Repository dotnet/winforms, pull requests merged in 2019-11, with the labels that each got.

#2092 APIcompat 3.0
  Directory.Build.props
  Directory.Build.targets
  eng/ApiCompatability/DesktopApiCompat.props
  eng/ApiCompatability/DesktopApiCompat.targets
  eng/ApiCompatability/DesktopAttributeTypeExclusions.txt
  eng/FacadeAssemblies.props
  eng/ResolveMatchingContract.targets
  eng/Tools.props
  eng/Version.Details.xml
  eng/Versions.props
  src/Accessibility/src/ApiCompatBaseline.txt
  src/System.Design/src/ApiCompatBaseline.netcoreapp.txt
  src/System.Design/src/ApiCompatBaseline.txt
  src/System.Drawing.Design/src/ApiCompatBaseline.txt
  src/System.Drawing/src/ApiCompatBaseline.txt
  src/System.Drawing/src/System.Drawing.Facade.csproj
  src/System.Windows.Forms/src/ApiCompatBaseline.txt
Labels: compliance, tenet-compatibility

#2259 Structify LOGPALETTE
  src/Common/src/Interop/Gdi32/Interop.LOGPALETTE.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
Labels: enhancement

#2254 Cleanup IsChild interop
  src/Common/src/Interop/User32/Interop.IsChild.cs
  src/Common/src/SafeNativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.cs
  src/System.Windows.Forms/src/System/Windows/Forms/UserControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowser.cs
Labels: enhancement

#2251 Structify more ListView messages
  src/Common/src/Interop/ComCtl32/Interop.LVGIT.cs
  src/Common/src/Interop/ComCtl32/Interop.NMLVCACHEHINT.cs
  src/Common/src/Interop/ComCtl32/Interop.NMLVGETINFOTIPW.cs
  src/Common/src/Interop/ComCtl32/Interop.NMLVKEYDOWN.cs
  src/Common/src/Interop/ComCtl32/Interop.NMLVODSTATECHANGE.cs
  src/Common/src/NativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
Labels: enhancement

#2246 Cleanup IOleInPlaceSite
  src/Common/src/Interop/Ole32/Interop.IOleInPlaceSite.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.OleInterfaces.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserSiteBase.cs
Labels: code cleanup, enhancement

#2242 Move DOCHOSTUIDBLCLK and DOCHOSTUIFLAG enums to separate files
  src/Common/src/Interop/Mshtml/Interop.DOCHOSTUIDBLCLK.cs
  src/Common/src/Interop/Mshtml/Interop.DOCHOSTUIFLAG.cs
  src/Common/src/NativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowser.cs
Labels: :octocat: automerge, enhancement

#2270 Don't recreate the handle twice in TabControl.Alignment setter
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControlTests.cs
Labels: enhancement, test-enhancement

#2267 Add GW enum and GetWindow methods to Interop User32
  src/Common/src/Interop/User32/Interop.GW.cs
  src/Common/src/Interop/User32/Interop.GetWindow.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Application.ParkingWindow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
Labels: enhancement

#2245 Add more Control tests especially for layout
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/tests/UnitTests/MonthCalendarTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHostTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ContainerControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Handlers.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Internals.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Methods.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Properties.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/ComponentEditorPageTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FlowLayoutPanelTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/HScrollBarTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PanelTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PictureBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ProgressBarTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollBarTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollableControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPageTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripPanelTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/VScrollBarTests.cs
Labels: test-enhancement

#2255 Remove assignment duplication
  src/System.Windows.Forms/src/System/Windows/Forms/Binding.cs
Labels: code cleanup

#2272 Cleanup GetParent interop
  src/Common/src/Interop/User32/Interop.GetParent.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Application.ParkingWindow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserSiteBase.cs
Labels: enhancement

#2268 Add TVHT enum in Interop ComCtl32 and remove corresponding constants …
  src/Common/src/Interop/ComCtl32/Interop.TVHT.cs
  src/Common/src/NativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeViewHitTestLocation.cs
Labels: enhancement

#2256 Cleanup TCS_ constants
  src/Common/src/Interop/ComCtl32/Interop.TCS.cs
  src/Common/src/NativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
Labels: enhancement

#2090 [Accessibility]: Adding MonthCalendar control UI Automation providers to improve calendar control accessibility
  src/Common/src/Interop/ComCtl32/Interop.MCGIF.cs
  src/Common/src/Interop/ComCtl32/Interop.MCGIP.cs
  src/Common/src/Interop/ComCtl32/Interop.MCGRIDINFO.cs
  src/Common/src/Interop/ComCtl32/Interop.MCHITTESTINFO.cs
  src/Common/src/Interop/ComCtl32/Interop.MCHT.cs
  src/Common/src/Interop/ComCtl32/Interop.MCM.cs
  src/Common/src/Interop/ComCtl32/Interop.MCS.cs
  src/Common/src/Interop/ComCtl32/Interop.MCSC.cs
  src/Common/src/Interop/Interop.POINT.cs
  src/Common/src/Interop/Kernel32/Interop.SYSTEMTIME.cs
  src/Common/src/Interop/User32/Interop.MOUSEEVENTF.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms/src/Resources/SR.resx
  src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarBodyAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarButtonAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarButtonType.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarCellAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarChildAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarChildType.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarGridChildAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarHeaderAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarNextButtonAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarPreviousButtonAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarRowAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarTodayLinkAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.MonthCalendarAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
Labels: servicing-approved

#2307 Structify CONTROLINFO
  src/Common/src/Interop/Ole32/Interop.CONTROLINFO.cs
  src/Common/src/Interop/Ole32/Interop.CTRLINFO.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.cs
Labels: enhancement

#2303 Cleanup MapWindowPoints interop
  src/Common/src/Interop/User32/Interop.MapWindowPoints.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ComponentTray.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripAdornerWindowService.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripDesigner.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs
  src/System.Windows.Forms/src/System/Windows/Forms/StatusStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.cs
  src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WinFormsUtils.cs
Labels: code cleanup, enhancement

#2194 Fix 2185 port missing code DOM serializers
  src/System.Windows.Forms.Design/src/Resources/SR.resx
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ActiveDesignSurfaceChangedEventArgs.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ActiveDesignSurfaceChangedEventHandler.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/CodeMarkerEvent.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignSurfaceCollection.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignSurfaceEvent.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignSurfaceManager.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerEventService.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/EventBindingService.EventPropertyDescriptor.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/EventBindingService.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/BasicDesignerLoader.ReloadOptions.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/BasicDesignerLoader.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomDesignerLoader.ModifierConverter.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomDesignerLoader.ModifiersExtenderProvider.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomDesignerLoader.ModifiersInheritedExtenderProvider.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomDesignerLoader.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomLocalizationModel.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomLocalizationProvider.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ICodeDomDesignerReload.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/LocalizationCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ResourcePropertyMemberCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/TypeCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewRowCollectionCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ImageCollectionCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TableLayoutControlCollectionCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TableLayoutPanelCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripMenuItemCodeDomSerializer.cs
Labels: servicing-approved

#2313 Cleanup OLEVERB
  src/Common/src/Interop/Ole32/Interop.OLEVERB.cs
  src/Common/src/Interop/Ole32/Interop.OLEVERBATTRIB.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXVerbEnum.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
Labels: enhancement

#2312 Rename TabPage fields
  src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
Labels: code cleanup

#2301 Cleanup PBS and PBM constants
  src/Common/src/Interop/ComCtl32/Interop.CCM.cs
  src/Common/src/Interop/ComCtl32/Interop.PBM.cs
  src/Common/src/Interop/ComCtl32/Interop.PBS.cs
  src/Common/src/NativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ProgressBar.cs
Labels: :octocat: automerge, enhancement

#2319 Structify EXCEPINFO
  src/Common/src/Interop/Ole32/Interop.EXCEPINFO.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.PropertyBagStream.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2AboutBoxPropertyDescriptor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/ComNativeDescriptor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlDocument.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlElement.cs
Labels: enhancement

#2324 Cleanup IsWindowEnabled/IsWindowVisible/EnableWindow
  src/Common/src/Interop/User32/Interop.EnableWindow.cs
  src/Common/src/Interop/User32/Interop.IsWindowEnabled.cs
  src/Common/src/Interop/User32/Interop.IsWindowVisible.cs
  src/Common/src/SafeNativeMethods.cs
  src/System.Windows.Forms.Design.Editors/src/Misc/NativeMethods.cs
  src/System.Windows.Forms.Design.Editors/src/System.Windows.Forms.Design.Editors.csproj
  src/System.Windows.Forms.Design.Editors/src/System/Drawing/Design/ColorEditor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadWindows.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDown.cs
Labels: enhancement

#2328 Structify DVTARGETDEVICE
  src/Common/src/Interop/Ole32/Interop.DVTARGETDEVICE.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
Labels: enhancement

#2299 Cleanup CCM and TCM constants
  src/Common/src/Interop/ComCtl32/Interop.TCM.cs
  src/Common/src/Interop/User32/Interop.WindowMessage.cs
  src/Common/src/NativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
Labels: enhancement

#2346 Structify TVHITTESTINFO and add more TreeView tests
  src/Common/src/Interop/ComCtl32/Interop.TVHITTESTINFO.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design.Editors/src/Misc/NativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewHitTestInfoTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs
Labels: enhancement, test-enhancement

#2291 Add IHandle and HandleRef overloads to GetWindow
  src/Common/src/Interop/User32/Interop.GetWindow.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
Labels: enhancement

#2354 Fix flakey tests
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs
Labels: test-bug

#2359 Add more Control tests
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Handlers.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Methods.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Properties.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs
Labels: test-enhancement

#2362 Add more ListView tests
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Labels: test-enhancement

#2327 Cleanup TrackPopupMenuEx interop
  src/Common/src/NativeMethods.cs
  src/Common/src/SafeNativeMethods.cs
Labels: code cleanup

#2258 Structify TCITEM
  src/Common/src/Interop/ComCtl32/Interop.TCIF.cs
  src/Common/src/Interop/ComCtl32/Interop.TCIS.cs
  src/Common/src/Interop/ComCtl32/Interop.TCITEMW.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.ControlCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControl.ControlCollectionTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControl.TabPageCollectionTests.cs
Labels: enhancement

#2349 Porting a Maui test MauiLabelTests to xUnit
  Winforms.sln
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiLabelTests/MauiLabelTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiLabelTests/MauiLabelTests.csproj
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.Maui.IntegrationTests/WinformsMauiLabelTests.cs
Labels: test-enhancement

#2345 Port ColumnHeaderCollectionEditor
  src/System.Design/src/System.Design.Forwards.cs
  src/System.Windows.Forms.Design.Editors/src/System/Windows/Forms/Design/ColumnHeaderCollectionEditor.cs
  src/System.Windows.Forms.Design.Editors/tests/UnitTests/System/Windows/Forms/Design/ColumnHeaderCollectionEditorTests .cs
Labels: area: UI type editors

#2355 Structify QACONTROL
  src/Common/src/Interop/Ole32/Interop.POINTERINACTIVE.cs
  src/Common/src/Interop/Ole32/Interop.QACONTROL.cs
  src/Common/src/Interop/Ole32/Interop.VIEWSTATUS.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
Labels: enhancement

#2379 Fixing LinkLabel text color setting
  src/Common/src/Interop/Gdi32/Interop.SetTextColor.cs
Labels: waiting-review

#2388 Subscribe to MSRC on internal CI
  azure-pipelines.yml
Labels: :octocat: automerge

#2386 Switch to non-stable
  azure-pipelines.yml
  eng/Versions.props
Labels: :octocat: automerge

#2384 Cleanup IConnectionPoint interface
  src/Common/src/Interop/Ole32/Interop.IConnectionPoint.cs
  src/Common/src/Interop/Ole32/Interop.IConnectionPointContainer.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.ConnectionPointCookie.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHost.ConnectionPointCookieTests.cs
Labels: enhancement, test-enhancement

#2331 Extract ThemingScope interop and move it to Common
  src/Common/src/Interop/Kernel32/Interop.ACTCTXW.cs
  src/Common/src/Interop/Kernel32/Interop.ACTCTX_FLAG.cs
  src/Common/src/Interop/Kernel32/Interop.ActivateActCtx.cs
  src/Common/src/Interop/Kernel32/Interop.CreateActCtxW.cs
  src/Common/src/Interop/Kernel32/Interop.DeactivateActCtx.cs
  src/Common/src/Interop/Kernel32/Interop.GetCurrentActCtx.cs
  src/Common/src/ThemingScope.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System.Windows.Forms.csproj
  src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
  src/System.Windows.Forms/src/System/Windows/Forms/CommonDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ImageListStreamer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MessageBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ProgressBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/StatusBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
Labels: enhancement

#2392 Move IErrorLog and IPropertyBag interfaces to interop
  src/Common/src/Interop/Ole32/Interop.IErrorLog.cs
  src/Common/src/Interop/Ole32/Interop.IPropertyBag.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.PropertyBagStream.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.State.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
Labels: enhancement

#2347 Port DataGridViewCellStyleEditor
  src/System.Design/src/System.Design.Forwards.cs
  src/System.Windows.Forms.Design.Editors/src/Resources/SR.Designer.cs
  src/System.Windows.Forms.Design.Editors/src/Resources/SR.resx
  src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms.Design.Editors/src/System/Windows/Forms/Design/DataGridViewCellStyleBuilder.cs
  src/System.Windows.Forms.Design.Editors/src/System/Windows/Forms/Design/DataGridViewCellStyleEditor.cs
  src/System.Windows.Forms.Design.Editors/src/System/Windows/Forms/Design/DataGridViewComponentPropertyGridSite.cs
  src/System.Windows.Forms.Design.Editors/tests/UnitTests/System/Windows/Forms/Design/DataGridViewCellStyleEditorTests.cs
Labels: area: UI type editors

#2385 Add ProfessionalColors tests
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ProfessionalColorTableTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ProfessionalColorsTests.cs
Labels: test-enhancement

#2266 Move KeyboardLayout methods to Interop User32
  src/Common/src/Interop/User32/Interop.ActivateKeyboardLayout.cs
  src/Common/src/Interop/User32/Interop.GetKeyboardLayout.cs
  src/Common/src/Interop/User32/Interop.GetKeyboardLayoutList.cs
  src/Common/src/SafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
Labels: enhancement

#2371 Add more tests
  src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Handlers.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Methods.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Properties.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PictureBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPageTests.TabPageControlCollection.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPageTests.cs
Labels: test-enhancement

#2294 Remove SYSTEMTIMEARRAY
  src/Common/src/NativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
Labels: enhancement

#2321 Cleanup InputLanguage interop
  src/Common/src/Interop/User32/Interop.ActivateKeyboardLayout.cs
  src/Common/src/Interop/User32/Interop.GetKeyboardLayout.cs
  src/Common/src/Interop/User32/Interop.GetKeyboardLayoutList.cs
  src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/InputLanguageTests.cs
Labels: :mailbox_with_mail: waiting-for-testing, enhancement, test-enhancement

#2363 Add more Panel tests
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PanelTests.cs
Labels: test-enhancement

#2394 Move ITextDocument and ITextRange out of UnsafeNativeMethods
  src/Common/src/Interop/Richedit/Interop.ITextDocument.cs
  src/Common/src/Interop/Richedit/Interop.ITextRange.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
Labels: enhancement

#2383 Move IQuickActivate to Ole32
  src/Common/src/Interop/Ole32/Interop.IQuickActivate.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
Labels: enhancement

#2404 Update feeds for tooling and .net 3
  NuGet.config
Labels: area: CI

#2330 Cleanup IViewObject.Draw interop
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserHelper.cs
Labels: enhancement

#2353 Cleanup LVBKIMAGEW
  src/Common/src/Interop/ComCtl32/Interop.LVBKIF.cs
  src/Common/src/Interop/ComCtl32/Interop.LVBKIMAGEW.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
Labels: enhancement

#2364 Add FontDialog tests
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FontDialogTests.cs
Labels: test-enhancement

#2277 Move GetThemeSysBool and GetThemeSysInt to Interop UxTheme and add TM…
  src/Common/src/Interop/UxTheme/Interop.GetThemeSysBool.cs
  src/Common/src/Interop/UxTheme/Interop.GetThemeSysInt.cs
  src/Common/src/Interop/UxTheme/Interop.TMT.cs
  src/Common/src/SafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleInformation.cs
Labels: enhancement

#2399 Add ComCtl32 control tests and fix a debug assert failure
  src/System.Windows.Forms/tests/UnitTests/ButtonTests.cs
  src/System.Windows.Forms/tests/UnitTests/CheckBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/DateTimePickerTests.cs
  src/System.Windows.Forms/tests/UnitTests/LabelTests.cs
  src/System.Windows.Forms/tests/UnitTests/RadioButtonTests.cs
  src/System.Windows.Forms/tests/UnitTests/RichTextBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ButtonBaseTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ContainerControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Methods.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/ComponentEditorPageTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FlowLayoutPanelTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/HScrollBarTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PictureBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ProgressBarTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollBarTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollableControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripPanelTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolTipTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/VScrollBarTests.cs
  src/System.Windows.Forms/tests/UnitTests/TextBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/TrackBarTests.cs
Labels: test-enhancement

#2429 Cleanup PatBlt interop
  src/Common/src/Interop/Gdi32/Interop.PatBlt.cs
  src/Common/src/SafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SplitContainer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Splitter.cs
Labels: enhancement

#2422 Add WindowsFormsSynchronizationContext tests and remove some dead code
  src/System.Windows.Forms/src/System/Windows/Forms/WindowsFormsSynchronizationContext.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/WindowsFormsSynchronizationContextTests.cs
Labels: test-enhancement

#2230 Add designer attribute tests
  src/System.Design/src/System.Design.Forwards.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/DesignerAttributeTests.cs
Labels: test-enhancement

#2206 Add CommDlgExtendedError method in Comdlg32 and FNERR enum and replac…
  src/Common/src/Interop/Comdlg32/Interop.CommDlgExtendedError.cs
  src/Common/src/Interop/Comdlg32/Interop.FNERR.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/SafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/OpenFileDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SaveFileDialog.cs
Labels: enhancement

#2367 Cleanup MONITORINFOEX
  src/Common/src/Interop/User32/Interop.GetMonitorInfoW.cs
  src/Common/src/Interop/User32/Interop.MONITORINFOEXW.cs
  src/Common/src/Interop/User32/Interop.MONITORINFOF.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/SafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Screen.cs
Labels: enhancement

#2257 Cleanup WC_ constants
  src/Common/src/Interop/ComCtl32/Interop.WindowClasses.cs
  src/Common/src/NativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Button.cs
  src/System.Windows.Forms/src/System/Windows/Forms/CheckBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.cs
  src/System.Windows.Forms/src/System/Windows/Forms/GroupBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Label.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ProgressBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridToolTip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/RadioButton.cs
  src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/RichTextBoxConstants.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/StatusBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
  src/System.Windows.Forms/tests/UnitTests/ButtonTests.cs
  src/System.Windows.Forms/tests/UnitTests/CheckBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/LabelTests.cs
  src/System.Windows.Forms/tests/UnitTests/RadioButtonTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/HScrollBarTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollBarTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/VScrollBarTests.cs
  src/System.Windows.Forms/tests/UnitTests/TextBoxTests.cs
Labels: enhancement

#2433 Cleanup CF_ constants
  src/Common/src/Interop/Comdlg32/Interop.CF.cs
  src/Common/src/NativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms/src/System/Windows/Forms/FontDialog.cs
Labels: enhancement

#2428 Cleanup ControlPaint interop
  src/Common/src/Interop/Gdi32/Interop.CreateDIBSection.cs
  src/Common/src/Interop/Gdi32/Interop.CreateHalftonePalette.cs
  src/Common/src/Interop/Gdi32/Interop.DIB.cs
  src/Common/src/SafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs
Labels: enhancement

#2437 Add tests to verify joint behaviours pertaining to `ThreeState`, `CheckState` and `Checked`
  src/System.Windows.Forms/tests/UnitTests/CheckBoxTests.cs
Labels: test-enhancement

#2398 Cleanup ValidateRect and add tests for affected components
  src/Common/src/Interop/User32/Interop.ValidateRect.cs
  src/Common/src/SafeNativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs
  src/System.Windows.Forms.Design/tests/UnitTests/ControlDesignerTests.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
Labels: enhancement, test-enhancement

#2261 Consolidate PARAM methods
  src/Common/src/Interop/Interop.PARAM.cs
  src/Common/src/NativeMethods.cs
  src/System.Windows.Forms.Design.Editors/src/Misc/NativeMethods.cs
  src/System.Windows.Forms.Design.Editors/src/System.Windows.Forms.Design.Editors.csproj
  src/System.Windows.Forms.Design.Editors/src/System/Drawing/Design/ColorEditor.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ComponentTray.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerFrame.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerUtils.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripDesigner.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Application.ParkingWindow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Button.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs
  src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DpiChangedEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
  src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MessageDecoder.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollableControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/StatusBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/StatusStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowser.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WinFormsUtils.cs
Labels: code cleanup, enhancement

#2445 Add WA enum to User32
  src/Common/src/Interop/User32/Interop.WA.cs
  src/Common/src/NativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionUI.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDown.cs
Labels: enhancement

#2450 Add ColorDialog tests
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ColorDialogTests.cs
Labels: test-enhancement

#2448 Add GroupBox tests and related Control methods
  src/System.Windows.Forms/src/System/Windows/Forms/PaintEventArgs.cs
  src/System.Windows.Forms/src/misc/GDI/WindowsGraphics.cs
  src/System.Windows.Forms/tests/UnitTests/GroupBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Handlers.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Methods.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs
Labels: enhancement
