Repository dotnet/winforms, pull requests merged in 2019-12, with the labels that each got.

#2401 Add AccessibleObject tests
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjectTests.cs
Labels: test-enhancement

#2452 Move GetAncestor to Interop User32 and add GA enum
  src/Common/src/Interop/User32/Interop.GA.cs
  src/Common/src/Interop/User32/Interop.GetAncestor.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.Ime.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WinFormsUtils.cs
Labels: enhancement

#2329 Move IEnumOLEVERB to interop
  src/Common/src/Interop/Ole32/Interop.IEnumOLEVERB.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXVerbEnum.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
Labels: enhancement

#2304 Cleanup PostMessage interop
  src/Common/src/Interop/User32/Interop.PostMessageW.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design.Editors/src/Misc/NativeMethods.cs
  src/System.Windows.Forms.Design.Editors/src/System.Windows.Forms.Design.Editors.csproj
  src/System.Windows.Forms.Design.Editors/src/System/Drawing/Design/ColorEditor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Application.ParkingWindow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/CommonDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MenuStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/NotifyIcon.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Timer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripMenuItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
Labels: enhancement

#2456 Move IsThemeBackgroundPartiallyTransparent to Interop UxTheme
  src/Common/src/Interop/UxTheme/Interop.IsThemeBackgroundPartiallyTransparent.cs
  src/Common/src/SafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/VisualStyles/VisualStyleRendererTests.cs
Labels: enhancement

#2221 Remove NativeMethods, SafeNativeMethods and UnsafeNativeMethods classes from DesignerActionPanel.cs
  src/Common/src/Interop/User32/Interop.SetWindowLong.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.cs
Labels: code cleanup

#2487 Remove unused ATTR and IDM constants
  src/Common/src/NativeMethods.cs
Labels: code cleanup

#2472 Add more ScrollableControl tests
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollableControlTests.cs
Labels: test-enhancement

#2469 Add NativeWindow tests
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/NativeWindowTests.cs
Labels: enhancement

#2457 Add UpDownBase tests and related Control tests
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHostTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ButtonBaseTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ButtonTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CheckBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ContainerControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Handlers.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Internals.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Methods.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Properties.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DateTimePickerTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/ComponentEditorPageTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FlowLayoutPanelTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/GroupBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/HScrollBarTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/LabelTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PanelTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PictureBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ProgressBarTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RadioButtonTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollBarTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollableControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPageTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripPanelTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/UpDownBaseTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/VScrollBarTests.cs
  src/System.Windows.Forms/tests/UnitTests/TextBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/TrackBarTests.cs
Labels: test-enhancement

#2496 Cleanup GetWindowRect interop
  src/Common/src/Interop/User32/Interop.GetWindowRect.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/CommonDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
  src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SplitContainer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
Labels: enhancement

#2494 Cleanup LB constants
  src/Common/src/Interop/User32/Interop.LB.cs
  src/Common/src/Interop/User32/Interop.LBN.cs
  src/Common/src/NativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.ItemAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs
Labels: enhancement

#2460 Fix issues in Interop.User32.GetWindowText
  src/Common/src/Interop/User32/Interop.GetWindowText.cs
  src/System.Windows.Forms/tests/UnitTests/InteropTests/GetWindowTextTests.cs
Labels: test-enhancement

#2493 Remove unused CorRuntimeHost and ICorRuntimeHost from UnsafeNativeMet…
  src/Common/src/UnsafeNativeMethods.cs
Labels: :octocat: automerge

#2482 Cleanup Control.SendMessage ref rect overload
  src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewInsertionMark.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewInsertionMarkTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControlTests.cs
Labels: enhancement, test-enhancement

#2408 Cleanup DIB related interop
  src/Common/src/Interop/Gdi32/Interop.BI.cs
  src/Common/src/Interop/Gdi32/Interop.BITMAPINFO.cs
  src/Common/src/Interop/Gdi32/Interop.BITMAPINFOHEADER.cs
  src/Common/src/Interop/Gdi32/Interop.GetDIBits.cs
  src/Common/src/Interop/Gdi32/Interop.StretchDIBits.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/SafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.MetafileDCWrapper.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs
Labels: enhancement

#2484 Add HBMMENU enum to Interop User32
  src/Common/src/Interop/User32/Interop.HBMMENU.cs
  src/Common/src/NativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripMenuItem.cs
Labels: enhancement

#2509 Add ToolStripItem tests and tests for related components
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Properties.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemTests.cs
Labels: test-enhancement

#2508 Remove always undefined SELECTEDCHANGED
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
Labels: code cleanup

#2512 Don't create Handle in MonthCalendar.OnHandleCreated
  src/Common/src/Interop/ComCtl32/Interop.MCM.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Handlers.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs
Labels: test-enhancement

#2513 Fix some coverage gaps in CommonDialog
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CommonDialogTests.cs
Labels: test-enhancement

#2519 Don't force create handle in TabPageCollectionTests.Clear
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControl.TabPageCollectionTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControlTests.cs
Labels: enhancement, test-enhancement

#2489 Add OFN and OFN_EX enums to Interop Comdlg32
  src/Common/src/Interop/Comdlg32/Interop.OFN.cs
  src/Common/src/Interop/Comdlg32/Interop.OFN_EX.cs
  src/Common/src/NativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/FileDialog_Vista.cs
  src/System.Windows.Forms/src/System/Windows/Forms/OpenFileDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SaveFileDialog.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FileDialogTests.cs
Labels: enhancement

#2534 Remove unused SetClassLong, SetClassLongPtr32 and SetClassLongPtr64 from UnsafeNativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
Labels: code cleanup

#2537 Remove unused TB and TBN constants
  src/Common/src/NativeMethods.cs
Labels: code cleanup

#2572 Add DataGridView selected collection tests
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/BaseCollectionTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewSelectedCellCollectionTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewSelectedColumnCollectionTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewSelectedRowCollectionTests.cs
Labels: test-enhancement

#2577 Add ToolStripSeparator tests
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSeparator.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripSeparatorTests.cs
Labels: code cleanup, test-enhancement

#2575 Add ToolStripButton tests
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripButtonTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemTests.cs
Labels: test-enhancement

#2574 Improve ColumnStyle/Row/TableLayout style tests
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ColumnStyleTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RowStyleTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TableLayoutStyleTests.cs
Labels: test-enhancement

#2571 Remove Control.GetVisibleCore
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDown.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownItem.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Internals.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Properties.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FormTests.cs
Labels: enhancement

#2565 Add Microsoft.DotNet.RemoteExecutor package reference to tests
  eng/Version.Details.xml
  eng/Versions.props
  src/Common/tests/InternalUtilitiesForTests/InternalUtilitiesForTests.csproj
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ApplicationTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CommonDialogTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/GroupBoxTests.cs
Labels: test-enhancement

#2552 Cleanup and improve ComponentEditorPage testing
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/ComponentEditorPageTests.cs
Labels: test-enhancement

#2583 Remove dead SetSelectionInCreateHandle flag
  src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
Labels: code cleanup

#2553 Improve tests for FlowLayoutPanel/FlowLayoutSettings
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FlowLayoutPanelTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FlowLayoutSettingsTests.cs
Labels: test-enhancement

#2567 Add StatusStrip tests
  src/System.Windows.Forms/tests/UnitTests/StatusStripTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Methods.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/GroupBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ProgressBarTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollableControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/StatusStripTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
Labels: test-enhancement
