Repository dotnet/winforms, pull requests merged in 2019-08, with the labels that each got.

#1524 The CellParsing event of the datagridview can't be invoked when changing the value of the cell firstly #1098
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxEditingControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxEditingControl.cs
Labels: AutoMerge

#1543 add yaml stages to meet arcade servicing bar
  azure-pipelines.yml
  eng/ci.yml
Labels: tell-mode

#1563 Add missing StructLayout
  src/Common/src/NativeMethods.cs
Labels: tell-mode

#1557 fix: `AccessibleObject` throws 'Value does not fall within the expected range.' creating `CollectionEditor`
  src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
Labels: tell-mode

#1483 Fix some Binding bugs
  src/System.Windows.Forms/src/System/Windows/Forms/BindingContext.cs
  src/System.Windows.Forms/src/System/Windows/Forms/BindingSource.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/BindingContextTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/BindingSourceTests.cs
Labels: tell-mode

#1545 Porting DataMemberFieldConverter into core
  src/System.Windows.Forms.Design/src/Resources/SR.resx
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataMemberFieldConverter.cs
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/DataMemberFieldConverterTests.cs
  src/System.Windows.Forms/src/AssemblyRef.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumn.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxColumn.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListControl.cs
Labels: tell-mode

#1541 Cleanup Control event and property naming
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.Ime.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MenuItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollableControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SplitContainer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ThreadExceptionDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDown.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.cs
Labels: tell-mode

#1481 Consolidate IStream code
  src/Common/src/Interop/Interop.HRESULT.cs
  src/Common/src/Interop/Interop.Libraries.cs
  src/Common/src/Interop/Ole32/Interop.CreateILockBytesOnHGlobal.cs
  src/Common/src/Interop/Ole32/Interop.GPStream.cs
  src/Common/src/Interop/Ole32/Interop.GetHGlobalFromILockBytes.cs
  src/Common/src/Interop/Ole32/Interop.ILockBytes.cs
  src/Common/src/Interop/Ole32/Interop.IPersistStorage.cs
  src/Common/src/Interop/Ole32/Interop.IPersistStream.cs
  src/Common/src/Interop/Ole32/Interop.IPersistStreamInit.cs
  src/Common/src/Interop/Ole32/Interop.IStorage.cs
  src/Common/src/Interop/Ole32/Interop.IStream.cs
  src/Common/src/Interop/Ole32/Interop.STATFLAG.cs
  src/Common/src/Interop/Ole32/Interop.STATSTG.cs
  src/Common/src/Interop/Ole32/Interop.STGC.cs
  src/Common/src/Interop/Ole32/Interop.STGM.cs
  src/Common/src/Interop/Ole32/Interop.STGTY.cs
  src/Common/src/Interop/Ole32/Interop.StgCreateDocfileOnILockBytes.cs
  src/Common/src/Interop/Ole32/Interop.StgOpenStorageOnILockBytes.cs
  src/Common/src/Interop/Richedit/Interop.CHARRANGE.cs
  src/Common/src/Interop/Richedit/Interop.IRichEditOleCallback.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/SafeNativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design.Editors/src/Misc/NativeMethods.cs
  src/System.Windows.Forms.Design.Editors/src/Misc/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design.Editors/src/System.Windows.Forms.Design.Editors.csproj
  src/System.Windows.Forms.Design.Editors/src/System/ComponentModel/Design/MultilineStringEditor.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms/src/System.Windows.Forms.csproj
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2TypeInfoProcessor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.Ime.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Cursor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataStreamFromComStream.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ImageListStreamer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowser.cs
  src/System.Windows.Forms/tests/UnitTests/DataStreamFromComStreamTests.cs
  src/System.Windows.Forms/tests/UnitTests/SerializableTypesTests.cs
Labels: enhancement, tell-mode

#1551 fix SnapLine is not implemented
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/SnapLine.cs
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/Behavior/SnapLineTests.cs
Labels: tell-mode

#1530 Add Screen/SystemInformation tests
  src/System.Windows.Forms/src/System/Windows/Forms/Screen.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScreenTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/SystemInformationTests.cs
Labels: Cleanup, enhancement, tell-mode

#1573 Remove unused .RESX files from Templates
  Documentation/images/templates-check-installed.png
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/Microsoft.Dotnet.Winforms.ProjectTemplates.csproj
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/Form1.resx
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/Program.cs
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/Form1.resx
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/readme.md
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PanelTests.cs
Labels: tell-mode

#1603 Fix screen related tests
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CursorTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScreenTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/SystemInformationTests.cs
Labels: AutoMerge

#1583 Remove pointstruct and friends
  src/Common/src/Interop/Gdi32/Interop.GetTextExtentPoint32.cs
  src/Common/src/Interop/Interop.HRESULT.cs
  src/Common/src/Interop/Ole32/Interop.IDropTarget.cs
  src/Common/src/Interop/Ole32/Interop.RegisterDragDrop.cs
  src/Common/src/Interop/Ole32/Interop.RevokeDragDrop.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/SafeNativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design.Editors/src/Misc/NativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Button.cs
  src/System.Windows.Forms/src/System/Windows/Forms/CheckBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DropTarget.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/RadioButton.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Screen.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropTargetManager.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.cs
  src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowser.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserSiteBase.cs
  src/System.Windows.Forms/src/misc/GDI/UnsafeNativeMethods.cs
Labels: Cleanup

#1592 Fixing DataGridViewCell AccessibleObject Value.IsReadOnly property
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs
  src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/DataGridViewCellAccessibleObjectTests.cs
Labels: a11yMAS

#1594 Fixing menu control type and menu items navigation
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDown.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
Labels: AutoMerge, a11yMAS

#1635 Set system aware mode in project templates c#
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/Program.cs
Labels: ask-mode

#1637 Add system.resource.extensions as a dependency from corefx
  eng/Version.Details.xml
  eng/Versions.props
  src/System.Windows.Forms/src/System.Windows.Forms.csproj
Labels: tell-mode

#1612 Fix tooltip crash and harden
  src/Common/src/Interop/ComCtl32/Interop.TTDT.cs
  src/Common/src/Interop/ComCtl32/Interop.TTTOOLINFOW.cs
  src/Common/src/Interop/Interop.PARAM.cs
  src/Common/src/Interop/Interop.WindowMessages.cs
  src/Common/src/Interop/User32/Interop.SendMessageW.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridToolTip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.cs
  src/System.Windows.Forms/src/System/Windows/Forms/IHandle.cs
  src/System.Windows.Forms/src/System/Windows/Forms/KeyboardToolTipStateMachine.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridToolTip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/StatusBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
Labels: ask-mode

#1616 Fix 1615: Disabling ToolTip visual styles to make it enough contrasted in HC mode.
  src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
Labels: a11yMAS, ask-mode, bug, tenet-accessibility

#1139 Remove .NET Framework isms
  src/Common/src/Interop/Interop.Libraries.cs
  src/Common/tests/InternalUtilitiesForTests/src/AssertExtensions.cs
  src/Common/tests/InternalUtilitiesForTests/src/PlatformDetection.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializerBase.cs
  src/System.Windows.Forms/src/Common/System/LocalAppContext.cs
  src/System.Windows.Forms/src/System/Resources/ResXDataNode.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.cs
  src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.cs
  src/System.Windows.Forms/src/System/Windows/Forms/LocalAppContextSwitches.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MaskedTextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/RichTextBoxConstants.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDown.cs
  src/System.Windows.Forms/tests/UnitTests/SerializableAttributeTests.cs
Labels: ask-mode

#1657 change agent pools to deal with recent build delays
  azure-pipelines.yml
  eng/ci.yml
Labels: tell-mode

#1661 Properly add and remove reflect children
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/MainFormControlsTabOrder.cs
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests/WinformsControlsTest.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinFormsControlsClassicTests/WinFormsControlsClassicTests.csproj
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ComboBoxes.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ComboBoxes.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Data/example.rtf
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListViewTest.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/RichTextBoxes.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/RichTextBoxes.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/WinformsControlsTest.csproj
Labels: ask-mode, bug

#1642 Disabling SystemRendering mode for ToolStrip in HC mode to make buttons contrasted
  src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewDialog.cs
Labels: ask-mode, tenet-accessibility
