Repository dotnet/winforms, pull requests merged in 2019-09, with the labels that each got.

#1692 [Accessibility]: Fixing ToolStripComboBox/ComboBox edit element AccessibleName property value
  src/System.Windows.Forms/src/Resources/SR.resx
  src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
  src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/ComboBoxAccessibleObjectTests.cs
Labels: a11yMAS, ask-mode, tenet-accessibility

#1684 Retarget to .NET 5.0
  Directory.Build.props
  Directory.Build.targets
  Documentation/building.md
  Documentation/debugging.md
  Documentation/testing.md
  Documentation/winforms-designer.md
  eng/CodeCoverage.proj
  eng/Version.Details.xml
  eng/Versions.props
  eng/common/templates/job/performance.yml
  global.json
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/Microsoft.Dotnet.Winforms.ProjectTemplates.csproj
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/.template.config/template.json
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/Company.WinFormsApplication1.csproj
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/.template.config/template.json
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/Company.WinFormsApplication1.vbproj
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-CSharp/.template.config/template.json
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-CSharp/Company.ClassLibrary1.csproj
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-VisualBasic/.template.config/template.json
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-VisualBasic/Company.ClassLibrary1.vbproj
  pkg/Microsoft.Private.Winforms/Microsoft.Private.Winforms.csproj
  src/Accessibility/src/Accessibility.ilproj
  src/Accessibility/ver/Accessibility-version.csproj
  src/Common/tests/Directory.Build.props
  src/Common/tests/InternalUtilitiesForTests/InternalUtilitiesForTests.csproj
  src/System.Design/Directory.Build.props
  src/System.Design/src/System.Design.Facade.csproj
  src/System.Drawing.Design/Directory.Build.props
  src/System.Drawing.Design/src/System.Drawing.Design.Facade.csproj
  src/System.Drawing/Directory.Build.props
  src/System.Drawing/src/System.Drawing.Facade.csproj
  src/System.Windows.Forms.Design.Editors/Directory.Build.props
  src/System.Windows.Forms.Design.Editors/src/System.Windows.Forms.Design.Editors.csproj
  src/System.Windows.Forms.Design.Editors/tests/UnitTests/System.Windows.Forms.Design.Editors.Tests.csproj
  src/System.Windows.Forms.Design/Directory.Build.props
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms.Design/tests/UnitTests/System.Windows.Forms.Design.Tests.csproj
  src/System.Windows.Forms/Directory.Build.props
  src/System.Windows.Forms/src/System.Windows.Forms.csproj
  src/System.Windows.Forms/tests/AccessibilityTests/AccessibilityTests.csproj
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiButtonTests/MauiButtonTests.csproj
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiComboBoxTests/MauiComboBoxTests.csproj
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/System.Windows.Forms.IntegrationTests.Common.csproj
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/TestHelpers.cs
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests/System.Windows.Forms.IntegrationTests.csproj
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.Maui.IntegrationTests/System.Windows.Forms.Maui.IntegrationTests.csproj
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.Maui.IntegrationTests/readme.md
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/WinformsControlsTest.csproj
  src/System.Windows.Forms/tests/UnitTests/SerializableTypesTests.cs
  src/System.Windows.Forms/tests/UnitTests/System.Windows.Forms.Tests.csproj
Labels: enhancement

#1722 fix `PowerStatus_BatteryChargeStatus_Get_ReturnsExpected` test
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PowerStatusTests.cs
Labels: test-bug

#1745 fix: RichTextBox `LinkClicked` event for "friendly named" hyperlinks
  src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinFormsControlsClassicTests/WinFormsControlsClassicTests.csproj
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/RichTextBoxes.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/RichTextBoxes.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/RichTextBoxes.resx
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/RichTextBoxes.cs.xlf
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/RichTextBoxes.de.xlf
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/RichTextBoxes.es.xlf
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/RichTextBoxes.fr.xlf
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/RichTextBoxes.it.xlf
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/RichTextBoxes.ja.xlf
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/RichTextBoxes.ko.xlf
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/RichTextBoxes.pl.xlf
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/RichTextBoxes.pt-BR.xlf
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/RichTextBoxes.ru.xlf
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/RichTextBoxes.tr.xlf
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/RichTextBoxes.zh-Hans.xlf
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/RichTextBoxes.zh-Hant.xlf
Labels: ask-mode

#1751 Fixing ToolStripMenu checked box rendering issue when Visual Styles are ON
  src/Common/src/Interop/UxTheme/Interop.GetThemeDocumentationProperty.cs
  src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleInformation.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/VisualStyles/VisualStyleInformationTests.cs
Labels: Regression, ask-mode

#1730 Cleanup IEnumVariant
  src/Common/src/Interop/OleAut32/Interop.IEnumVariant.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design.Editors/src/Misc/NativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
Labels: Cleanup, enhancement

#1574 Cleanup Control.GetState/GetState2
  src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlNativeWindow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ExtendedStates.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.States.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.UICuesStates.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
  src/System.Windows.Forms/src/System/Windows/Forms/GroupBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Label.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MDIClient.cs
  src/System.Windows.Forms/src/System/Windows/Forms/NumericUpDown.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Panel.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PictureBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollableControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SendKeys.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDown.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripOverflow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/UserControl.cs
Labels: Cleanup, enhancement

#1805 Cleanup misc Ole32 interop
  src/Common/src/Interop/Interop.HRESULT.cs
  src/Common/src/Interop/Ole32/Interop.CLSCTX.cs
  src/Common/src/Interop/Ole32/Interop.CoCreateInstance.cs
  src/Common/src/Interop/Ole32/Interop.CoGetClassObject.cs
  src/Common/src/Interop/Ole32/Interop.IClassFactory2.cs
  src/Common/src/Interop/Ole32/Interop.LICINFO.cs
  src/Common/src/Interop/Ole32/Interop.OleInitialize.cs
  src/Common/src/Interop/Ole32/Interop.OleUninitialize.cs
  src/Common/src/Interop/Ole32/Interop.ReadClassStg.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design.Editors/src/Misc/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design.Editors/src/System.Windows.Forms.Design.Editors.csproj
  src/System.Windows.Forms.Design.Editors/src/System/ComponentModel/Design/MultilineStringEditor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/StringSource.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.cs
Labels: Cleanup, enhancement

#1813 Add more Control/AxHost tests
  src/System.Windows.Forms/tests/UnitTests/MenuItemTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHostTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ContainerControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/ComponentEditorPageTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FlowLayoutPanelTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/HScrollBarTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PanelTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PictureBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollBarTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollableControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPageTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/VScrollBarTests.cs
Labels: test-enhancement

#1778 Cleanup IRawElementProviderSimple and dependencies
  src/Common/src/Interop/Interop.Libraries.cs
  src/Common/src/Interop/UiaCore/Interop.IGridItemProvider.cs
  src/Common/src/Interop/UiaCore/Interop.IRawElementProviderFragment.cs
  src/Common/src/Interop/UiaCore/Interop.IRawElementProviderFragmentRoot.cs
  src/Common/src/Interop/UiaCore/Interop.IRawElementProviderHwndOverride.cs
  src/Common/src/Interop/UiaCore/Interop.IRawElementProviderSimple.cs
  src/Common/src/Interop/UiaCore/Interop.ISelectionItemProvider.cs
  src/Common/src/Interop/UiaCore/Interop.NavigateDirection.cs
  src/Common/src/Interop/UiaCore/Interop.ProviderOptions.cs
  src/Common/src/Interop/UiaCore/Interop.StructureChangeType.cs
  src/Common/src/Interop/UiaCore/Interop.UiaClientsAreListening.cs
  src/Common/src/Interop/UiaCore/Interop.UiaHostProviderFromHwnd.cs
  src/Common/src/Interop/UiaCore/Interop.UiaRaiseAutomationEvent.cs
  src/Common/src/Interop/UiaCore/Interop.UiaRaiseAutomationPropertyChangedEvent.cs
  src/Common/src/Interop/UiaCore/Interop.UiaRaiseNotificationEvent.cs
  src/Common/src/Interop/UiaCore/Interop.UiaRaiseStructureChangedEvent.cs
  src/Common/src/Interop/UiaCore/Interop.UiaRect.cs
  src/Common/src/Interop/UiaCore/Interop.UiaReturnRawElementProvider.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.AccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.TopRowAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnHeaderCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxEditingControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowHeaderCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxEditingControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTopLeftHeaderCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.AccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.ItemAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/CategoryGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/DocComment.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/DropDownButton.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/HotCommands.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/StatusStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripControlHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripProgressBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSplitButton.cs
  src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/ComboBoxAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/ToolStripAccessibleObjectTests.cs
Labels: Cleanup, enhancement

#1747 Fix issue 1746 - Screen reader is not announcing change in expanded/collapsed state of PropertyGrid Category item
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/CategoryGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
Labels: a11yMAS, ask-mode

#1841 [release/3.0] Mark transport packages as non-shipping
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/Microsoft.Dotnet.Winforms.ProjectTemplates.csproj
  pkg/Microsoft.Private.Winforms/Microsoft.Private.Winforms.csproj
Labels: ask-mode, waiting-approval

#1704 Fix issue 1703 - Adding ExpandCollapse pattern to DataGridViewComboBoxCell
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxCell.cs
  src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/DataGridViewComboBoxCellAccessibleObjectTests.cs
Labels: ask-mode

#1706 Fix issue 1705 - Accessibility: PropertyGridView should support Table and Grid accessibility patterns
  src/Common/src/NativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/CategoryGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
  src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/PropertyGridViewAccessibleObjectTests.cs
Labels: a11yMAS, ask-mode

#1852 Tests `FormBorderStyles`
  src/System.Windows.Forms/tests/IntegrationTests/WinFormsControlsClassicTests/WinFormsControlsClassicTests.csproj
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/FormBorderStyles.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/FormBorderStyles.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/FormBorderStyles.resx
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/FormBorderStyles.cs.xlf
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/FormBorderStyles.de.xlf
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/FormBorderStyles.es.xlf
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/FormBorderStyles.fr.xlf
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/FormBorderStyles.it.xlf
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/FormBorderStyles.ja.xlf
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/FormBorderStyles.ko.xlf
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/FormBorderStyles.pl.xlf
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/FormBorderStyles.pt-BR.xlf
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/FormBorderStyles.ru.xlf
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/FormBorderStyles.tr.xlf
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/FormBorderStyles.zh-Hans.xlf
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/FormBorderStyles.zh-Hant.xlf
Labels: tell-mode, test-enhancement

#1901 fix: DataBindings.Remove/Clear unsubscribe from the INotifyPropertyChanged.PropertyChanged event
  src/System.Windows.Forms/src/System/Windows/Forms/Binding.cs
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests/Mocks/MainObject.cs
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests/WinformsControlsTest.cs
Labels: Regression, tenet-compatibility

#1886 Cleanup COMRECT interop in some IOle interfaces
  src/Common/src/NativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserHelper.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserSiteBase.cs
Labels: AutoMerge

#1919 Structify TRACKMOUSEEVENT
  src/Common/src/Interop/User32/Interop.TME.cs
  src/Common/src/Interop/User32/Interop.TrackMouseEvent.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/SafeNativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs
Labels: AutoMerge

#1925 Add some ListView tests and more Control tests
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHostTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ContainerControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridTableStyleTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/ComponentEditorPageTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FlowLayoutPanelTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/HScrollBarTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PanelTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PictureBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollBarTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollableControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPageTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/VScrollBarTests.cs
Labels: AutoMerge, test-enhancement

#1943 Cleanup PageSetupDialog and add tests
  src/Common/src/Interop/Comdlg32/Interop.PSD.cs
  src/Common/src/Interop/Comdlg32/Interop.PageSetupDlgW.cs
  src/Common/src/Interop/Interop.Libraries.cs
  src/Common/src/Interop/User32/Interop.WNDPROC.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Printing/PageSetupDialog.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PageSetupDialogTests.cs
Labels: Cleanup, enhancement, test-enhancement

#1941 Cleanup IExtender/IGetOleObject
  src/Common/src/Interop/Ole32/Interop.IGetOleObject.cs
  src/Common/src/Interop/OleAut32/Interop.IExtender.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
Labels: Cleanup, enhancement

#1928 Cleanup Gdi32 Pen/Brush interop
  src/Common/src/Interop/Gdi32/Interop.BS.cs
  src/Common/src/Interop/Gdi32/Interop.CreateBrushIndirect.cs
  src/Common/src/Interop/Gdi32/Interop.CreatePatternBrush.cs
  src/Common/src/Interop/Gdi32/Interop.CreatePen.cs
  src/Common/src/Interop/Gdi32/Interop.CreateSolidBrush.cs
  src/Common/src/Interop/Gdi32/Interop.Ellipse.cs
  src/Common/src/Interop/Gdi32/Interop.ExtCreatePen.cs
  src/Common/src/Interop/Gdi32/Interop.LOGBRUSH.cs
  src/Common/src/Interop/Gdi32/Interop.PS.cs
  src/Common/src/Interop/User32/Interop.FillRect.cs
  src/Common/src/Interop/User32/Interop.GetSysColorBrush.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/SafeNativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerUtils.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/ButtonStandardAdapter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.cs
  src/System.Windows.Forms/src/misc/GDI/NativeMethods.cs
  src/System.Windows.Forms/src/misc/GDI/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/misc/GDI/WindowsBrush.cs
  src/System.Windows.Forms/src/misc/GDI/WindowsGraphics2.cs
  src/System.Windows.Forms/src/misc/GDI/WindowsPen.cs
  src/System.Windows.Forms/src/misc/GDI/WindowsPenStyle.cs
  src/System.Windows.Forms/src/misc/GDI/WindowsSolidBrush.cs
Labels: Cleanup, enhancement

#1946 Add badges for 3.1 release build pipeline and also the code cov of 3.1
  README.md
Labels: AutoMerge

#1939 Cleanup IFont related interop
  src/Common/src/Interop/Ole32/Interop.IFont.cs
  src/Common/src/Interop/Ole32/Interop.IFontDisp.cs
  src/Common/src/Interop/Ole32/Interop.IPicture.cs
  src/Common/src/Interop/OleAut32/Interop.FONTDESC.cs
  src/Common/src/Interop/OleAut32/Interop.OleCreateFontIndirect.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/SafeNativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2FontConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXFontMarshaler.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserHelper.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHostTests.cs
Labels: test-enhancement

#1913 Extract LVM_ message
  src/Common/src/Interop/Interop.ListViewMessages.cs
  src/Common/src/NativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerUtils.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ColumnHeader.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewInsertionMark.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs
Labels: Cleanup, enhancement

#1958 Cleanup DWebBrowserEvents2 and add some WebBrowser tests
  src/Common/src/Interop/SHDocVw/Interop.CSC.cs
  src/Common/src/Interop/SHDocVw/Interop.DWebBrowserEvents2.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowser.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PictureBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/WebBrowserTests.cs
Labels: enhancement, test-enhancement, waiting-author-feedback

#1967 Add more Control/ListView related tests
  src/Common/tests/CommonTestHelper.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridTableStyleTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PanelTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs
Labels: test-enhancement

#1960 Cleanup SystemParametersInfo interop
  src/Common/src/Interop/Gdi32/Interop.CreateFontIndirectW.cs
  src/Common/src/Interop/Gdi32/Interop.GetObjectW.cs
  src/Common/src/Interop/Interop.WindowMessages.cs
  src/Common/src/Interop/User32/Interop.HIGHCONTRASTW.cs
  src/Common/src/Interop/User32/Interop.LOGFONTW.cs
  src/Common/src/Interop/User32/Interop.NONCLIENTMETRICSW.cs
  src/Common/src/Interop/User32/Interop.SPI.cs
  src/Common/src/Interop/User32/Interop.SystemParametersInfoW.cs
  src/Common/src/Interop/User32/Interop.WindowMessage.cs
  src/Common/src/Interop/UxTheme/Interop.GetThemeFont.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/SafeNativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXFontMarshaler.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.MetafileDCWrapper.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Cursor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/FontDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs
  src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
  src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SystemInformation.cs
  src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs
  src/System.Windows.Forms/src/misc/GDI/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/misc/GDI/WindowsFont.cs
  src/System.Windows.Forms/tests/UnitTests/InteropTests/SysInfoTests.cs
  src/System.Windows.Forms/tests/UnitTests/InteropTests/TextTests.cs
Labels: Cleanup, enhancement
