Repository dotnet/winforms, pull requests merged in 2019-10, with the labels that each got.

#1980 Cleanup IErrorInfo and ISupportErrorInfo
  src/Common/src/Interop/OleAut32/Interop.GetErrorInfo.cs
  src/Common/src/Interop/OleAut32/Interop.IErrorInfo.cs
  src/Common/src/Interop/OleAut32/Interop.ISupportErrorInfo.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
Labels: Cleanup, enhancement

#1975 ImeMode.NoControl in Text and Combo boxes on CHS pinyin was switching to ENG
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.Ime.cs
Labels: waiting-approval

#1988 Cleanup Caret interop
  src/Common/src/Interop/User32/Interop.GetCaretBlinkTime.cs
  src/Common/src/Interop/User32/Interop.HideCaret.cs
  src/Common/src/Interop/User32/Interop.ShowCaret.cs
  src/Common/src/SafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SystemInformation.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.cs
Labels: Cleanup

#1979 Cleanup OleCreatePropertyFrameIndirect
  src/Common/src/Interop/OleAut32/Interop.OCPFIPARAMS.cs
  src/Common/src/Interop/OleAut32/Interop.OleCreatePropertyFrameIndirect.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
Labels: Cleanup

#1937 Cleanup IOleCommandTarget
  src/Common/src/Interop/Ole32/Interop.IOleCommandTarget.cs
  src/Common/src/Interop/Ole32/Interop.OLECMD.cs
  src/Common/src/Interop/Ole32/Interop.OLECMDEXECOPT.cs
  src/Common/src/Interop/Ole32/Interop.OLECMDF.cs
  src/Common/src/Interop/Ole32/Interop.OLECMDID.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowser.cs
Labels: Cleanup, enhancement

#1920 Cleanup SCROLLINFO related interop
  src/Common/src/Interop/User32/Interop.ESB.cs
  src/Common/src/Interop/User32/Interop.EnableScrollBar.cs
  src/Common/src/Interop/User32/Interop.GetScrollInfo.cs
  src/Common/src/Interop/User32/Interop.SB.cs
  src/Common/src/Interop/User32/Interop.SBH.cs
  src/Common/src/Interop/User32/Interop.SBV.cs
  src/Common/src/Interop/User32/Interop.SCROLLINFO.cs
  src/Common/src/Interop/User32/Interop.SIF.cs
  src/Common/src/Interop/User32/Interop.ScrollSW.cs
  src/Common/src/Interop/User32/Interop.ScrollWindowEx.cs
  src/Common/src/Interop/User32/Interop.SetScrollInfo.cs
  src/Common/src/Interop/User32/Interop.SetScrollPos.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/SafeNativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerFrame.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HScrollProperties.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollEventType.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollProperties.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollableControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/VScrollProperties.cs
Labels: Cleanup, enhancement

#2013 Structify DISPPARAMS
  src/Common/src/Interop/Ole32/Interop.DISPPARAMS.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2AboutBoxPropertyDescriptor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/ComNativeDescriptor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlDocument.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlElement.cs
Labels: Cleanup, enhancement

#1984 Remove unused interop interfaces
  src/Common/src/UnsafeNativeMethods.cs
Labels: Cleanup

#2000 Scope `EnsureSerializableAttribute` tests to user-generated types
  src/Common/tests/InternalUtilitiesForTests/src/BinarySerialization.cs
  src/System.Windows.Forms.Design.Editors/tests/UnitTests/SerializableAttributeTest.cs
  src/System.Windows.Forms.Design/tests/UnitTests/SerializableAttributeTests.cs
  src/System.Windows.Forms/tests/UnitTests/SerializableAttributeTests.cs
Labels: test-bug, test-enhancement

#2025 Cleanup GetDoubleClickTime
  src/Common/src/Interop/User32/Interop.GetDoubleClickTime.cs
  src/Common/src/SafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SystemInformation.cs
Labels: Cleanup, enhancement

#2045 Removed dead code from ImageList
  src/System.Windows.Forms/src/Resources/SR.resx
  src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs
Labels: Cleanup

#2043 Cleanup WaitMessage/PostQuitMessage
  src/Common/src/Interop/User32/Interop.PostQuitMessage.cs
  src/Common/src/Interop/User32/Interop.WaitMessage.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Application.ComponentManager.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs
Labels: Cleanup, enhancement

#2027 Cleanup ComputerName and UserName interop
  src/Common/src/ExternDll.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design.Editors/src/Misc/ExternDll.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SystemInformation.cs
Labels: AutoMerge, Cleanup, enhancement

#2022 Cleanup ICategorizeProperties
  src/Common/src/Interop/VSSDK/Interop.ICategorizeProperties.cs
  src/Common/src/Interop/VSSDK/Interop.PROPCAT.cs
  src/Common/src/NativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2ICategorizePropertiesHandler.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2Properties.cs
Labels: Cleanup, enhancement

#2031 Cleanup IAutoComplete2
  src/Common/src/Interop/Shell32/Interop.AUTOCOMPLETEOPTIONS.cs
  src/Common/src/Interop/Shell32/Interop.IAutoComplete2.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AutoCompleteMode.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/StringSource.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextBox.cs
Labels: AutoMerge, Cleanup, enhancement

#2034 Remove dead code from WindowsGraphics
  src/System.Windows.Forms/src/misc/GDI/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/misc/GDI/WindowsGraphics.cs
  src/System.Windows.Forms/src/misc/GDI/WindowsGraphics2.cs
Labels: AutoMerge

#2026 Cleanup DEVMODE interop
  src/Common/src/Interop/User32/Interop.DEVMODEW.cs
  src/Common/src/Interop/User32/Interop.DM.cs
  src/Common/src/Interop/User32/Interop.ENUM.cs
  src/Common/src/Interop/User32/Interop.EnumDisplaySettingsW.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/SafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SystemInformation.cs
Labels: AutoMerge, Cleanup, enhancement

#2024 Cleanup OpenInputDesktop/CloseDesktop
  src/Common/src/Interop/Interop.ERROR.cs
  src/Common/src/Interop/Kernel32/Interop.LoadLibrary.cs
  src/Common/src/Interop/User32/Interop.CloseDesktop.cs
  src/Common/src/Interop/User32/Interop.DESKTOP.cs
  src/Common/src/Interop/User32/Interop.DF.cs
  src/Common/src/Interop/User32/Interop.OpenInputDesktop.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/SafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SystemInformation.cs
Labels: AutoMerge, Cleanup, enhancement

#2035 Cleanup Hook functions
  src/Common/src/Interop/User32/Interop.CallNextHookEx.cs
  src/Common/src/Interop/User32/Interop.HC.cs
  src/Common/src/Interop/User32/Interop.HOOKPROC.cs
  src/Common/src/Interop/User32/Interop.SetWindowsHookExW.cs
  src/Common/src/Interop/User32/Interop.UnhookWindowsHookEx.cs
  src/Common/src/Interop/User32/Interop.WH.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SendKeys.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.cs
Labels: AutoMerge, Cleanup, enhancement

#2046 Cleanup ImageList interop and add tests
  src/Common/src/Interop/ComCtl32/Interop.CLR.cs
  src/Common/src/Interop/ComCtl32/Interop.ILC.cs
  src/Common/src/Interop/ComCtl32/Interop.ILD.cs
  src/Common/src/Interop/ComCtl32/Interop.ILP.cs
  src/Common/src/Interop/ComCtl32/Interop.IMAGEINFO.cs
  src/Common/src/Interop/ComCtl32/Interop.ImageList.Add.cs
  src/Common/src/Interop/ComCtl32/Interop.ImageList.Create.cs
  src/Common/src/Interop/ComCtl32/Interop.ImageList.Destroy.cs
  src/Common/src/Interop/ComCtl32/Interop.ImageList.Draw.cs
  src/Common/src/Interop/ComCtl32/Interop.ImageList.DrawEx.cs
  src/Common/src/Interop/ComCtl32/Interop.ImageList.Duplicate.cs
  src/Common/src/Interop/ComCtl32/Interop.ImageList.GetIconSize.cs
  src/Common/src/Interop/ComCtl32/Interop.ImageList.GetImageCount.cs
  src/Common/src/Interop/ComCtl32/Interop.ImageList.GetImageInfo.cs
  src/Common/src/Interop/ComCtl32/Interop.ImageList.Read.cs
  src/Common/src/Interop/ComCtl32/Interop.ImageList.Remove.cs
  src/Common/src/Interop/ComCtl32/Interop.ImageList.Replace.cs
  src/Common/src/Interop/ComCtl32/Interop.ImageList.ReplaceIcon.cs
  src/Common/src/Interop/ComCtl32/Interop.ImageList.SetBkColor.cs
  src/Common/src/Interop/ComCtl32/Interop.ImageList.Write.cs
  src/Common/src/Interop/ComCtl32/Interop.ImageList.WriteEx.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/SafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ImageListStreamer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
  src/System.Windows.Forms/tests/UnitTests/SerializableTypesTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageListTests.cs
Labels: Cleanup, enhancement, test-enhancement

#2041 Cleanup PowerStatus interop
  src/Common/src/ExternDll.cs
  src/Common/src/Interop/Interop.BOOLEAN.cs
  src/Common/src/Interop/Interop.Libraries.cs
  src/Common/src/Interop/Kernel32/Interop.GetSystemPowerStatus.cs
  src/Common/src/Interop/Kernel32/Interop.SYSTEM_POWER_STATUS.cs
  src/Common/src/Interop/Powrprof/Interop.SetSuspendState.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design.Editors/src/Misc/ExternDll.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PowerStatus.cs
Labels: Cleanup, enhancement, waiting-author-feedback

#1978 Cleanup Menu related interop
  src/Common/src/Interop/User32/Interop.CreateMenu.cs
  src/Common/src/Interop/User32/Interop.CreatePopupMenu.cs
  src/Common/src/Interop/User32/Interop.DestroyMenu.cs
  src/Common/src/Interop/User32/Interop.EnableMenuItem.cs
  src/Common/src/Interop/User32/Interop.GetMenu.cs
  src/Common/src/Interop/User32/Interop.GetMenuItemCount.cs
  src/Common/src/Interop/User32/Interop.GetMenuItemID.cs
  src/Common/src/Interop/User32/Interop.GetSubMenu.cs
  src/Common/src/Interop/User32/Interop.GetSystemMenu.cs
  src/Common/src/Interop/User32/Interop.MF.cs
  src/Common/src/Interop/User32/Interop.RemoveMenuItem.cs
  src/Common/src/Interop/User32/Interop.SC.cs
  src/Common/src/Interop/User32/Interop.SetMenu.cs
  src/Common/src/Interop/User32/Interop.SetMenuDefaultItem.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MDIControlStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MainMenu.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Menu.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MenuItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MenuStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownMenu.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.cs
  src/System.Windows.Forms/tests/UnitTests/MainMenuTestsTests.cs
  src/System.Windows.Forms/tests/UnitTests/MenuTests.cs
Labels: AutoMerge

#2063 Cleanup NMLISTVIEW
  src/Common/src/Interop/ComCtl32/Interop.NMLISTVIEW.cs
  src/Common/src/NativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
Labels: AutoMerge

#2070 Structify NMTVDISPINFOW
  src/Common/src/Interop/ComCtl32/Interop.NMTVDISPINFOW.cs
  src/Common/src/NativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
Labels: enhancement

#1985 Fix conditional order of precedence
  eng/Shipping.ruleset
  src/Common/src/OsVersion.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DragAssistanceManager.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/SnapLine.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripKeyboardHandlingService.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGrid.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridTableStyle.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnHeaderCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxEditingControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Layout/DockAndAnchorLayout.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MdiWindowListStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MenuItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/NumericUpDown.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollableControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SplitContainer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSplitStackLayout.cs
  src/System.Windows.Forms/tests/UnitTests/OsVersionTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComponentModel/Com2Interop/Com2PropertyDescriptorTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollableControlTests.cs
Labels: documentation: breaking

#2061 Cleanup OleCreatePropertyFrame
  src/Common/src/Interop/OleAut32/Interop.OleCreatePropertyFrame.cs
  src/Common/src/SafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2ComponentEditor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyPageUITypeConverter.cs
Labels: enhancement

#2066 Cleanup ChooseColor
  src/Common/src/Interop/Comdlg32/Interop.CC.cs
  src/Common/src/Interop/Comdlg32/Interop.ChooseColorW.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/SafeNativeMethods.cs
  src/System.Windows.Forms.Design.Editors/src/Misc/NativeMethods.cs
  src/System.Windows.Forms.Design.Editors/src/System.Windows.Forms.Design.Editors.csproj
  src/System.Windows.Forms.Design.Editors/src/System/Drawing/Design/ColorEditor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ColorDialog.cs
Labels: AutoMerge, waiting-author-feedback

#2065 Cleanup SendKeys interop
  src/Common/src/Interop/User32/Interop.BlockInput.cs
  src/Common/src/Interop/User32/Interop.EVENTMSG.cs
  src/Common/src/Interop/User32/Interop.GetAsyncKeyState.cs
  src/Common/src/Interop/User32/Interop.GetKeyboardState.cs
  src/Common/src/Interop/User32/Interop.OemKeyScan.cs
  src/Common/src/Interop/User32/Interop.SetKeyboardState.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/SafeNativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SendKeys.cs
Labels: Cleanup, enhancement

#2079 Structify REQRESIZE
  src/Common/src/Interop/Richedit/Interop.REQRESIZE.cs
  src/Common/src/NativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
Labels: AutoMerge

#2081 Cleanup NMTBHOTITEM
  src/Common/src/Interop/ComCtl32/Interop.HICF.cs
  src/Common/src/Interop/ComCtl32/Interop.NMTBHOTITEM.cs
  src/Common/src/NativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolBar.cs
Labels: AutoMerge, Cleanup, enhancement

#2064 Rename and structify OLEINPLACEFRAMEINFO
  src/Common/src/Interop/Ole32/Interop.OLEINPLACEFRAMEINFO.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserSiteBase.cs
Labels: AutoMerge, Cleanup

#2028 Remove new HandleRef(null, ...) usage in Control.PrintToMetaFile
  src/Common/src/SafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.MetafileDCWrapper.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Label.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Panel.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WinFormsUtils.cs
Labels: AutoMerge, Cleanup

#2083 Remove duplicate GetCursor interop
  src/Common/src/NativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/CommandSet.cs
Labels: AutoMerge, Cleanup

#1994 Adding test for null for PropertyGridView's SelectedGridEntry
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
Labels: Tactics Approved, ask-mode

#2086 LOC CHECKIN | dotnet/winforms release/3.1 | 20191015
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
Labels: AutoMerge

#2099 Cleanup tagVT enum
  src/Common/src/NativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2TypeInfoProcessor.cs
Labels: code cleanup, enhancement

#1977 [Accessibility][HC]: Fixing DataGridView background color in HC themes
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs
Labels: ask-mode

#2109 Cleanup IOleContainer
  src/Common/src/Interop/Ole32/Interop.IOleContainer.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.AxSourcingSite.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserContainer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserSiteBase.cs
Labels: enhancement

#2108 Cleanup OLEMENUGROUPWIDTHS
  src/Common/src/Interop/Ole32/Interop.OLEMENUGROUPWIDTHS.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserContainer.cs
Labels: enhancement

#2100 Cleanup Gdi32 drawing apis
  src/Common/src/Interop/Gdi32/Interop.ETO.cs
  src/Common/src/Interop/Gdi32/Interop.ExtTextOutW.cs
  src/Common/src/Interop/Gdi32/Interop.LineTo.cs
  src/Common/src/Interop/Gdi32/Interop.MoveToEx.cs
  src/Common/src/Interop/Gdi32/Interop.Rectangle.cs
  src/Common/src/Interop/Gdi32/Interop.RoundRect.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/SafeNativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerUtils.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.cs
  src/System.Windows.Forms/src/misc/GDI/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/misc/GDI/WindowsGraphics2.cs
Labels: code cleanup, enhancement

#2089 Port IconEditor; add test
  src/System.Windows.Forms.Design.Editors/src/Resources/SR.resx
  src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms.Design.Editors/src/System/Drawing/Design/IconEditor.cs
  src/System.Windows.Forms.Design.Editors/tests/UnitTests/EnsureEditorsTests.cs
  src/System.Windows.Forms/src/System/Drawing/Design/UITypeEditor.cs
Labels: waiting-author-feedback

#2075 Cleanup NMTOOLBARW/TBBUTTONINFOW/TBBUTTON
  src/Common/src/Interop/ComCtl32/Interop.NMTOOLBARW.cs
  src/Common/src/Interop/ComCtl32/Interop.TB.cs
  src/Common/src/Interop/ComCtl32/Interop.TBBUTTON.cs
  src/Common/src/Interop/ComCtl32/Interop.TBBUTTONINFOW.cs
  src/Common/src/Interop/ComCtl32/Interop.TBIF.cs
  src/Common/src/Interop/ComCtl32/Interop.TBSTATE.cs
  src/Common/src/Interop/ComCtl32/Interop.TBSTYLE.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolBarButton.cs
Labels: AutoMerge, enhancement

#2080 Structify SELCHANGE
  src/Common/src/Interop/Richedit/Interop.SEL.cs
  src/Common/src/Interop/Richedit/Interop.SELCHANGE.cs
  src/Common/src/NativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/RichTextBoxConstants.cs
Labels: AutoMerge

#2082 Structify NMVIEWCHANGE
  src/Common/src/Interop/ComCtl32/Interop.MCMV.cs
  src/Common/src/Interop/ComCtl32/Interop.NMVIEWCHANGE.cs
  src/Common/src/NativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
Labels: AutoMerge, enhancement

#2106 Remove #if false code from winforms
  src/System.Windows.Forms/src/System/Windows/Forms/DataGrid.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridColumnCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridTableStyle.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MergePropertyDescriptor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
Labels: code cleanup

#2129 Cleanup IOleInPlaceActiveObject and IOleInPlaceUIWindow interop
  src/Common/src/Interop/Ole32/Interop.IOleInPlaceActiveObject.cs
  src/Common/src/Interop/Ole32/Interop.IOleInPlaceUIWindow.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.Ime.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowser.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserContainer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserSiteBase.cs
Labels: AutoMerge

#2130 Cleanup Gdi32 Ext/Org interop
  src/Common/src/Interop/Gdi32/Interop.GetViewportExtEx.cs
  src/Common/src/Interop/Gdi32/Interop.GetViewportOrgEx.cs
  src/Common/src/Interop/Gdi32/Interop.SetViewportExtEx.cs
  src/Common/src/Interop/Gdi32/Interop.SetViewportOrgEx.cs
  src/Common/src/Interop/Gdi32/Interop.SetWindowExtEx.cs
  src/Common/src/Interop/Gdi32/Interop.SetWindowOrgEx.cs
  src/Common/src/SafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WinFormsUtils.cs
  src/System.Windows.Forms/src/misc/GDI/DeviceContext2.cs
  src/System.Windows.Forms/src/misc/GDI/UnsafeNativeMethods.cs
Labels: AutoMerge

#2062 Cleanup SYSTEMTIME and dependencies
  src/Common/src/Interop/ComCtl32/Interop.GDT.cs
  src/Common/src/Interop/ComCtl32/Interop.NMDATETIMECHANGE.cs
  src/Common/src/Interop/ComCtl32/Interop.NMDAYSTATE.cs
  src/Common/src/Interop/ComCtl32/Interop.NMSELCHANGE.cs
  src/Common/src/Interop/Kernel32/Interop.SYSTEMTIME.cs
  src/Common/src/Interop/User32/Interop.MCM.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
Labels: AutoMerge, code cleanup, enhancement

#2097 Add TabControl tests
  src/Common/tests/CommonTestHelper.cs
  src/System.Windows.Forms/tests/UnitTests/MonthCalendarTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridTableStyleTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItemTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewSubItemTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs
Labels: test-enhancement

#2093 Make DVASPECT and OLEMISC into enums
  src/Common/src/Interop/Interop.HRESULT.cs
  src/Common/src/Interop/Ole32/Interop.DVASPECT.cs
  src/Common/src/Interop/Ole32/Interop.OLEMISC.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserSiteBase.cs
Labels: enhancement

#2143 Clean up Capture method
  src/Common/src/Interop/User32/Interop.SetCapture.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGrid.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
  src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SplitContainer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Splitter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDown.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs
Labels: code cleanup, enhancement

#2137 Consolidate MapMode Gdi32 interop
  src/Common/src/Interop/Gdi32/Interop.GetMapMode.cs
  src/Common/src/Interop/Gdi32/Interop.MM.cs
  src/Common/src/Interop/Gdi32/Interop.SetMapMode.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/SafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.cs
  src/System.Windows.Forms/src/misc/GDI/DeviceContext2.cs
  src/System.Windows.Forms/src/misc/GDI/DeviceContextMapMode.cs
  src/System.Windows.Forms/src/misc/GDI/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/misc/GDI/WindowsGraphics2.cs
Labels: AutoMerge

#2135 Cleanup IOleInPlaceFrame
  src/Common/src/Interop/Interop.HRESULT.cs
  src/Common/src/Interop/Ole32/Interop.IOleInPlaceFrame.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowser.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserContainer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserSiteBase.cs
Labels: AutoMerge, code cleanup, enhancement

#2096 Implementing UIA supporting for Form control
  src/System.Windows.Forms/src/System/Windows/Forms/Form.AccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
Labels: servicing-approved

#2098 Add VisualStyleRenderer tests
  src/Common/tests/CommonTestHelper.cs
  src/System.Windows.Forms.Design.Editors/tests/UnitTests/System.Windows.Forms.Design.Editors.Tests.csproj
  src/System.Windows.Forms.Design/tests/UnitTests/System.Windows.Forms.Design.Tests.csproj
  src/System.Windows.Forms/tests/UnitTests/System.Windows.Forms.Tests.csproj
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ApplicationTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/VisualStyles/VisualStyleRendererTests.cs
  src/System.Windows.Forms/tests/UnitTests/VisualStyleRendererTests.cs
Labels: test-enhancement

#2139 Add Control dialog/input/key/menu tests
  src/System.Windows.Forms/tests/UnitTests/ContextMenuTests.cs
  src/System.Windows.Forms/tests/UnitTests/MainMenuTests.cs
  src/System.Windows.Forms/tests/UnitTests/MenuTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs
Labels: test-enhancement

#1961 Extract misc Ole32 data types
  src/Common/src/Interop/Ole32/Interop.ELEMDESC.cs
  src/Common/src/Interop/Ole32/Interop.FUNCDESC.cs
  src/Common/src/Interop/Ole32/Interop.IDLDESC.cs
  src/Common/src/Interop/Ole32/Interop.PARAMDESC.cs
  src/Common/src/Interop/Ole32/Interop.TYPEATTR.cs
  src/Common/src/Interop/Ole32/Interop.TYPEDESC.cs
  src/Common/src/Interop/Ole32/Interop.VARDESC.cs
  src/Common/src/NativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2TypeInfoProcessor.cs
Labels: code cleanup, enhancement

#1998 Accessibility: NRE announcing changed item in `PropertyGrid`
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs
Labels: servicing-approved

#2183 Fixing editors unit tests and the branch building
  src/System.Design/src/System.Design.Forwards.cs
  src/System.Windows.Forms.Design.Editors/tests/UnitTests/EnsureEditorsTests.cs
Labels: waiting-review

#2180 Cleanup SetParent interop
  src/Common/src/Interop/User32/Interop.SetParent.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerFrame.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Application.ParkingWindow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.cs
Labels: :octocat: automerge

#2105 Rename TabControl fields
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.ControlCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.State.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
Labels: enhancement

#2203 Remove ClassStyle enum
  src/Common/src/NativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDown.cs
Labels: :octocat: automerge

#2158 Add FW, OUT_PRECIS and QUALITY enums and remove NativeMethods.cs and WindowsFontQuality.cs
  src/Common/src/Interop/Gdi32/Interop.FW.cs
  src/Common/src/Interop/Gdi32/Interop.OUT_PRECIS.cs
  src/Common/src/Interop/Gdi32/Interop.QUALITY.cs
  src/Common/src/Interop/User32/Interop.LOGFONTW.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs
  src/System.Windows.Forms/src/System/Windows/Forms/GDI/TextRenderer.cs
  src/System.Windows.Forms/src/misc/GDI/NativeMethods.cs
  src/System.Windows.Forms/src/misc/GDI/WindowsFont.cs
  src/System.Windows.Forms/src/misc/GDI/WindowsFontQuality.cs
  src/System.Windows.Forms/src/misc/GDI/WindowsGraphicsCacheManager.cs
Labels: enhancement

#2162 Add ARW enum and remove ARW constants
  src/Common/src/Interop/User32/Interop.ARW.cs
  src/Common/src/NativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ArrangeDirection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ArrangeStartingPosition.cs
Labels: enhancement

#2154 Partially revert "Porting DataMemberFieldConverter" f477b2a
  src/System.Design/src/System.Design.Forwards.cs
  src/System.Windows.Forms.Design/src/Properties/InternalsVisibleTo.cs
  src/System.Windows.Forms/src/AssemblyRef.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumn.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxColumn.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListControl.cs
Labels: :octocat: automerge

#2179 Extract AxHost nested classes
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.ActiveXInvokeKind.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxComponentEditor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxContainer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxPerPropertyBrowsingEnum.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxPropertyDescriptor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.ClsidAttribute.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.ConnectionPointCookie.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.EnumUnknown.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.InvalidActiveXStateException.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.OleInterfaces.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.PropertyBagStream.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.State.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.StateConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.TypeLibraryTimeStampAttribute.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.VBFormat.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
Labels: enhancement

#2033 Cleanup some UxTheme Draw* interop and add tests
  src/Common/src/Interop/User32/Interop.BDR.cs
  src/Common/src/Interop/User32/Interop.BF.cs
  src/Common/src/Interop/User32/Interop.EDGE.cs
  src/Common/src/Interop/UxTheme/Interop.CloseThemeData.cs
  src/Common/src/Interop/UxTheme/Interop.DrawThemeBackground.cs
  src/Common/src/Interop/UxTheme/Interop.DrawThemeEdge.cs
  src/Common/src/Interop/UxTheme/Interop.DrawThemeParentBackground.cs
  src/Common/src/Interop/UxTheme/Interop.DrawThemeText.cs
  src/Common/src/Interop/UxTheme/Interop.GetThemeAppProperties.cs
  src/Common/src/Interop/UxTheme/Interop.IsAppThemed.cs
  src/Common/src/Interop/UxTheme/Interop.IsThemePartDefined.cs
  src/Common/src/Interop/UxTheme/Interop.OpenThemeData.cs
  src/Common/src/Interop/UxTheme/Interop.STAP.cs
  src/Common/src/Interop/UxTheme/Interop.SetThemeAppProperties.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/SafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Border3DSide.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Border3DStyle.cs
  src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/EdgeEffects.cs
  src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/EdgeStyle.cs
  src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/Edges.cs
  src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleInformation.cs
  src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleState.cs
Labels: code cleanup, enhancement

#2229 Add more Control tests
  src/System.Windows.Forms/tests/UnitTests/MonthCalendarTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHostTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ContainerControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/ComponentEditorPageTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FlowLayoutPanelTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/HScrollBarTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PanelTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PictureBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollBarTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollableControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPageTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripPanelTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/VScrollBarTests.cs
Labels: test-enhancement

#2141 Add more ProgressBar and related tests and fix a parameter name
  src/System.Windows.Forms/src/System/Windows/Forms/ProgressBar.cs
  src/System.Windows.Forms/tests/UnitTests/ProgressBarTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ProgressBarTests.cs
Labels: test-bug

#2212 Remove WS constants
  src/Common/src/NativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionUI.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/SelectionUIService.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripAdornerWindowService.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorPage.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Label.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MDIClient.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Panel.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PictureBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ProgressBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollableControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Splitter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDown.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.cs
  src/System.Windows.Forms/src/System/Windows/Forms/UserControl.cs
Labels: :octocat: automerge

#2152 Cleanup IOleClientSite
  src/Common/src/Interop/Ole32/Interop.IOleClientSite.cs
  src/Common/src/Interop/Ole32/Interop.OLEGETMONIKER.cs
  src/Common/src/Interop/Ole32/Interop.OLEWHICHMK.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxContainer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.OleInterfaces.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.AxSourcingSite.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserContainer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserSiteBase.cs
Labels: :octocat: automerge

#2217 Use separate file for MARGINS in UxTheme
  src/Common/src/Interop/UxTheme/Interop.MARGINS.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/SafeNativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs
Labels: enhancement

#2131 Remove duplicate DpiHelper implementation
  src/Common/src/DpiHelper.cs
  src/Common/src/ExternDll.cs
  src/Common/src/Interop/Interop.Libraries.cs
  src/Common/src/Interop/SHCore/Interop.GetProcessDpiAwareness.cs
  src/Common/src/Interop/SHCore/Interop.PROCESS_DPI_AWARENESS.cs
  src/Common/src/Interop/SHCore/Interop.SetProcessDpiAwareness.cs
  src/Common/src/Interop/User32/Interop.DPI_AWARENESS_CONTEXT.cs
  src/Common/src/Interop/User32/Interop.IsProcessDPIAware.cs
  src/Common/src/Interop/User32/Interop.IsValidDpiAwarenessContext.cs
  src/Common/src/Interop/User32/Interop.SetProcessDPIAware.cs
  src/Common/src/Interop/User32/Interop.SetProcessDpiAwarenessContext.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/SafeNativeMethods.cs
  src/System.Windows.Forms.Design.Editors/src/Misc/CommonUnsafeNativeMethods.cs
  src/System.Windows.Forms.Design.Editors/src/Misc/DpiHelper.cs
  src/System.Windows.Forms.Design.Editors/src/Misc/ExternDll.cs
  src/System.Windows.Forms.Design.Editors/src/System.Windows.Forms.Design.Editors.csproj
  src/System.Windows.Forms.Design.Editors/src/System/ComponentModel/Design/CollectionEditor.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms/tests/UnitTests/CommonUnsafeNativeMethodsTests.cs
Labels: code cleanup

#2238 Cleanup ADVF constants
  src/Common/src/Interop/Ole32/Interop.ADVF.cs
  src/Common/src/NativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
Labels: enhancement

#2074 [Accessibility][ScreenReader]: Fixing tooltip text announcing by NVDA/Narrator
  src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
Labels: servicing-approved

#1992 [Accessibility] Adding announcement for PropertyGrid ComboBox Expand and Collapse actions
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
Labels: servicing-approved

#2241 Remove References from Directory.Build.props
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/Directory.Build.props
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiButtonTests/MauiButtonTests.csproj
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiComboBoxTests/MauiComboBoxTests.csproj
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/References.targets
Labels: test-enhancement

#2239 Cleanup AdjustWindowRectEx and friends
  src/Common/src/Interop/Gdi32/Interop.AdjustWindowRectEx.cs
  src/Common/src/Interop/Gdi32/Interop.AdjustWindowRectExForDpi.cs
  src/Common/src/Interop/Gdi32/Interop.LPtoDP.cs
  src/Common/src/SafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
Labels: enhancement

#2240 Cleanup GetClientRect interop
  src/Common/src/Interop/User32/Interop.GetClientRect.cs
  src/Common/src/SafeNativeMethods.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
  src/System.Windows.Forms/src/System/Windows/Forms/GroupBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/StatusStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripTextBox.cs
Labels: enhancement

#2248 Fixing UI and accessibility regression in DataGridView editing cell
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs
Labels: servicing-approved

#2247 DataGridViewEditingControl: Adding null reference check for parent DataGridView control
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxEditingControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxEditingControl.cs
Labels: servicing-approved
