Repository dotnet/winforms, pull requests merged in 2020-10, with the labels that each got.

#3862 Reinstate `RichTextBox_Text_GetWithHandle_ReturnsExpected`
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
Labels: test-enhancement

#4039 Adding Toggle pattern support for ListView items with checkboxes
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObjectTests.cs
Labels: a11yMAS, servicing-approved

#4064 Moving Combobox subclasses to their own files
  src/System.Windows.Forms/src/System.Windows.Forms.csproj
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ACNativeWindow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.AutoCompleteDropDownFinder.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ChildAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildDropDownButtonUiaProvider.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildEditUiaProvider.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildListUiaProvider.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildNativeWindow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildTextUiaProvider.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObjectCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.FlatComboAdapter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ItemComparer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ObjectCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
Labels: code cleanup

#3969 Fixing the incorrect ScreenReader blue rectangle for a new character when typing (Text pattern area)
  src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
Labels: waiting-review

#3732 Add AccessibleObject native tests
  src/System.Windows.Forms.Primitives/src/Interop/UiaCore/Interop.IAccessibleEx.cs
  src/System.Windows.Forms.Primitives/src/Properties/AssemblyInfo.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.EnumVariantObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/InternalAccessibleObject.cs
  src/System.Windows.Forms/tests/InteropTests/AccessibleObjectTests.cs
  src/System.Windows.Forms/tests/InteropTests/NativeTests/AccessibleObjectTests.cpp
  src/System.Windows.Forms/tests/InteropTests/NativeTests/CMakeLists.txt
  src/System.Windows.Forms/tests/InteropTests/NativeTests/testhelpers.h
  src/System.Windows.Forms/tests/InteropTests/System.Windows.Forms.Interop.Tests.csproj
Labels: area: interop, tenet-accessibility, test-enhancement

#4062 Update docs and guides
  .github/CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
  Winforms.sln
  docs/building.md
  docs/contributing.md
  docs/debugging.md
  docs/developer-guide.md
  docs/getting-started.md
  docs/issue-guide.md
  docs/porting-guidelines.md
  docs/roadmap.md
  docs/testing.md
  roadmap.md
Labels: :books: documentation

#4021 Style cleanup for button rendering
  src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/ButtonBaseAdapter.ColorData.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/ButtonBaseAdapter.ColorOptions.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/ButtonBaseAdapter.LayoutData.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/ButtonBaseAdapter.LayoutOptions.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/ButtonBaseAdapter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/ButtonFlatAdapter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/ButtonPopupAdapter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/ButtonStandardAdapter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/CheckBoxBaseAdapter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/CheckBoxFlatAdapter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/CheckBoxPopupAdapter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/CheckBoxStandardAdapter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/CheckableControlBaseAdapter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/RadioButtonBaseAdapter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/RadioButtonFlatAdapter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/RadioButtonPopupAdapter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/RadioButtonStandardAdapter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/CheckBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewButtonCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCheckBoxCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/RadioButton.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownButton.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.ToolStripItemInternalLayout.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripLabel.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripStatusLabel.cs
Labels: code cleanup

#4077 Enabled NRT for Combobox and LinkLabel AccessibleObjects
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.LinkAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.LinkLabelAccessibleObject.cs
Labels: area: NRT

#4081 Enable NRT for DataGridView AccessibleObjects
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.AccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.DataGridViewEditingPanelAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.SelectedCellsAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.TopRowAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.AccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
Labels: area: NRT, code cleanup

#4088 Output the full EMF log whenever EMF validation fail.
  src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/Validators/EmfValidator.cs
Labels: test-bug, test-enhancement

#4111 Fix initial directory and custom places in file dialogs
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SHILCreateFromPath.cs
  src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/Shell32/ShellItemTests.cs
Labels: servicing-approved

#4113 Attempt to reduce concurrency while accessing `ImageList`
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageList.ImageCollectionTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageListTests.cs
Labels: test-bug

#4117 Fix MSAA accessibility
  src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.SystemIAccessibleWrapper.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildDropDownButtonUiaProvider.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjectTests.cs
Labels: servicing-consider

#4119 Fix MSAA accessibility (#4117)
  src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.SystemIAccessibleWrapper.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjectTests.cs
Labels: servicing-approved

#4132 Add some codes in Accessibility sample app to work around bug 1155463
  .gitignore
  src/System.Windows.Forms/tests/AccessibilityTests/DataControls.Designer.cs
  src/System.Windows.Forms/tests/AccessibilityTests/DataControls.cs
Labels: tenet-accessibility

#4127 DomainUpDown/NumericUpdown should be KeyboardFocusable
  src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainUpDownAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/NumericUpDown.NumericUpDownAccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/DomainUpDownAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/NumericUpDownAccessibleObjectTests.cs
Labels: :octocat: automerge, hacktoberfest-accepted

#4086 Add Rich Navigation to CI, a new Rich Nav pipeline
  NuGet.config
  azure-pipelines-richnav.yml
Labels: area: infra
