Repository dotnet/winforms, pull requests merged in 2020-02, with the labels that each got.

#2784 Cleanup ENDROPFILES
  src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.ENDROPFILES.cs
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.DragQueryFileW.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
Labels: enhancement

#2630 Cleanup MonthCalendar interop definitions
  src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.MCGRIDINFO.cs
  src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.MCHITTESTINFO.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarBodyAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.MonthCalendarAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
  src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/MonthCalendar.CalendarHeaderAccessibleObjectTests.cs
Labels: enhancement

#2808 Update to preview branding
  eng/Versions.props
Labels: :octocat: automerge

#2800 More SendMessage cleanup
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ColumnHeader.cs
  src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/StatusBarPanel.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
Labels: code cleanup, enhancement

#2798 Remove deprecated API
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/Resources/SR.resx
  src/System.Windows.Forms/src/Resources/System/Windows/Forms/StatusBar.ico
  src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms/src/System.Windows.Forms.csproj
  src/System.Windows.Forms/src/System/Windows/Forms/StatusBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/StatusBarDrawItemEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/StatusBarDrawItemEventHandler.cs
  src/System.Windows.Forms/src/System/Windows/Forms/StatusBarPanel.cs
  src/System.Windows.Forms/src/System/Windows/Forms/StatusBarPanelAutoSize.cs
  src/System.Windows.Forms/src/System/Windows/Forms/StatusBarPanelBorderStyle.cs
  src/System.Windows.Forms/src/System/Windows/Forms/StatusBarPanelClickEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/StatusBarPanelClickEventHandler.cs
  src/System.Windows.Forms/src/System/Windows/Forms/StatusBarPanelStyle.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/StatusBarDrawItemEventArgsTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/StatusBarPanelClickEventArgsTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/StatusBarPanelTests.cs
Labels: :book: documentation: breaking, api-suggestion

#2801 fix: `Application.ExecutablePath` returns dll instead of exe
  src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
Labels: servicing-consider

#2836 Add HT enum in Interop User32
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/CommandSet.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripAdornerWindowService.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.HT.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Label.cs
  src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridToolTip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SplitContainer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/StatusStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.cs
  src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/HitTestCode.cs
Labels: enhancement

#2829 Fix TextBoxBase NREs
  src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
  src/System.Windows.Forms/tests/UnitTests/TextBoxBaseTests.cs
Labels: enhancement

#2603 Cleanup ITypeInfo and IDispatch
  src/System.Windows.Forms.Primitives/src/Interop/Interop.BSTR.cs
  src/System.Windows.Forms.Primitives/src/Interop/Interop.HRESULT.cs
  src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.TYPEATTR.cs
  src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.TYPEDESC.cs
  src/System.Windows.Forms.Primitives/src/Interop/OleAut32/Interop.DISPATCH.cs
  src/System.Windows.Forms.Primitives/src/Interop/OleAut32/Interop.IDispatch.cs
  src/System.Windows.Forms.Primitives/src/Interop/OleAut32/Interop.ITypeInfo.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
  src/System.Windows.Forms.Primitives/tests/Interop/Oleaut32/IDispatchTests.cs
  src/System.Windows.Forms.Primitives/tests/Interop/Oleaut32/ITypeInfoTests.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2AboutBoxPropertyDescriptor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IPerPropertyBrowsingHandler.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IProvidePropertyBuilderHandler.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IVsPerPropertyBrowsingHandler.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2Properties.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2TypeInfoProcessor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/ComNativeDescriptor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlDocument.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlElement.cs
Labels: enhancement

#2810 Add CDCS, FDEOR, FDESRV, SIATTRIBFLAGS and SIGDN enums in Interop Shell32
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.CDCS.cs
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.FDEOR.cs
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.FDESVR.cs
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SIATTRIBFLAGS.cs
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SIGDN.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/FileDialog_Vista_Interop.cs
  src/System.Windows.Forms/src/System/Windows/Forms/FileDialog_Vista.cs
  src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
Labels: code cleanup, enhancement

#2821 Add missing ProgressBar AccessibleName
  src/System.Windows.Forms/src/Resources/SR.resx
  src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms/src/System/Windows/Forms/ProgressBar.cs
  src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/ProgressBarAccessibleObjectTests.cs
Labels: tenet-accessibility

#2831 Fix TabControl NREs
  src/System.Windows.Forms/src/Resources/SR.resx
  src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControlTests.cs
Labels: :book: documentation: breaking

#2819 Fix NullReferenceExceptions in Control.ControlCollection with a null owner
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutControlCollection.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.ControlCollection.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControl.ControlCollectionTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPageTests.TabPageControlCollection.cs
Labels: :book: documentation: breaking, enhancement

#2878 Update branding
  eng/Versions.props
Labels: :octocat: automerge

#2880 Run tests in x86 and x64
  Directory.Build.targets
Labels: test-enhancement

#2883 Add NIF and NIIF enums to Interop Shell32
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.NIF.cs
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.NIIF.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/NotifyIcon.cs
Labels: enhancement

#2820 Add TrackBar accessible object tests
  src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/TrackBarAccessibleObjectTests.cs
Labels: tenet-accessibility

#2909 fix: WebBrowser_AttachInterfaces_Invoke_Success fails if IE browser not installed
  src/System.Windows.Forms/tests/UnitTests/WebBrowserTests.cs
Labels: test-bug
