Repository dotnet/winforms, pull requests merged in 2020-09, with the labels that each got.

#3793 Print preview dialog incorrect focus after pressing 'Enter' on any button
  src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewDialog.PrintPreviewDialogToolStripButton.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewDialog.cs
Labels: servicing-approved

#3749 Correctly announce `DataGridViewCheckBoxColumn.CheckBox` state
  src/System.Windows.Forms/src/Resources/SR.resx
  src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCheckBoxCell.DataGridViewCheckBoxCellAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCheckBoxCell.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellTests.cs
Labels: :mailbox_with_mail: waiting-for-testing, servicing-approved

#3828 Use proper size rectangle with GDI (#3815)
  src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ButtonRenderingTests.cs
Labels: servicing-approved

#3831 Read accessible name of a data bound ListBox from the DisplayMember of the data source
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.AccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.ItemAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBox.ListBoxItemAccessibleObjectTests.cs
Labels: servicing-approved

#3843 loc checking 20200904
  src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
Labels: servicing-approved

#3849 Cannot find the RichEdit control of the "Text" property in UIA structure of a PropertyGrid control
  src/System.Windows.Forms/src/Resources/SR.resx
  src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.DropDownHolder.DropDownHolderAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.DropDownHolder.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewEdit.GridViewEditAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewEdit.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntryAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyGridView.DropDownHolder.DropDownHolderAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyGridView.DropDownHolderTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewEdit.GridViewEditAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewListBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyGridViewTests.cs
Labels: servicing-approved

#3857 Reset the DeviceDPI after setting DPI awareness (#3855)
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/DpiHelper.cs
Labels: servicing-approved

#3786 Adding dotnet3.1/dotnet-eng packages sources
  NuGet.config
Labels: area: infra

#3850 Fixing exception when switching between DataGridViewCell with active Narrator
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs
  src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/DataGridView.DataGridViewEditingPanelAccessibleObjectTests.cs
Labels: servicing-approved

#3871 Disable `RichTextBox_Text_GetWithHandle_ReturnsExpected`
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
Labels: servicing-approved

#3870 Change DataGridView.GridColor when set. (#3869)
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTests.cs
Labels: servicing-approved

#3873 Respect padding options when rendering text (#3872)
  src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/Validators/TextOutValidator.cs
  src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/Validators/Validate.cs
  src/System.Windows.Forms/src/System/Windows/Forms/GroupBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextExtensions.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextRenderer.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TextRendererTests.cs
  src/System.Windows.Forms/tests/UnitTests/Text/FontMetrics.cs
Labels: servicing-approved

#3888 Reset all DpiHelper statics when setting the DPI mode (#3881)
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/DpiHelper.cs
Labels: servicing-approved

#3911 More BehaviorService related code cleanup
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ComponentDesigner.ShadowPropertyCollection.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ComponentDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/Behavior.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorDragDropEventArgs.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.AdornerWindow.MouseHook.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.AdornerWindow.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.ChildSubClass.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.ControlDesignerAccessibleObject.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.DockingActionList.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs
Labels: code cleanup

#3913 Fix PaintEventArgs Graphics property
  src/System.Windows.Forms/src/System/Windows/Forms/Internal/DrawingEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PaintEventArgs.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PaintEventArgsTests.cs
Labels: :beetle: bug

#3916 Fix PaintEventArgs Graphics property (#3913)
  src/System.Windows.Forms/src/System/Windows/Forms/Internal/DrawingEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PaintEventArgs.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PaintEventArgsTests.cs
Labels: servicing-consider

#3914 Add ServiceProvider overloads
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ComponentDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.ControlDesignerAccessibleObject.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FormDocumentDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ParentControlDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ServiceProviderExtensions.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripDropDownDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripItemDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripMenuItemDesigner.cs
Labels: code cleanup

#3934 Correct regression introduced in #659
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowConverter.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewRowConverterTests.cs
Labels: area: VS designer, servicing-approved

#3866 Adding Text pattern to DataGridViewTextBoxCell
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxEditingControl.DataGridViewTextBoxEditingControlAccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTextBoxEditingControl.DataGridViewTextBoxEditingControlAccessibleObjectTests.cs
Labels: servicing-approved

#3942 Fix rendering of NumericUpDown control (#3939)
  src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.cs
  src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.cs
  src/System.Windows.Forms/tests/UnitTests/NumericUpDownTests.cs
Labels: servicing-consider

#3865 Adding Text pattern to ToolStripTextBox
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.MapWindowPoints.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Automation/UiaTextProvider.cs
  src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/Automation/UiaTextProviderTests.cs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseUiaTextProvider.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripControlHost.ToolStripHostedControlAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripTextBox.ToolStripTextBoxControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripTextBox.ToolStripTextBoxControlAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripTextBox.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTextBox.ToolStripTextBoxControlAccessibleObjectTests.cs
Labels: servicing-approved

#3876 Adding Text pattern to PropertyGridView.GridViewEdit
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewEdit.GridViewEditAccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewEdit.GridViewEditAccessibleObjectTests.cs
Labels: servicing-approved

#3875 Do not reset user fonts in DataGridView
  src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/EmfScope.cs
  src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/Validators/FontFaceNameValidator.cs
  src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/Validators/State.cs
  src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/Validators/TextOutValidator.cs
  src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/Validators/Validate.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/DataGridViewHeaders.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/DataGridViewHeaders.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTests.Rendering.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TextRendererTests.cs
Labels: :book: documentation: breaking, servicing-approved

#3967 Prepare CLI VB template for vs16.8 P4 VS templates.
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/.template.config/template.json
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/ApplicationEvents.vb
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/Company.WinFormsApplication1.vbproj
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/Program.vb
Labels: servicing-approved

#3972 Cut down warnings in VS
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/WindowsFormsApplicationBase.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Audio.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Network.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Interaction.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Logging/FileLogTraceListener.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/MyServices/ClipboardProxy.vb
  src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ExceptionCollectionTests.cs
  src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationServiceTests.cs
  src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/Serialization/CodeDomSerializerExceptionTests.cs
  src/System.Windows.Forms/src/System/Resources/ResXDataNode.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.PropertyBagStream.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataObject.OleConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MergePropertyDescriptor.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageListTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Layout/TableLayoutSettingsTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroupTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewSubItemTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/OwnerDrawPropertyBagTests.cs
Labels: code cleanup

#3878 Adding Text pattern to UpDownControls
  src/System.Windows.Forms/src/Resources/SR.resx
  src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownEdit.UpDownEditAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownEdit.cs
  src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/UpDownEditAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/UpDownBase.UpDownEdit.UpDownEditAccessibleObjectTests.cs
Labels: servicing-approved

#3964 Fixing "ListViewItem.ListViewItemAccessibleObject.ScrollIntoView" method
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObject.cs
Labels: :beetle: bug, api-approved, tenet-accessibility

#3993 Apply clipping and translation transforms correctly (#3990)
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/DeviceContextHdcScope.cs
  src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/DeviceContextHdcScopeTests.cs
Labels: servicing-approved

#4005 Adding more diagnostics around device contexts
  src/System.Windows.Forms.Primitives/src/Interop/Gdi32/Interop.CreateBrushScope.cs
  src/System.Windows.Forms.Primitives/src/Interop/Interop.HRESULT.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/DeviceContextHdcScope.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/DisposalTracking.cs
  src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/EmfScope.cs
  src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/ComCtl32/MCGRIDINFOTests.cs
  src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/ComCtl32/TASKDIALOGCONFIGIconUnionTests.cs
  src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/ComCtl32/TASKDIALOGCONFIGTests.cs
  src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/ComCtl32/TASKDIALOG_BUTTONTests.cs
  src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/Comdlg32/PRINTDLGWTests.cs
  src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/Oleaut32/SAFEARRAYTests.cs
  src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/Oleaut32/VARIANTTests.cs
  src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/DeviceContextHdcScopeTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TextRendererTests.cs
Labels: test-enhancement

#4004 use new intellisense blob, change package composition logic (#3999)
  eng/packageContent.targets
  global.json
Labels: area: infra, servicing-approved

#4007 Fix VS experience
  eng/packageContent.targets
  start-vs.cmd
Labels: :beetle: bug, area: infra

#3874 Remove incorrect assert
  src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
Labels: code cleanup

#3963 Fix ListView is in virtual mode
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListVIew.ListViewAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroupTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Labels: :beetle: bug, servicing-approved, tenet-accessibility
