Repository dotnet/winforms, pull requests merged in 2020-12, with the labels that each got.

#4289 Allow loading custom comctl32.dll
  .gitignore
  src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.LoadLibrary.cs
  src/System.Windows.Forms/src/System.Windows.Forms.csproj
  src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Properties/launchSettings.json
Labels: area: comctl/shell, tenet-OS-compat

#4325 Moving `CheckedListBox` nested types to separate files
  src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.CheckedIndexCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.CheckedItemCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.CheckedListBoxAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.CheckedListBoxItemAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.ObjectCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.cs
Labels: waiting-review

#4331 Refactored ListBox.ItemArray
  src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.CheckedIndexCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.CheckedItemCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ItemArray.Entry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ItemArray.EntryEnumerator.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ItemArray.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.AccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.ItemAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.ItemArray.Entry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.ItemArray.EntryEnumerator.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.ItemArray.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.ObjectCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.SelectedIndexCollection.cs
Labels: area: NRT, code cleanup, enhancement

#4314 Revert "Explicit ImageList ownership management" (servicing)
  src/System.Windows.Forms/src/System/Windows/Forms/ImageList.ImageCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ImageList.NativeImageList.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Labels: servicing-approved

#4290 Adding virtual mode validation for a double click
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiListViewTests/MauiListViewTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiTestsHelper/MouseHelper.cs
Labels: :book: documentation: breaking

#4354 Fixed position of bounding rectangle for ComboBox items when drop down shows a scrollbar
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ComboBoxes.Designer.cs
Labels: :mailbox_with_mail: waiting-for-testing, waiting-review

#4317 Fixing MonthCalendar a display dates range resets and flickers after calling UpdateBoldedDates
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs
Labels: waiting-review

#4384 Enable nullability in ConvertEventArgs and ListControlConvertEventArgs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ConvertEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListControlConvertEventArgs.cs
Labels: area: NRT

#4389 Fix #4385 for VB and fixed constant name from Framework
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Helpers/NativeTypes.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Interaction.vb
Labels: code cleanup
