Repository dotnet/winforms, pull requests merged in 2020-01, with the labels that each got.

#2548 Add ToolStripContentPanel tests and related Panel subclasses
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PanelTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPageTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripContentPanelTests.cs
Labels: test-enhancement

#2584 Cleanup ToolStripControlHost
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripControlHost.StubSite.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripControlHost.ToolStripControlHostAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripControlHost.ToolStripHostedControlAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripControlHost.cs
Labels: code cleanup

#2578 Cleanup ToolStripButton
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripButton.ToolStripButtonAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripButton.cs
Labels: enhancement

#2592 Remove unused MCM, MCHT and MCSC constants
  src/Common/src/NativeMethods.cs
Labels: code cleanup

#2611 Cleanup SplitterPanel
  src/System.Windows.Forms/src/System/Windows/Forms/SplitterPanel.cs
Labels: code cleanup

#2568 Add ControlAccessibleObject tests
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Control.ControlAccessibleObjectTests.cs
Labels: test-enhancement

#2594 Add PD and PD_RESULT enums in Interop Comdlg32
  src/Common/src/Interop/Comdlg32/Interop.PD.cs
  src/Common/src/Interop/Comdlg32/Interop.PD_RESULT.cs
  src/Common/src/NativeMethods.cs
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintDialog.cs
Labels: enhancement

#2605 Cleanup MessageBox interop
  src/Common/src/Interop/User32/Interop.ID.cs
  src/Common/src/Interop/User32/Interop.MB.cs
  src/Common/src/Interop/User32/Interop.MessageBoxW.cs
  src/Common/src/SafeNativeMethods.cs
  src/System.Windows.Forms.Design.Editors/src/Misc/NativeMethods.cs
  src/System.Windows.Forms.Design.Editors/src/System.Windows.Forms.Design.Editors.csproj
  src/System.Windows.Forms.Design.Editors/src/System/Drawing/Design/ColorEditor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MessageBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MessageBoxButtons.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MessageBoxDefaultButton.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MessageBoxIcon.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MessageBoxOptions.cs
Labels: enhancement

#2499 Fix DivideByZeroException in MonthCalendar
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs
Labels: enhancement, test-enhancement

#2607 Cleanup Control.SendMessage
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
  src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollableControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SplitContainer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
Labels: enhancement

#2556 Add ListViewInsertionMark ComCtl32 tests
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewInsertionMarkTests.cs
Labels: test-enhancement

#2628 Cleanup HDM constants
  src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.HDM.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.SendMessageW.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.WindowMessage.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ColumnHeader.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
Labels: :octocat: automerge, enhancement

#2631 Cleanup TTN_ constants
  src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.TTN.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
Labels: enhancement

#2635 Cleanup ERROR_ constants
  src/System.Windows.Forms.Primitives/src/Interop/Interop.ERROR.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
Labels: enhancement

#2634 Cleanup some Menu interop
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
Labels: code cleanup

#2626 Cleanup NM_ constants
  src/System.Windows.Forms.Design.Editors/src/System/ComponentModel/Design/ObjectSelectorEditor.cs
  src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.NM.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/StatusBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
Labels: enhancement

#2581 Add ToolStripRenderer tests
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripRendererTests.cs
Labels: test-enhancement

#2632 Cleanup TCN constants
  src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.TCN.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
Labels: enhancement

#2514 Add TrackBar tests and update tests to match styles for other ComCtl32 controls
  src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.TBM.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.cs
  src/System.Windows.Forms/tests/UnitTests/CheckedListBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHostTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ContainerControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Handlers.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Methods.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Properties.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PanelTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PictureBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ProgressBarTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollBarTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs
  src/System.Windows.Forms/tests/UnitTests/TrackBarTests.cs
Labels: test-enhancement

#2618 Move SetLayeredWindowAttributes to Interop User32 and add LWA enum
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.LWA.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.SetLayeredWindowAttributes.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDown.cs
Labels: enhancement

#2620 Add EC, EN and ES enums in Interop User32
  src/System.Windows.Forms.Design.Editors/src/System/Drawing/Design/ColorEditor.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.EC.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.EN.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.ES.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MaskedTextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
Labels: enhancement

#2650 Add MenuCommandService
  src/System.Design/src/ApiCompatBaseline.netcoreapp.txt
  src/System.Windows.Forms.Design/src/Resources/SR.resx
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionMethodItem.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/MenuCommandService.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/MenuCommandsChangedEventArgs.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/MenuCommandsChangedEventHandler.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/MenuCommandsChangedType.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2TypeInfoProcessor.cs
Labels: :octocat: automerge

#2597 Move ChildWindowFromPointEx to Interop User32 and add CWP enum
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.CWP.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.ChildWindowFromPointEx.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/GetChildAtPointSkip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
Labels: enhancement

#2652 Fix missing reference
  pkg/Microsoft.Private.Winforms/Microsoft.Private.Winforms.csproj
Labels: :octocat: automerge

#2588 Add SB and SBT enums in Interop ComCtl32 and SBS and SS enums in User32
  src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.SB.cs
  src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.SBT.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.SBS.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.SS.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HScrollBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Label.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/StatusBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/StatusBarPanel.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/VScrollBar.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroupTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Labels: enhancement

#2622 Cleanup a bunch of ListView constants
  src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.LVA.cs
  src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.LVIR.cs
  src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.LVNI.cs
  src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.LVSCW.cs
  src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.LVSIL.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ItemBoundsPortion.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewAlignment.cs
Labels: :octocat: automerge, enhancement

#2612 Add tests for Control.AssignParent
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Properties.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FormTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PictureBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/SplitterPanelTests.cs
Labels: test-enhancement

#2447 Remove GetWindowLong and SetWindowLong from UnsafeNativeMethods.cs an…
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionUI.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetWindowLong.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.SetWindowLong.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Application.ModalApplicationContext.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/CommonDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.cs
  src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDown.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
Labels: enhancement

#2661 fix casing in csproj
  src/System.Windows.Forms/src/System.Windows.Forms.csproj
Labels: :octocat: automerge, code cleanup

#2648 Cleanup NMHEADERW interop
  src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.NMHEADERW.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
Labels: enhancement

#2539 Remove commented out code
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerUtils.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/MaskDesignerDialog.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/MaskPropertyEditor.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripMenuItemDesigner.cs
  src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ComponentDesignerTests.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/CheckBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2Enum.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2TypeInfoProcessor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/ComNativeDescriptor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs
  src/System.Windows.Forms/src/System/Windows/Forms/CurrencyManager.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewAdvancedBorderStyle.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellLinkedList.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellStyle.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewSelectedCellCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewSelectedRowCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Label.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.cs
  src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MDIControlStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MaskedTextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/ArrayElementGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridToolTip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MultiSelectRootGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/RelatedPropertyManager.cs
  src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SendKeys.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Splitter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelRow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Triangle.cs
  src/System.Windows.Forms/src/misc/GDI/WindowsGraphicsCacheManager.cs
Labels: code cleanup

#2670 Use BitOperations.PopCount instead of GetBitCount
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/ClientUtils.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WinFormsUtils.cs
Labels: enhancement, tenet-performance

#2691 Cleanup DISPATCH_ interop
  src/System.Windows.Forms.Primitives/src/Interop/Interop.HRESULT.cs
  src/System.Windows.Forms.Primitives/src/Interop/OleAut32/Interop.DISPATCH.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2AboutBoxPropertyDescriptor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/ComNativeDescriptor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlDocument.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlElement.cs
Labels: enhancement

#2669 Cleanup CBS_ and CBN_ constants
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.CB.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.CBN.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.CBS.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/FontDialog.cs
Labels: enhancement

#2596 Add TextBoxBase tests
  src/System.Windows.Forms/src/System/Windows/Forms/Control.Ime.cs
  src/System.Windows.Forms/tests/UnitTests/TextBoxBaseTests.cs
  src/System.Windows.Forms/tests/UnitTests/TextBoxTests.cs
Labels: test-enhancement

#2692 Cleanup Button interop
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.BM.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.BN.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Button.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs
  src/System.Windows.Forms/src/System/Windows/Forms/CheckBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/RadioButton.cs
Labels: enhancement

#2666 Remove unused window messages
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.WindowMessage.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
Labels: code cleanup

#2639 Improve performance of Enum*Windows() interop functions
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.EnumChildWindows.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.EnumThreadWindows.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.EnumWindows.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadWindows.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
Labels: enhancement, tenet-performance

#2713 fix: Race conditions adding `ThreadContext` to TLS
  src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs
Labels: test-enhancement

#2715 Update .editorConfig to add support for VB and move all dotnet rules …
  .editorconfig
Labels: enhancement

#2563 Fix NullReferenceException serializing TableLayoutSettings for controls without name
  src/System.Windows.Forms/src/Resources/SR.resx
  src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutSettingsTypeConverter.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Layout/TableLayoutSettingsTypeConverterTests.cs
Labels: :octocat: automerge, test-enhancement

#2711 Cleanup WindowMessage RegisteredMessages
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.RegisteredMessage.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.WindowMessage.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlNativeWindow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
Labels: enhancement

#2679 Improve PaddingConverter CreateInstance implementation
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/PaddingConverter.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PaddingConverterTests.cs
Labels: api-approved

#2716 Fix VisualBasic Mouse tests
  src/Microsoft.VisualBasic/tests/UnitTests/Microsoft/VisualBasic/Devices/MouseTests.cs
Labels: test-bug, test-enhancement

#2667 Cleanup DTM window messages
  src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.DTM.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.WindowMessage.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.cs
Labels: enhancement

#2739 Remove unused ACM, CP, CONNECT, GCL, IMAGE, LOCK, MB, MSH and PSM constants
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
Labels: code cleanup

#2659 Cleanup MENUITEM structs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetMenuItemInfoW.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.MENUITEMINFOW.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.MFS.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.MFT.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.MIIM.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownMenu.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripMenuItem.cs
Labels: enhancement, waiting-review

#2559 Add TableLayoutPanel tests
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Properties.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Layout/TableLayoutSettingsTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TableLayoutControlCollectionTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TableLayoutPanelTests.cs
Labels: test-enhancement

#2658 Cleanup CHOOSEFONT
  src/System.Windows.Forms.Primitives/src/Interop/Comdlg32/Interop.ChooseFontW.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/SafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/FontDialog.cs
Labels: enhancement

#2645 Cleanup NMTTDISPINFOW interop
  src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.NMTTDISPINFOW.cs
  src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.TTF.cs
  src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.TTOOLINFOW.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolTipBuffer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MultipleControls.Designer.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolTipBufferTests.cs
Labels: enhancement

#2616 Move DrawMenuBar to Interop User32
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.DrawMenuBar.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/SafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
Labels: enhancement

#2766 Move ScrollWindow to Interop User32
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.ScrollWindow.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/SafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewControl.cs
Labels: :octocat: automerge

#2764 Remove Succeeded and Failed methods from NativeMethods.cs
  src/System.Windows.Forms.Primitives/src/System/ExternDll.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/SafeNativeMethods.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2TypeInfoProcessor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXFontMarshaler.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs
Labels: :octocat: automerge, code cleanup

#2787 Enable PublicApiAnalyzers by default
  eng/ApiCompatibility/PublicApiAnalyzer.props
  eng/ApiCompatibility/PublicApiAnalyzer.targets
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
Labels: :octocat: automerge

#2615 Use SendMessageW directly and remove TreeView_GetExtendedStyle and TreeView_SetExtendedStyle
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ObjectSelectorEditor.cs
Labels: code cleanup
