Repository dotnet/winforms, pull requests merged in 2020-06, with the labels that each got.

#3368 Add ListBox SelectedItems tests
  eng/NonShipping.ruleset
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.SelectedIndexCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.SelectedObjectCollection.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewColumnCollectionTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewSelectedCellCollectionTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewSelectedColumnCollectionTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewSelectedRowCollectionTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageList.ImageCollectionTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBox.IntegerCollectionTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBox.ObjectCollectionTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBox.SelectedIndexCollectionTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBox.SelectedObjectCollectionTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBoxTests.cs
Labels: :book: documentation: breaking, test-enhancement

#2823 Enable nullability for ScrollBar/ScrollProperties
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/HScrollBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HScrollProperties.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollProperties.cs
  src/System.Windows.Forms/src/System/Windows/Forms/VScrollBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/VScrollProperties.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollableControlTests.cs
Labels: :octocat: automerge, area: NRT

#3389 Add local dev convenience scripts
  build-local.ps1
  start-code.cmd
  start-vs.cmd
Labels: area: infra

#3397 LOC CHECKIN | dotnet/winforms master | 20200605
  src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.cs.xlf
  src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.de.xlf
  src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.es.xlf
  src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.fr.xlf
  src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.it.xlf
  src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.ja.xlf
  src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.ko.xlf
  src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.pl.xlf
  src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.pt-BR.xlf
  src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.ru.xlf
  src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.tr.xlf
  src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.zh-Hans.xlf
  src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
Labels: :octocat: automerge

#3398 Call UiaDisconnectProvider from Control.ReleaseUiaProvider
  build-local.ps1
  src/Common/src/OsVersion.cs
  src/Common/src/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
  start-code.cmd
  start-vs.cmd
Labels: servicing-approved

#3324 Cleanup CopyMemory/WideCharToMultiByte
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ByteViewer.cs
  src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ByteViewerTests.cs
  src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.CP.cs
  src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.MultiByteToWideChar.cs
  src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.WideCharToMultiByte.cs
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.DROPFILES.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageList.ImageCollectionTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TableLayoutPanelTests.cs
Labels: enhancement

#3407 Cleanup CA code
  src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.CA.cs
  src/System.Windows.Forms.Primitives/src/Interop/OleAut32/Interop.IPerPropertyBrowsing.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxPropertyDescriptor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/BaseCAMarshaler.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IPerPropertyBrowsingHandler.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/Int32CAMarshaler.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/OleStrCAMarshaler.cs
Labels: enhancement

#3408 Fix local WebBrowser tests
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/WebBrowserTests.cs
Labels: test-bug

#3415 Make HtmlElement tests machine agnostic
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/HtmlDocumentTests.cs
Labels: test-bug

#3335 Avoid initializing native tools twice
  eng/configure-toolset.ps1
  eng/packageContent.targets
Labels: area: infra

#3442 Add scoping structs for Win32 objects
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/MultilineStringEditor.cs
  src/System.Windows.Forms.Primitives/src/Interop/Gdi32/Interop.CreateDcScope.cs
  src/System.Windows.Forms.Primitives/src/Interop/Gdi32/Interop.ObjectScope.cs
  src/System.Windows.Forms.Primitives/src/Interop/Gdi32/Interop.Rop2Scope.cs
  src/System.Windows.Forms.Primitives/src/Interop/Gdi32/Interop.SelectionScope.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetDcScope.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/DpiHelper.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/ScreenDC.cs
  src/System.Windows.Forms.Primitives/tests/TestUtilities/GdiHelper.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/FontDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserHelper.cs
Labels: enhancement

#3463 Remove StringSorter
  src/System.Windows.Forms/src/Resources/SR.resx
  src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntryComparer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/SingleSelectRootGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/StringSorter.cs
Labels: code cleanup

#3448 Add more combinations of REFLECT with other values in WM enum
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ObjectSelectorEditor.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.WM.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Button.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs
  src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.cs
Labels: enhancement

#3366 Test AxHost ICustomTypeDescriptor implementation
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxPropertyDescriptor.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHost.AxPropertyDescriptorTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHostTests.cs
Labels: test-enhancement

#3465 Cleanup Critical Exception Handling
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/ClientUtils.cs
  src/System.Windows.Forms/src/System/Resources/ResXDataNode.cs
  src/System.Windows.Forms/src/System/Resources/ResXResourceReader.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Binding.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Clipboard.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXFontMarshaler.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DCMapping.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlDocument.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlElement.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MaskedTextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowser.cs
  src/System.Windows.Forms/src/misc/DbgUtil.cs
  src/System.Windows.Forms/src/misc/GDI/WindowsGraphics.cs
  src/System.Windows.Forms/src/misc/GDI/WindowsSolidBrush.cs
  src/System.Windows.Forms/src/misc/MultitargetUtil.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/BindingTests.cs
Labels: code cleanup

#3323 Move FileDialogNative code to modern interop model
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.COMDLG_FILTERSPEC.cs
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.FDAP.cs
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.GETPROPERTYSTOREFLAGS.cs
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.IFileDialog.cs
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.IFileDialogCustomize.cs
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.IFileDialogEvents.cs
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.IFileOpenDialog.cs
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.IFileSaveDialog.cs
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.IShellItem.cs
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.IShellItemArray.cs
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.PROPERTYKEY.cs
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SFGAOF.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/FileDialogCustomPlacesCollection.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/FileDialog_Vista_Interop.cs
  src/System.Windows.Forms/src/System/Windows/Forms/FileDialog_Vista.cs
  src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/OpenFileDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SaveFileDialog.cs
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/MainFormControlsTabOrder.cs
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests/WinformsControlsTest.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/FileDialog.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/FileDialog.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/FileDialog.resx
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FileDialogTests.cs
Labels: :mailbox_with_no_mail: waiting-author-feedback

#3237 Nullable annotate InputLanguage
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/Resources/SR.resx
  src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
  src/System.Windows.Forms/src/System/Windows/Forms/InputLanguageChangedEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/InputLanguageChangedEventHandler.cs
  src/System.Windows.Forms/src/System/Windows/Forms/InputLanguageChangingEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/InputLanguageChangingEventHandler.cs
  src/System.Windows.Forms/src/System/Windows/Forms/InputLanguageCollection.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/InputLanguageChangedEventArgsTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/InputLanguageChangingEventArgsTests.cs
Labels: :book: documentation: breaking, area: NRT, enhancement

#3489 Prepare for strict coherency
  eng/Version.Details.xml
  eng/Versions.props
Labels: area: infra

#3486 ImageList must be disposed
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageListTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs
Labels: test-bug

#3497 Add tests for TreeNodeCollection Find method
  src/System.Windows.Forms/src/System/Windows/Forms/TreeNodeCollection.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.ControlCollection.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNodeCollectionTests.cs
Labels: :book: documentation: breaking, test-enhancement
