Repository dotnet/winforms, pull requests merged in 2020-11, with the labels that each got.

#4177 Fix Application.EnableVisualStyles in single file publishing mode (servicing)
  src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.ACTCTXW.cs
  src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.ACTCTX_FLAG.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/ThemingScope.cs
  src/System.Windows.Forms/src/System.Windows.Forms.csproj
  src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ApplicationTests.cs
Labels: servicing-approved

#4165 Allow setting `TreeNode` image index to magic number `-2` (servicing)
  src/System.Windows.Forms/src/System/Windows/Forms/ImageIndexConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ImageList.Indexer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItemStateImageIndexConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeViewImageIndexConverter.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItemStateImageIndexConverterTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/NoneExcludedImageIndexConverterTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNodeTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewImageIndexConverterTests.cs
Labels: servicing-approved

#4203 Cache semantic models per syntax tree
  src/System.Windows.Forms.SourceGenerators/src/System/Windows/Forms/SourceGenerators/EnumValidationGenerator.cs
Labels: tenet-performance

#4221 Enable visual styles (#4197)
  src/System.Windows.Forms/tests/TestUtilities/ThreadExceptionFixture.cs
  src/System.Windows.Forms/tests/UnitTests/NumericUpDownTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ButtonRenderingTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Handlers.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewHeaderCellTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DomainUpDownTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/GroupBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageList.ImageCollectionTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollableControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPageTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TextBoxBase.TextBoxBaseUiaTextProviderTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/UpDownBaseTests.cs
Labels: test-enhancement

#4220 Narrator and Inspect become unresponsive inspecting `Combobox` control (servicing)
  src/System.Windows.Forms.Primitives/src/Interop/UiaCore/Interop.IRawElementProviderHwndOverride.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
Labels: :boom: regression, a11yMAS, servicing-approved, tenet-accessibility

#4232 Add Save/Load test for ToolStripSettingsManager
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripSettingsManagerTests.cs
Labels: test-enhancement

#4209 Correct `EnumVariantObject` definition (servicing)
  src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.EnumVariantObject.cs
Labels: a11yMAS, servicing-approved, tenet-accessibility

#4222 Fix `ListView` no longer displays images (servicing)
  src/System.Windows.Forms/src/System/Windows/Forms/ImageList.ImageCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListViewTest.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListViewTest.cs
Labels: :boom: regression, servicing-approved

#4063 Add focus rectangle focus to ToolStripButtons on PropertyGrid
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridToolStripButton.cs
Labels: :mailbox_with_mail: waiting-for-testing

#4241 Fix OnInitialize fails to compile if VB Compile Options changes
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/My Project/Application.Designer.HighDpi.vb
Labels: area: Visual Basic

#4233 Use 'is not null' in System.Windows.Forms.Primitives
  src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.TTOOLINFOW.cs
  src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.GPStream.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/DeviceContextHdcScope.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/FileDialogCustomPlacesCollection.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/GdiPlus/GdiPlusCache.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/DpiHelper.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/WeakRefCollection.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/ObjectCache.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/RefCountedCache.Scope.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/SinglyLinkedList.cs
Labels: code cleanup

#4281 fix: Prevent GC'on of native callback
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
Labels: servicing-approved

#4185 Fixing broken hierarchy for items list in Combobox
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildDropDownButtonUiaProvider.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildEditUiaProvider.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildListUiaProvider.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildNativeWindow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildTextUiaProvider.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxChildDropDownButtonUiaProviderTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxChildEditUiaProviderTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxChildListUiaProviderTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxChildTextUiaProviderTests.cs
Labels: waiting-review

#4003 Use function pointers for native TaskDialog and Enum*Windows callbacks
  src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.PFTASKDIALOGCALLBACK.cs
  src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.TASKDIALOGCONFIG.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.EnumChildWindows.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.EnumThreadWindows.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.EnumWindows.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TaskDialog.cs
Labels: area: interop

#3603 Use native-sized integers to avoid overhead for 32-bit platforms
  src/System.Windows.Forms.Primitives/src/Interop/Interop.PARAM.cs
  src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/PARAMTests.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TaskDialog.cs
Labels: enhancement

#4286 Fixing ErrorProvider error text announcing by a screen reader
  src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.cs
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/MainFormControlsTabOrder.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ErrorProviderTest.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ErrorProviderTest.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ErrorProviderTest.resx
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs
Labels: waiting-review

#4249 Adding a part of the `DataGridView` test app to check DGV in Virtual mode
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/MainFormControlsTabOrder.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/DataGridViewInVirtualModeTest.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/DataGridViewInVirtualModeTest.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/DataGridViewInVirtualModeTest.resx
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/DataGridViewTest.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/DataGridViewTest.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/DataGridViewTest.resx
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/TestCustomer.cs
Labels: waiting-review
