Repository dotnet/winforms, pull requests merged in 2021-04, with the labels that each got.

#4715 Adding 'TypeForwardedFrom' attribute for System.Windows.Forms.Padding.
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Padding.cs
Labels: servicing-approved

#4424 Use generic lists in LinkLabel
  src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.LinkCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.LinkComparer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/LinkLabel.LinkComparerTests.cs
Labels: area: NRT, enhancement

#4744 Fix ANE in the "ListViewSubItemAccessibleObjectin " constructor
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItemCollection.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewSubItemCollectionTests.cs
Labels: servicing-approved

#4753 Porting: Fixing missing 'TypeForwardedFrom' attribute
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Padding.cs
Labels: servicing-approved

#4764 Fix ANE in the "ListViewSubItemAccessibleObjectin" constructor (#4744) (port to 5.0)
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItemCollection.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewSubItemCollectionTests.cs
Labels: servicing-approved

#4800 Fix rectangle of the ListViewGroup
  src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.LVGGR.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListVIew.ListViewAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObjectTests.cs
Labels: :octocat: automerge

#4837 Script to mark API as shipped
  eng/ApiCompatibility/README.md
  eng/ApiCompatibility/mark-shipped.cmd
  eng/ApiCompatibility/mark-shipped.ps1
Labels: area: infra
