Repository dotnet/winforms, pull requests merged in 2021-01, with the labels that each got.

#4423 Enable nullability in DragEventArgs and ItemDragEventArgs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DragEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ItemDragEventArgs.cs
Labels: area: NRT

#4438 Check font returned via `SystemParametersInfoW` interop
  src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/User32/SystemParametersInfoWTests.cs
Labels: test-enhancement

#4432 Custom accessibleRole, accessibleName, accessibleDescription for controls in Accessibility test app
  src/System.Windows.Forms/tests/AccessibilityTests/CustomAccessiblePropertiesForm.Designer.cs
  src/System.Windows.Forms/tests/AccessibilityTests/CustomAccessiblePropertiesForm.cs
  src/System.Windows.Forms/tests/AccessibilityTests/CustomAccessiblePropertiesForm.resx
  src/System.Windows.Forms/tests/AccessibilityTests/Main.Designer.cs
  src/System.Windows.Forms/tests/AccessibilityTests/Main.cs
Labels: test-enhancement

#4352 Fixing issue with getting of textbox from DataGridViewTextBoxCell by Accessibility Insights (port to 3.1)
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellTests.cs
Labels: servicing-approved

#4351 Fixing issue with getting of textbox from DataGridViewTextBoxCell by Accessibility Insights (port to 5.0)
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellTests.cs
Labels: servicing-approved

#4452 Implemented ScrollItemPattern for ComboBoxItemAccessibleObject (port to 5.0)
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/MainFormControlsTabOrder.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ComboBoxesWithScrollBars.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ComboBoxesWithScrollBars.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ComboBoxesWithScrollBars.resx
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObjectTests.cs
Labels: servicing-approved, waiting-review

#4453 Implemented ScrollItemPattern for ComboBoxItemAccessibleObject (port to 3.1)
  src/Common/src/NativeMethods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/MainFormControlsTabOrder.cs
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests/WinformsControlsTest.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinFormsControlsClassicTests/WinFormsControlsClassicTests.csproj
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ComboBoxesWithScrollBars.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ComboBoxesWithScrollBars.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ComboBoxesWithScrollBars.resx
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObjectTests.cs
Labels: servicing-approved, waiting-review

#4476 Add tests for #4388
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MdiControlStripTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripMenuItemTests.cs
Labels: test-enhancement

#4396 Enable nullability in Control.AmbientProperty, Control.Ime and Contro…
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Control.AmbientProperty.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.Ime.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ThreadMethodEntry.cs
Labels: area: NRT
