Repository dotnet/winforms, pull requests merged in 2021-06, with the labels that each got.

#5012 Spelling src system.windows.forms.primitives src
  src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.MCGIF.cs
  src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.MCS.cs
  src/System.Windows.Forms.Primitives/src/Interop/Gdi32/Interop.SelectPaletteScope.cs
  src/System.Windows.Forms.Primitives/src/Interop/Mso/Interop.IMsoComponent.cs
  src/System.Windows.Forms.Primitives/src/Interop/Mso/Interop.msocstate.cs
  src/System.Windows.Forms.Primitives/src/Interop/Mso/Interop.msoloop.cs
  src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.IStream.cs
  src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.STATSTG.cs
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.DragQueryFileW.cs
  src/System.Windows.Forms.Primitives/src/Interop/UiaCore/Interop.IAccessibleEx.cs
  src/System.Windows.Forms.Primitives/src/Interop/UiaCore/Interop.IInvokeProvider.cs
  src/System.Windows.Forms.Primitives/src/Interop/UiaCore/Interop.IRawElementProviderFragment.cs
  src/System.Windows.Forms.Primitives/src/Interop/UiaCore/Interop.ISelectionProvider.cs
  src/System.Windows.Forms.Primitives/src/Interop/VSSDK/Interop.IVsPerPropertyBrowsing.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/DeviceContextExtensions.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/DeviceContextHdcScope.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/DpiHelper.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/WeakRefCollection.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/SystemDrawingExtensions.cs
Labels: code cleanup

#4922 enable nullable for new projects
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/.template.config/dotnetcli.host.json
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/.template.config/template.json
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/Company.WinFormsApplication1.csproj
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-CSharp/.template.config/dotnetcli.host.json
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-CSharp/.template.config/template.json
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-CSharp/Company.ControlLibrary1.csproj
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-CSharp/.template.config/dotnetcli.host.json
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-CSharp/.template.config/template.json
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-CSharp/Company.ClassLibrary1.csproj
Labels: :no_entry_sign: * NO-MERGE *, area: templates

#5025 Changing control types of DataGridView and its TextBox cell
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.AccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxCell.DataGridViewTextBoxCellAccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/DataGridViewAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTextBoxCell.DataGridViewTextBoxCellAccessibleObjectTests.cs
Labels: waiting-review

#4782 Replace EnumValidator - Unit Tests and Changing the Validator
  src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs
  src/System.Windows.Forms/src/System/Windows/Forms/CheckBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Label.cs
  src/System.Windows.Forms/src/System/Windows/Forms/RadioButton.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripControlHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WinFormsUtils.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/LabelTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RadioButtonTests.cs
Labels: :octocat: automerge

#4968 correct defaultValue of ListView.HideSelection
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
Labels: :book: documentation: breaking, tenet-accessibility

#5075 Fix StartupNextInstance when the main Form is nothing.
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/WindowsFormsApplicationBase.vb
Labels: waiting-review

#5173 Remove stale and obsolete dependencies. Add CMake SDK.
  eng/Version.Details.xml
  eng/Versions.props
  global.json
Labels: area: infra
