Repository dotnet/winforms, pull requests merged in 2021-03, with the labels that each got.

#4620 Enable nullability in GridItem and GridItemCollection
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/GridItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/GridItemCollection.cs
Labels: area: NRT

#4606 Moved sub-classes of "FileDialog", "OpenFileDialog" and "SaveFileDialog" classes to their own files
  src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.Vista.cs
  src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.VistaDialogEvents.cs
  src/System.Windows.Forms/src/System/Windows/Forms/OpenFileDialog.FileOpenDialogRCW.cs
  src/System.Windows.Forms/src/System/Windows/Forms/OpenFileDialog.NativeFileOpenDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/OpenFileDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SaveFileDialog.FileSaveDialogRCW.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SaveFileDialog.NativeFileSaveDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SaveFileDialog.cs
Labels: code cleanup

#4611 fix PropertyGrid value rendering (servicing 5.0)
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextRenderer.cs
  src/System.Windows.Forms/tests/UnitTests/PropertyGridInternal/PropertyGridViewTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertiesTabTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyGridViewTests.Rendering.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyGridViewTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TextRendererTests.cs
Labels: servicing-approved

#4658 Enable nullability in TreeViewCancelEventArgs and TreeViewEventArgs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/TreeViewCancelEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeViewEventArgs.cs
Labels: area: NRT

#4632 Enable NRT for FileDialog.Vista
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.Vista.cs
Labels: area: NRT

#4652 Enable nullability in Keys and TableLayoutPanelGrowStyle
  src/System.Windows.Forms/src/System/Windows/Forms/Keys.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutPanelGrowStyle.cs
Labels: area: NRT

#4657 Enable nullability in DrawListView EventArgs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DrawListViewColumnHeaderEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DrawListViewItemEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DrawListViewSubItemEventArgs.cs
Labels: area: NRT

#4684 Enable nullability in PropertyTabChangedEventArgs and PropertyValueCh…
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyTabChangedEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyValueChangedEventArgs.cs
Labels: area: NRT

#4702 Move sub-classes of "HtmlDocument", "HtmlElement" and "HtmlWindow" classes to their own files
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlDocument.HTMLDocumentEvents2.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlDocument.HtmlDocumentShim.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlDocument.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlElement.HTMLElementEvents2.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlElement.HtmlElementShim.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlElement.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlWindow.HTMLWindowEvents2.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlWindow.HtmlWindowShim.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlWindow.cs
Labels: code cleanup

#4706 Move sub-classes of "PropertyDescriptorGridEntry" and "PropertyStore" classes to their own files
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.ExceptionConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.ExceptionEditor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyStore.ColorWrapper.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyStore.PaddingWrapper.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyStore.RectangleWrapper.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyStore.SizeWrapper.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyStore.cs
Labels: code cleanup

#4683 Enable nullability in DrawToolTipEventArgs and DrawTreeNodeEventArgs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DrawToolTipEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DrawTreeNodeEventArgs.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DrawTreeNodeEventArgsTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs
Labels: :book: documentation: breaking, area: NRT

#4695 Move sub-classes of "DataGridViewTopLeftHeaderCell", "FlatButtonAppearance" and "FontCacheEntry" classes to their own files
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ApplicableToButtonAttribute.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTopLeftHeaderCell.DataGridViewTopLeftHeaderCellAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTopLeftHeaderCell.DataGridViewTopLeftHeaderCellRenderer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTopLeftHeaderCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/FlatButtonAppearance.cs
  src/System.Windows.Forms/src/System/Windows/Forms/FlatButtonAppearanceConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Internal/Gdi/FontCache.FontCacheEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Internal/Gdi/FontCache.cs
Labels: :book: documentation: breaking, area: NRT

#4676 Enable nullability in some DataGridViewRow EventArgs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowCancelEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowContextMenuStripNeededEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowDividerDoubleClickEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowErrorTextNeededEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowPostPaintEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowPrePaintEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowStateChangedEventArgs.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewRowDividerDoubleClickEventArgsTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewRowStateChangedEventArgsTests.cs
Labels: :book: documentation: breaking, area: NRT
