Repository dotnet/winforms, pull requests merged in 2021-05, with the labels that each got.

#4889 Use .NET certificate
  eng/Signing.props
Labels: area: infra

#4761 Fix incorrect behavior of ListViewSubItem
  docs/accessibility/listview-expected-behavior.md
  docs/images/listview-disabledstyles-inspect-details-view-tree.png
  docs/images/listview-disabledstyles-inspect-largeicon-view-tree.png
  docs/images/listview-disabledstyles-inspect-list-view-tree.png
  docs/images/listview-disabledstyles-inspect-smallicon-view-tree.png
  docs/images/listview-disabledstyles-inspect-tile-view-tree.png
  docs/images/listview-inspect-details-view-tree.png
  docs/images/listview-inspect-largeicon-view-tree.png
  docs/images/listview-inspect-list-view-tree.png
  docs/images/listview-inspect-smallicon-view-tree.png
  docs/images/listview-inspect-tile-view-tree.png
  docs/images/listview-showgroupdisabled-inspect-details-view-tree.png
  docs/images/listview-showgroupdisabled-inspect-largeicon-view-tree.png
  docs/images/listview-showgroupdisabled-inspect-list-view-tree.png
  docs/images/listview-showgroupdisabled-inspect-smallicon-view-tree.png
  docs/images/listview-showgroupdisabled-inspect-tile-view-tree.png
  docs/images/listview-virtualmode-inspect-details-view-tree.png
  docs/images/listview-virtualmode-inspect-largeicon-view-tree.png
  docs/images/listview-virtualmode-inspect-list-view-tree.png
  docs/images/listview-virtualmode-inspect-smallicon-view-tree.png
  docs/images/listview-withgroup-inspect-details-view-tree.png
  docs/images/listview-withgroup-inspect-largeicon-view-tree.png
  docs/images/listview-withgroup-inspect-list-view-tree.png
  docs/images/listview-withgroup-inspect-smallicon-view-tree.png
  docs/images/listview-withgroup-inspect-tile-view-tree.png
  docs/images/listview-withoutgroup-inspect-details-view-tree.png
  docs/images/listview-withoutgroup-inspect-largeicon-view-tree.png
  docs/images/listview-withoutgroup-inspect-list-view-tree.png
  docs/images/listview-withoutgroup-inspect-smallicon-view-tree.png
  docs/images/listview-withoutgroup-inspect-tile-view-tree.png
  docs/images/listviewsubitem-disabledvisualstyles-inspect-tile-view-tree.png
  docs/images/listviewsubitem-inspect-details-view-tree.png
  docs/images/listviewsubitem-inspect-largeicon-view-tree.png
  docs/images/listviewsubitem-inspect-list-view-tree.png
  docs/images/listviewsubitem-inspect-smallicon-view-tree.png
  docs/images/listviewsubitem-inspect-tile-view-tree.png
  docs/images/listviewsubitem-smallsize-inspect-tile-view-tree.png
  docs/images/listviewsubitem-threeitems-inspect-tile-view-tree.png
  docs/images/listviewsubitem-twocolumns-inspect-details-view-tree.png
  docs/images/listviewsubitem-twocolumns-inspect-tile-view-tree.png
  docs/images/listviewsubitem-twosubitems-inspect-details-view-tree.png
  src/System.Windows.Forms/src/Properties/AssemblyInfo.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.cs
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiListViewTests/MauiListViewTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListVIew.ListViewAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Labels: :octocat: automerge

#4915 Validate input in Application.SetHighDpiMode() method
  src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ApplicationTests.cs
Labels: test-enhancement

#4923 Rename private source generators project
  Winforms.sln
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms.PrivateSourceGenerators/README.md
  src/System.Windows.Forms.PrivateSourceGenerators/src/System.Windows.Forms.PrivateSourceGenerators.csproj
  src/System.Windows.Forms.PrivateSourceGenerators/src/System/Windows/Forms/SourceGenerators/EnumValidationGenerator.cs
  src/System.Windows.Forms.PrivateSourceGenerators/src/System/Windows/Forms/SourceGenerators/EnumValidationInfo.cs
  src/System.Windows.Forms.PrivateSourceGenerators/src/System/Windows/Forms/SourceGenerators/SyntaxReceiver.cs
  src/System.Windows.Forms.PrivateSourceGenerators/tests/UnitTests/EnumValidationTests.cs
  src/System.Windows.Forms.PrivateSourceGenerators/tests/UnitTests/System.Windows.Forms.PrivateSourceGenerators.Tests.csproj
  src/System.Windows.Forms/src/System.Windows.Forms.csproj
Labels: area: infra

#4932 Enable nullability in TableLayoutCellPaintEventArgs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutCellPaintEventArgs.cs
Labels: area: NRT

#4717 Fixing GridEntry padding
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/CategoryGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs
Labels: area: HDPI

#4796 Fix regression in ParkHandle method from .NET framework
  src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Application.ParkingWindowTests.cs
Labels: area: HDPI

#4653 Enable nullability in OwnerDrawPropertyBag
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/OwnerDrawPropertyBag.cs
Labels: area: NRT

#4960 Enable nullability in some DataGridViewCell EventArgs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellMouseEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellParsingEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellValueEventArgs.cs
Labels: area: NRT

#4952 Stop NativeImageList GDI leak
  Winforms.sln
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GR.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetGuiResources.cs
  src/System.Windows.Forms.Primitives/src/Properties/AssemblyInfo.cs
  src/System.Windows.Forms/src/Properties/AssemblyInfo.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ImageList.NativeImageList.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/ImageListTests/MauiImageListTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/ImageListTests/MauiImageListTests.csproj
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.Maui.IntegrationTests/MauiTestHelper.cs
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.Maui.IntegrationTests/WinformsMauiImageListTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListViewTest.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageList.NativeImageListTests.cs
Labels: servicing-consider

#4975 Stop NativeImageList GDI leak (servicing)
  Winforms.sln
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GR.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetGuiResources.cs
  src/System.Windows.Forms.Primitives/src/Properties/AssemblyInfo.cs
  src/System.Windows.Forms/src/Properties/AssemblyInfo.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ImageList.NativeImageList.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/ImageListTests/MauiImageListTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/ImageListTests/MauiImageListTests.csproj
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.Maui.IntegrationTests/MauiTestHelper.cs
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.Maui.IntegrationTests/WinformsMauiImageListTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListViewTest.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageList.NativeImageListTests.cs
Labels: servicing-approved

#4961 Enable nullability in DpiChangedEventArgs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DpiChangedEventArgs.cs
Labels: area: NRT

#4976 Fix OneLoc build step
  eng/Localize/LocProject.json
Labels: area: infra

#4910 Separating ListViewItemAccessibleObject
  src/System.Windows.Forms/src/Resources/SR.resx
  src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemBaseAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemDetailsAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemListAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemTileAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListVIew.ListViewAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Labels: code cleanup

#4988 Fixing ColumnHeader of a MonthCalendar date cell
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarCellAccessibleObject.cs
Labels: waiting-review

#5003 spelling: accessible
  src/System.Windows.Forms/tests/InteropTests/AccessibleObjectTests.cs
Labels: code cleanup

#5007 Spelling src system.windows.forms tests integration tests design surface demo console
  src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.cs
Labels: code cleanup

#4994 Enable nullability in BindingCompleteEventArgs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/BindingCompleteEventArgs.cs
Labels: area: NRT
