Repository dotnet/winforms, pull requests merged in 2021-10, with the labels that each got.

#5887 Fix incorrect ToggleState of DataGridViewCheckBoxCellAO class
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCheckBoxCell.DataGridViewCheckBoxCellAccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCheckBoxCellAccessibleObjectTests.cs
Labels: ready-to-merge

#5436 Adding `IsAccessibilityObjectCreated` checks to event handlers
  src/System.Windows.Forms/src/System/Windows/Forms/Button.cs
  src/System.Windows.Forms/src/System/Windows/Forms/CheckBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildNativeWindow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCheckBoxCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxEditingControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxEditingControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Label.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewTextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/RadioButton.cs
  src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripStatusLabel.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownEdit.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewComboBoxEditingControlAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTextBoxEditingControl.DataGridViewTextBoxEditingControlAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Labels: waiting-review, ready-to-merge

#5889 Fix toggle state of data grid view check box cell ao class - port 6.0
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCheckBoxCell.DataGridViewCheckBoxCellAccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCheckBoxCellAccessibleObjectTests.cs
Labels: servicing-approved

#5909 Use "ArgumentNullException.ThrowIfNull" to check for null (System.Windows.Forms.Primitives)
  src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.PictureWrapper.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Automation/UiaTextRange.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/ArgumentValidation.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/PaddingConverter.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/RefCountedCache.cs
  src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/Internals/ArgumentValidationTests.cs
Labels: hacktoberfest-accepted

#5907 Enable nullability in DataGridViewCellCancelEventArgs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellCancelEventArgs.cs
Labels: area: NRT, hacktoberfest-accepted

#5905 Enable nullability in WebBrowserNavigatingEventArgs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserNavigatingEventArgs.cs
Labels: area: NRT, hacktoberfest-accepted

#5902 Enable nullability in NodeLabelEditEventArgs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/NodeLabelEditEventArgs.cs
Labels: area: NRT, hacktoberfest-accepted

#5906 Enable nullability in some AxHost classes
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.InvalidActiveXStateException.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.State.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.StateConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.TypeLibraryTimeStampAttribute.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.VBFormat.cs
Labels: area: NRT, hacktoberfest-accepted

#5901 Use 'is not null' in some System.Windows.Forms files
  src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.ControlItem.ControlItemAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.ControlItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.ErrorWindow.ErrorWindowAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.ErrorWindow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.IconRegion.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.cs
  src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/FlatButtonAppearance.cs
  src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.AccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.ControlCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.EnumThreadWindowsCallback.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
  src/System.Windows.Forms/src/System/Windows/Forms/FormCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Formatter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/GroupBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Help.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HelpProvider.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlDocument.HTMLDocumentEvents2.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlDocument.HtmlDocumentShim.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlDocument.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlElement.HTMLElementEvents2.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlElement.HtmlElementShim.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlElement.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlElementCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlElementEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlHistory.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlShim.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlShimManager.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlWindow.HTMLWindowEvents2.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlWindow.HtmlWindowShim.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlWindow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlWindowCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ImageIndexConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ImageKeyConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ImageList.ImageCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ImageList.Indexer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ImageListStreamer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
  src/System.Windows.Forms/src/System/Windows/Forms/InputLanguageCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Internal/DrawingEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Internal/Gdi/FontCache.Data.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Internal/Gdi/GdiCache.cs
Labels: hacktoberfest-accepted

#5900 Enable nullability in ListViewItemMouseHoverEventArgs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItemMouseHoverEventArgs.cs
Labels: area: NRT, hacktoberfest-accepted

#5904 Enable nullability in CachedItemHdcInfo
  src/System.Windows.Forms/src/System/Windows/Forms/CachedItemHdcInfo.cs
Labels: area: NRT, hacktoberfest-accepted

#5890 Filling empty test files for missing ao (part 5)
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewButtonCellAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCheckBoxCellAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewImageCellAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewLinkCellAccessibleObjectTests.cs
Labels: waiting-review, ready-to-merge

#5869 Fixed getting an month index of a bolded date of a MonthCalendar
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Calendar.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs
Labels: :octocat: automerge, ready-to-merge, TestingDelayed

#5842 Fixing switching focus between ToolStrips where TabStop=true with Shift-Tab
  src/System.Windows.Forms/src/Resources/SR.resx
  src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
Labels: :octocat: automerge, ready-to-merge, TestingDelayed

#5898 Enable nullability in ColumnReorderedEventArgs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ColumnReorderedEventArgs.cs
Labels: area: NRT, hacktoberfest-accepted

#5908 Use generic list in ImageCollection
  src/System.Windows.Forms/src/System/Windows/Forms/ImageList.ImageCollection.cs
Labels: hacktoberfest-accepted

#5923 Remove 'using' from DrawItemEventArgs_TestData
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControlTests.cs
Labels: test-bug
