Repository dotnet/winforms, pull requests merged in 2021-07, with the labels that each got.

#5176 Reworking `Flags` to `_flags` in GridEntry
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MultiSelectRootGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/SingleSelectRootGridEntry.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridTests.cs
Labels: waiting-review

#5172 Added tooltip to the interactive control test
  src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Buttons.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Buttons.cs
Labels: :octocat: automerge

#5192 Wrong `LabelEditEventArgs.Label` parameters when cancel editing in ListView (port to 5.0)
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
Labels: servicing-approved

#5107 Fix NullRefException for case when user closes Form with hidden PropertyGrid (port to 3.1)
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
  src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/PropertyGridViewAccessibleObjectTests.cs
Labels: servicing-approved

#5094 Fix ListViewGroup rendering (servicing)
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.cs
Labels: servicing-approved

#5103 Fix NullRefException for case when user closes Form with hidden PropertyGrid (port to 5.0)
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
  src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/PropertyGridViewAccessibleObjectTests.cs
Labels: servicing-approved

#5214 Fixing wrong color for label in high contrast mode (port to 3.1)
  src/System.Windows.Forms/src/System/Windows/Forms/Label.cs
Labels: servicing-approved

#5215 Fixing wrong color for label in high contrast mode (port to 5.0)
  src/System.Windows.Forms/src/System/Windows/Forms/Label.cs
Labels: servicing-approved

#5203 Rework casting IntPtr by using ParamToInt
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlCommandSet.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Application.ComponentManager.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ColumnHeader.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.Ime.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Cursor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxEditingControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/FontDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
  src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewNativeItemCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MaskedTextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/NotifyIcon.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Screen.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SplitContainer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDown.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.ModalMenuFilter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripMenuItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
  src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/MonthCalendar.MonthCalendarChildAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComponentModel/Com2Interop/COM2PictureConverterTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTextBoxEditingControlTests.cs
Labels: :octocat: automerge

#5044 Adding UIA support for ScrollBar
  Winforms.sln
  src/System.Windows.Forms/src/Properties/AssemblyInfo.cs
  src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/HScrollBar.HScrollBarAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HScrollBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollBar.ScrollBarAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollBar.ScrollBarChildAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollBar.ScrollBarFirstLineButtonAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollBar.ScrollBarFirstPageButtonAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollBar.ScrollBarLastLineButtonAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollBar.ScrollBarLastPageButtonAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollBar.ScrollBarThumbAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.TrackBarFirstButtonAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.TrackBarLastButtonAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/VScrollBar.VScrollBarAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/VScrollBar.cs
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiScrollBarTests/MauiHScrollBarTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiScrollBarTests/MauiScrollBarTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiScrollBarTests/MauiScrollBarTests.csproj
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiScrollBarTests/MauiVScrollBarTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/MainFormControlsTabOrder.cs
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.Maui.IntegrationTests/System.Windows.Forms.Maui.IntegrationTests.csproj
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.Maui.IntegrationTests/WinformsMauiScrollBarTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ScrollBars.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ScrollBars.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ScrollBars.resx
  src/System.Windows.Forms/tests/TestUtilities/ScrollBarTestHelper.cs
  src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/HScrollBar.HScrollBarAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/HScrollBar.ScrollBarFirstLineButtonAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/HScrollBar.ScrollBarFirstPageButtonAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/HScrollBar.ScrollBarLastLineButtonAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/HScrollBar.ScrollBarLastPageButtonAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/HScrollBar.ScrollBarThumbAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/ScrollBar.ScrollBarAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/TrackBar.TrackBarFirstButtonAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/TrackBar.TrackBarLastButtonAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/VScrollBar.ScrollBarFirstLineButtonAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/VScrollBar.ScrollBarFirstPageButtonAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/VScrollBar.ScrollBarLastLineButtonAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/VScrollBar.ScrollBarLastPageButtonAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/VScrollBar.ScrollBarThumbAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/VScrollBar.VScrollBarAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/HScrollBar.HScrollBarAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/VScrollBar.VScrollBarAccessibleObjectTests.cs
Labels: ready-to-merge

#5206 Implementing invoke action of UpDownButton
  src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.UpDownButtonsAccessibleObject.DirectionButtonAccessibleObject.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MultipleControls.Designer.cs
  src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/DirectionButtonAccessibleObjectTests.cs
Labels: waiting-review

#3705 Add HighDpiMode property/ApplyHighDpiMode Event to WindowsFormsApplicationBase.
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/ApplicationEvents.vb
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/My Project/Application.Designer.HighDpi.vb
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/My Project/Application.Designer.vb
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/Program.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/ApplyApplicationDefaultsEventArgs.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/WindowsFormsApplicationBase.vb
  src/Microsoft.VisualBasic.Forms/src/PublicAPI.Unshipped.txt
  src/System.Windows.Forms/tests/IntegrationTests/VisualBasicTemplate/VbWinForms.sln
Labels: area: Visual Basic, tenet-compatibility

#5289 Fixing freezing ListView in virtual mode when Accessibility Tool is active
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemBaseAccessibleObject.cs
Labels: ready-to-merge

#5232 Adding "IsAccessibilityObjectCreated" property
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ObjectCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Combobox.ObjectCollectionTests.cs
Labels: ready-to-merge

#5216 Resolving "The LocalizedControlType of ImageAlign/TextAlign/Anchor/Dock property is inconsistent in Inspect" for Anchor property
  src/System.Windows.Forms.Design/src/Resources/SR.resx
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/AnchorEditor.cs
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/AnchorEditorTests.cs
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ContentAlignmentEditorTests.cs
Labels: ready-to-merge

#5242 Fixing color contrast for CheckedListBox
  src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs
Labels: ready-to-merge

#5333 Fixing freezing ListView in virtual mode when Accessibility Tool is active (port to 5.0)
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObject.cs
Labels: servicing-approved
