Repository dotnet/winforms, pull requests merged in 2021-11, with the labels that each got.

#6092 Ignoring MauiMonthCalendarTests for "SelectedDate" event
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiMonthCalendarTests/MauiMonthCalendarTests.cs
Labels: test-bug

#6055 Fix disabled ToolStripItem selected bits when ToolStrip fires MouseLeave
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
Labels: hacktoberfest-accepted, ready-to-merge

#6087 Enable nullability in CreateParams
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/CreateParams.cs
Labels: ready-to-merge

#6088 Enable nullability in ToolStripItemClickedEventArgs and ToolStripItemEventArgs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItemClickedEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItemEventArgs.cs
Labels: :octocat: automerge, area: NRT

#6104 Servicing branding.
  eng/Versions.props
Labels: ready-to-merge

#6107 Enable nullability in ColumnHeader
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ColumnHeader.ColumnHeaderImageListIndexer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ColumnHeader.cs
Labels: :octocat: automerge, area: NRT

#6086 Use 'is not null' in some System.Windows.Forms.Design files
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/BasicDesignerLoader.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomDesignerLoader.ModifierConverter.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomDesignerLoader.ModifiersExtenderProvider.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomDesignerLoader.ModifiersInheritedExtenderProvider.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomDesignerLoader.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomLocalizationProvider.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializationProvider.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializerBase.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeMethodMap.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CollectionCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ComponentCache.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ComponentCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ContainerCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/DesignerSerializationManager.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/EnumCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/EventMemberCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ExpressionTable.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/LocalizationCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/PropertyMemberCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ResourceCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ResourcePropertyMemberCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/StatementContext.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/TypeCodeDomSerializer.cs
Labels: code cleanup, :octocat: automerge

#6112 Use 'is not null' in some System.Windows.Forms files
  src/System.Windows.Forms/src/System/Windows/Forms/AutomationMessages.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.Annotated.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.PageSelector.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorPage.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DrawListViewItemEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DropTarget.cs
  src/System.Windows.Forms/src/System/Windows/Forms/KeyboardToolTipStateMachine.cs
  src/System.Windows.Forms/src/System/Windows/Forms/KeysConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Layout/CommonProperties.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Layout/DockAndAnchorLayout.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Layout/FlowLayout.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Layout/LayoutTransaction.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Layout/LayoutUtils.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.ContainerInfo.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MessageBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Printing/PageSetupDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintControllerWithStatusDialog.BackgroundThread.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintControllerWithStatusDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs
  src/System.Windows.Forms/src/misc/MultitargetUtil.cs
  src/System.Windows.Forms/src/misc/WeakHashtable.cs
Labels: :octocat: automerge, area: NRT

#6077 Add a comment with a link to docs
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/net6.0/Program.cs
Labels: area: templates

#6115 (Servicing) Resume invocation of OnParentHandleRecreated for child control when form recreates handle
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs
Labels: servicing-approved

#6113 Resume invocation of OnParentHandleRecreated for child control when form recreates handle
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs
Labels: :mailbox_with_mail: waiting-for-testing

#6122 Fix anchored controls mis-alignment when DPI of the display is higher than 100%
  src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Layout/DockAndAnchorLayout.cs
Labels: :mailbox_with_mail: waiting-for-testing, area: HDPI

#6134 Enable nullability in ToolStripItemTextRenderEventArgs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItemTextRenderEventArgs.cs
Labels: area: NRT

#6106 Enable nullability in CheckBox adapters
  src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/CheckBoxBaseAdapter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/CheckBoxFlatAdapter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/CheckBoxPopupAdapter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/CheckBoxStandardAdapter.cs
Labels: area: NRT

#6073 Fixing Color contrast for DataGridViewLinkCell when it is selected
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewLinkCell.cs
Labels: tenet-accessibility, ready-to-merge

#6110 Enable loc on servicing branch.
  azure-pipelines.yml
Labels: :no_entry_sign: * NO-MERGE *

#6140 [6.0][Servicing]Fix anchored controls mis-alignment when DPI of the display is higher than 100%
  src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Layout/DockAndAnchorLayout.cs
Labels: servicing-approved

#6109 [6.0][Servicing]Update template to include *.user file while creating new applications
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/.template.config/template.json
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-CSharp/.template.config/template.json
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-CSharp/.template.config/template.json
Labels: servicing-approved

#6078 Add a comment with a link to docs
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/net6.0/Program.cs
Labels: area: templates, servicing-approved

#6114 (Servicing) Resume invocation of OnParentHandleRecreated for child control when form recreates handle
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs
Labels: servicing-approved

#6133 Enable nullability in ScrollBarRenderer
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollBarRenderer.cs
Labels: area: NRT

#6161 Fix some comments
  src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs
Labels: :books: documentation, :octocat: automerge

#6158 [6.0][Servicing] Fix nested container controls scaling that have AutoscaleMode as Inherit
  src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
Labels: servicing-approved

#6102 Fixing no focus border on the empty DGV in the Narrator
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.AccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewAccessibleObjectTests.cs
Labels: waiting-review, ready-to-merge

#6171 (Servicing) Emit font in app bootstrap locale agnostic
  eng/Versions.props
  src/System.Windows.Forms.Analyzers.CSharp/src/System/Windows/Forms/Generators/ProjectFileReader.FontConverter.cs
  src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilderTests.GenerateInitialize_DefaultFont=SansSerif.verified.txt
  src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilderTests.cs
  src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ProjectFileReaderTests.FontConverter.cs
  src/System.Windows.Forms.Analyzers/src/System/Windows/Forms/ApplicationConfig.FontDescriptor.cs
  src/System.Windows.Forms.Analyzers/tests/UnitTests/System/Windows/Forms/Analyzers/ApplicationConfigTests.FontDescriptor.cs
Labels: servicing-approved

#6111 Enable nullability in some Indexer classes
  src/System.Windows.Forms/src/System/Windows/Forms/Label.LabelImageIndexer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.ToolStripItemImageIndexer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeImageIndexer.cs
Labels: area: NRT

#6138 Adding a new localized control type for category of property grid
  src/System.Windows.Forms/src/Resources/SR.resx
  src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/CategoryGridEntry.CategoryGridEntryAccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CategoryGridEntryAccessibleObjectTests.cs
Labels: waiting-review

#6198 Fixing scaling issue on explicitly set Font containers but Inherit AutoScaleMode
  src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
Labels: area: HDPI

#6188 Adding prevention of label editing when clicking on subitems of ListView
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Labels: waiting-review

#5976 Fixing too large up and down arrows at ToolStripScrollButton
  src/System.Windows.Forms.Primitives/src/Properties/AssemblyInfo.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/DpiHelper.cs
  src/System.Windows.Forms/src/Properties/AssemblyInfo.cs
  src/System.Windows.Forms/src/Resources/System/Windows/Forms/ToolStrip/ScrollButtonDown.ico
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripScrollButton.cs
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiToolStripTests/MauiToolStripDropDownTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiToolStripTests/MauiToolStripTests.csproj
Labels: ready-to-merge

#6091 Rewrite MAUI tests
  Winforms.sln
  eng/Versions.props
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.SPI.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.SystemParametersInfoW.cs
  src/System.Windows.Forms.Primitives/src/Properties/AssemblyInfo.cs
  src/System.Windows.Forms/src/Properties/AssemblyInfo.cs
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiButtonTests/MauiButtonTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiButtonTests/MauiButtonTests.csproj
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiMonthCalendarTests/MauiMonthCalendarTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiMonthCalendarTests/MauiMonthCalendarTests.csproj
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiTabControlTests/MauiTabControlTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiTabControlTests/MauiTabControlTests.csproj
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests/WinformsControlsTest.cs
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.Maui.IntegrationTests/MauiDataAttribute.cs
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.Maui.IntegrationTests/System.Windows.Forms.Maui.IntegrationTests.csproj
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.Maui.IntegrationTests/WinformsMauiButtonTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.Maui.IntegrationTests/WinformsMauiMonthCalendarTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.Maui.IntegrationTests/WinformsMauiTabControlTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ButtonTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Directory.Build.props
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/DenyExecutionSynchronizationContext.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/SendInput.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/MonthCalendarAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/MonthCalendarTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/System.Windows.Forms.UI.IntegrationTests.csproj
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/TabControlTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/xunit.runner.json
Labels: test-enhancement
