Repository dotnet/winforms, pull requests merged in 2021-09, with the labels that each got.

#5403 Hide keyboard tooltip on form move or resize
  src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/KeyboardToolTipStateMachine.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ContainerControlTests.cs
Labels: ready-to-merge

#5435 Removing redundant runtime id overrides
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollBar.ScrollBarAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.TrackBarAccessibleObject.cs
Labels: ready-to-merge

#5658 Add support UIA provider for CheckedListBox control (#5276 port 6.0)
  src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.CheckedListBoxAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.CheckedListBoxItemAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.AccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.ItemAccessibleObject.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListViewTest.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MultipleControls.Designer.cs
  src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/CheckedListBoxAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/CheckedListBoxItemAccessibleObjectTests.cs
Labels: waiting-review

#5574 Fix the behavior of the Narrator rectangle for TabControl
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPage.TabAccessibleObjectTests.cs
Labels: a11yMAS

#5667 GridEntry cleanup
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/GridItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/IRootGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/ImmutablePropertyDescriptorGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MultiPropertyDescriptorGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MultiSelectRootGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/SingleSelectRootGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleElement.cs
  src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridTests.cs
Labels: ready-to-merge

#5608 Checking if DataGridView handle is created for ToolTip (port to 6.0-rc2)
  Winforms.sln
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.ToolTip.cs
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiDataGridViewTests/MauiDataGridViewTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiDataGridViewTests/MauiDataGridViewTests.csproj
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.Maui.IntegrationTests/System.Windows.Forms.Maui.IntegrationTests.csproj
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.Maui.IntegrationTests/WinformsMauiDataGridViewTests.cs
Labels: ready-to-merge

#5422 Support Windows11-style default tooltip behavior.
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/OsVersion.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/MainFormControlsTabOrder.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Buttons.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ToolTipTests.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ToolTipTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ToolTipTests.resx
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolTipTests.cs
Labels: a11yMAS, :book: documentation: breaking

#5485 Adding UIA support for Panel
  src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Panel.PanelAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Panel.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Panel.PanelAccessibleObjectTests.cs
Labels: ready-to-merge

#5618 Fixing ToolStripButton high contrast issue
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSystemRenderer.cs
Labels: a11yMAS, ready-to-merge

#5674 Fixing ToolStripButton high contrast issue (port to 6.0)
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSystemRenderer.cs
Labels: ready-to-merge

#5686 Support Windows11-style default tooltip behavior (port to 6.0)
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/OsVersion.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/MainFormControlsTabOrder.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Buttons.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ToolTipTests.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ToolTipTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ToolTipTests.resx
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolTipTests.cs
Labels: a11yMAS, :book: documentation: breaking

#5557 Fixing scaling issue with initializing Form on non-primary monitor with different DPI settings.
  src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
Labels: :mailbox_with_mail: waiting-for-testing, ready-to-merge

#5614 Fixing `ToolStrip` button background rendering in HC theme
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripHighContrastRenderer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSystemRenderer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ToolStripTests.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ToolStripTests.cs
Labels: a11yMAS

#5700 Issue 5670 tool strip buttons rendering tests
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripButtonTests.Rendering.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripButtonTests.cs
Labels: :octocat: automerge, ready-to-merge

#5705 Fix getting value for "ControlAccessibleObject.AccessKey" property
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.Link.LinkAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.LinkLabelAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabControlAccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Control.ControlAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridTests.cs
Labels: waiting-review, ready-to-merge

#5723 Adding exception when user tries to add group to ListView in virtual mode (port to 6.0)
  src/System.Windows.Forms/src/Resources/SR.resx
  src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroupCollection.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListViewTest.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MultipleControls.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListVIew.ListViewAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroupCollectionTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Labels: :book: documentation: breaking

#5724 Fixing EditTextBox AO position in the PropertyGrid tree
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewTextBox.GridViewTextBoxAccessibleObjectTests.cs
Labels: ready-to-merge

#5725 Fixing EditTextBox AO position in the PropertyGrid tree (port 6.0)
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewEdit.GridViewEditAccessibleObjectTests.cs
Labels: waiting-review, ready-to-merge

#5726 Fixing ToolStrip Shift+Tab: now focus turns counter-clockwise
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
Labels: ready-to-merge

#5751 Fixing ToolStrip Shift+Tab: now focus turns counter-clockwise (merge to 7.0)
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
Labels: ready-to-merge

#5748 Moving units tests from AccessibleObjects folder
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CheckedListBoxAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DirectionButtonAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DomainUpDownAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProviderAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/GroupBoxAccessibleObjectTests.cs
Labels: waiting-review

#5424 Support Win11 accessibility features in tooltips displayed by keyboard focus
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/KeyboardToolTipStateMachine.SmEvent.cs
  src/System.Windows.Forms/src/System/Windows/Forms/KeyboardToolTipStateMachine.SmState.cs
  src/System.Windows.Forms/src/System/Windows/Forms/KeyboardToolTipStateMachine.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ToolTipTests.Designer.cs
  src/System.Windows.Forms/tests/TestUtilities/CommonTestHelperEx.cs
  src/System.Windows.Forms/tests/UnitTests/KeyboardTooltipStateMachineTests.cs
  src/System.Windows.Forms/tests/UnitTests/OsVersionTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ButtonBaseTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/SplitterTests.cs
Labels: a11yMAS, :book: documentation: breaking

#5763 Filling empty test files
  src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainItemListAccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DomainUpDown.DomainItemAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DomainUpDown.DomainItemListAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemListAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemTileAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollBar.ScrollBarChildAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TrackBar.TrackBarChildAccessibleObjectTests.cs
Labels: waiting-review

#5762 Fixing behavior of ListViewSubItem.Bounds when FullRowSelect = true
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObjectTests.cs
Labels: waiting-review

#5785 Update intellisense
  eng/Versions.props
Labels: servicing-approved

#5775 Filling empty test files for missing ao (part 2)
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CategoryGridEntryAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ChildAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridView.GridViewListBoxItemAccessibleObjectTests.cs
Labels: waiting-review, ready-to-merge

#5797 Updating NativeHost.PlatformToolset version
  WinForms.vsconfig
  docs/developer-guide.md
  src/System.Windows.Forms/tests/IntegrationTests/NativeHost/NativeHost.vcxproj
Labels: ready-to-merge

#5848 Update template to include *.user file while creating new applications.
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/.template.config/template.json
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-CSharp/.template.config/template.json
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-CSharp/.template.config/template.json
Labels: servicing-approved

#5404 Removing InternalAccessibleObject from the code
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildNativeWindow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxUiaTextProvider.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.ErrorWindow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/InternalAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseUiaTextProvider.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxUiaTextProviderTests.cs
Labels: :mailbox_with_mail: waiting-for-testing, ready-to-merge

#5873 Addendum to #5859
  src/System.Windows.Forms/tests/TestUtilities/ThreadExceptionFixture.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripSettingsManagerTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/UserConfigDisposableFixture.cs
Labels: test-enhancement

#5534 Fixing focus rectangle width for controls with vertical scrollbar
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetWindowRect.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildListUiaProvider.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxChildListUiaProviderTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListVIew.ListViewAccessibleObjectTests.cs
Labels: waiting-review, ready-to-merge

#5864 Filling empty test files for missing ao (part 3)
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewColumnHeaderCellAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewRowHeaderCellAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewSelectedCellsAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewSelectedRowCellsAccessibleObjectTests.cs
Labels: ready-to-merge

#5868 Fixing missing control type for custom `DataGridViewCell`s
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.DataGridViewCellAccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellAccessibleObjectTests.cs
Labels: ready-to-merge, TestingDelayed

#5880 Fixed getting an month index of a bolded date of a MonthCalendar (port 6.0)
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
Labels: servicing-approved
