Repository dotnet/winforms, pull requests merged in 2021-02, with the labels that each got.

#4525 Properly apply translation and clipping in TextRenderer
  src/System.Windows.Forms.Primitives/src/Interop/Gdi32/Interop.HENHMETAFILE.cs
  src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/EmfScope.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextRenderer.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TextRendererTests.cs
Labels: :boom: regression, servicing-approved

#4577 Move sub-classes of "ToolStrip", "ToolStripContainer" and "ToolStripDropDown" classes to their own files
  src/System.Windows.Forms/src/System/Windows/Forms/CachedItemHdcInfo.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MouseHoverTimer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.RestoreFocusMessageFilter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.ToolStripAccessibleObjectWrapperForItemsOnOverflow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripContainer.ToolStripContainerTypedControlCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripContainer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDown.ToolStripDropDownAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDown.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSplitStackDragDropHandler.RelativeLocation.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSplitStackDragDropHandler.cs
Labels: code cleanup

#4588 Enable nullability in TreeViewHitTestInfo
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/TreeViewHitTestInfo.cs
Labels: area: NRT
