Repository dotnet/winforms, pull requests merged in 2021-08, with the labels that each got.

#4995 Enable nullability in DataGridViewColumn EventArgs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnDividerDoubleClickEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnStateChangedEventArgs.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewColumnStateChangedEventArgsTests.cs
Labels: :book: documentation: breaking, area: NRT

#5157 Implementing LinkLabel support UIA provider
  src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.Link.LinkAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.Link.cs
  src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.LinkAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.LinkLabelAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MultipleControls.Designer.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/LinkLabel.Link.LinkAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/LinkLabel.LinkLabelAccessibleObjectTests.cs
Labels: waiting-review

#4685 Fix inversion of conditional
  Winforms.sln
  src/System.Windows.Forms.Primitives/src/Properties/AssemblyInfo.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/tests/IntegrationTests/NativeHost.ManagedControl/ManagedControl.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/NativeHost.ManagedControl/ManagedControl.cs
  src/System.Windows.Forms/tests/IntegrationTests/NativeHost.ManagedControl/ManagedControl.resx
  src/System.Windows.Forms/tests/IntegrationTests/NativeHost.ManagedControl/NativeHost.ManagedControl.csproj
  src/System.Windows.Forms/tests/IntegrationTests/NativeHost/NativeHost.IgnoreBuild.targets
  src/System.Windows.Forms/tests/IntegrationTests/NativeHost/NativeHost.cpp
  src/System.Windows.Forms/tests/IntegrationTests/NativeHost/NativeHost.vcxproj
  src/System.Windows.Forms/tests/IntegrationTests/NativeHost/NativeHost.vcxproj.filters
  src/System.Windows.Forms/tests/IntegrationTests/NativeHost/app.manifest
  src/System.Windows.Forms/tests/IntegrationTests/NativeHost/pch.cpp
  src/System.Windows.Forms/tests/IntegrationTests/NativeHost/pch.h
  src/System.Windows.Forms/tests/IntegrationTests/NativeHost/readme.md
Labels: :boom: regression, area: COM

#5417 Fixing the issue with getting a ListBox.ItemAccessibleObject.Role (port to .NET Core 5.0)
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.ItemAccessibleObject.cs
Labels: servicing-consider

#5245 Adding support expand-collapse pattern for DateTimePicker
  src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.DateTimePickerAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DateTimePicker.DateTimePickerAccessibleObjectTests.cs
Labels: waiting-review, ready-to-merge

#5380 Fix UIA navigation for TabControl
  src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabControlAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabPage.TabAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabPage.TabPageAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControl.TabControlAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPage.TabAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPage.TabPageAccessibleObjectTests.cs
Labels: :mailbox_with_mail: waiting-for-testing
