Repository dotnet/winforms, pull requests merged in 2022-03, with the labels that each got.

#6762 Fixing a JAWS exception in a PropertyGrid (port to 6.0)
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewEdit.GridViewEditAccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewEdit.GridViewEditAccessibleObjectTests.cs
Labels: servicing-approved

#6774 Enable nullability in ImageList
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ImageList.ImageCollection.ImageInfo.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ImageList.ImageCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ImageList.Original.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs
Labels: area: NRT

#6787 Enable nullability in NumericUpDownAccessibleObject
  src/System.Windows.Forms/src/System/Windows/Forms/NumericUpDown.NumericUpDownAccessibleObject.cs
Labels: area: NRT

#6751 Do not retreive shell items via built-in COM
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SHCreateItemFromParsingName.cs
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SHCreateShellItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
Labels: :octocat: automerge

#6788 Enable nullability in PropertyDescriptorGridEntryAccessibleObject
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.PropertyGridViewAccessibleObject.cs
Labels: :octocat: automerge, area: NRT

#6801 Enable nullability in TrackBar
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.cs
Labels: area: NRT

#6800 Enable nullability in UpDownButtons
  src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.cs
Labels: :octocat: automerge, area: NRT

#6792 Enable nullability in AutoCompleteDropDownFinder
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.AutoCompleteDropDownFinder.cs
Labels: area: NRT

#6790 Enable nullability in PropertyGridAccessibleObject
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxEditingControl.DataGridViewTextBoxEditingControlAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.PropertyGridAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/CommandsPane.CommandsPaneAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/DetailsButton.DetailsButtonAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/HelpPane.HelpPaneAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.PropertyGridViewAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridToolStrip.PropertyGridToolStripAccessibleObject.cs
Labels: area: NRT

#6799 Enable nullability in Form.ControlCollection
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Form.ControlCollection.cs
Labels: area: NRT

#6791 Enable nullability in PrintPreviewControl
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewControl.cs
Labels: area: NRT

#6806 Remove Image null check before calling ImageAnimator.UpdateFrames
  src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Label.cs
Labels: ready-to-merge

#6752 Fixing layout issues of Anchored/Docked controls in the MDI child forms
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
Labels: area: MDI, area: HDPI PMv2

#6432 Implementing support UIA Provider for TreeView control
  src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeView.TreeViewAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNode.TreeNodeAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeView.TreeViewAccessibleObjectTests.cs
Labels: ready-to-merge

#6384 Enable nullability in some COM2 handlers
  src/System.Windows.Forms.Primitives/src/Interop/VSSDK/Interop.IVsPerPropertyBrowsing.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2ExtendedBrowsingHandler.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2ICategorizePropertiesHandler.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IManagedPerPropertyBrowsingHandler.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IPerPropertyBrowsingHandler.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IProvidePropertyBuilderHandler.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IVsPerPropertyBrowsingHandler.cs
Labels: area: NRT

#6819 Enable nullability in DateTimePickerAccessibleObject
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.DateTimePickerAccessibleObject.cs
Labels: :octocat: automerge, area: NRT

#6803 Enable nullability in PrintControllerWithStatusDialog
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintControllerWithStatusDialog.BackgroundThread.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintControllerWithStatusDialog.StatusDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintControllerWithStatusDialog.cs
Labels: area: NRT

#6802 Enable additional C/C++ compiler warnings
  src/System.Windows.Forms/tests/IntegrationTests/NativeHost/NativeHost.vcxproj
  src/System.Windows.Forms/tests/InteropTests/NativeTests/CMakeLists.txt
Labels: compliance

#6563 Fix ListViewGroupAccessibleObject.GetNativeGroupId returning incorrect value
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObjectTests.cs
Labels: waiting-on-team

#6839 Enable nullability in PrintPreviewDialog
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewDialog.cs
Labels: area: NRT

#6837 Enable nullability in some COM2 converters
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2ColorConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2DataTypeToManagedDataTypeConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2FontConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PictureConverter.cs
Labels: area: NRT

#6861 Update intellisense
  eng/Versions.props
Labels: :octocat: automerge

#6822 Enable nullability in Form
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Form.ControlCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
Labels: area: NRT

#6862 Pedantically construct paths for XML files
  eng/packageContent.targets
Labels: :octocat: automerge

#6867 Remove publishing TRX files from public CI
  eng/pipelines/post-build.yml
Labels: :octocat: automerge

#6879 Enable nullability in ConnectionPointCookie
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.ConnectionPointCookie.cs
Labels: :octocat: automerge, area: NRT

#6880 Enable nullability in DataGridViewComboBoxEditingControlAccessibleObject
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxEditingControl.DataGridViewComboBoxEditingControlAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripComboBox.ToolStripComboBoxControl.ToolStripComboBoxControlAccessibleObject.cs
Labels: :octocat: automerge, area: NRT

#6836 Enable nullability in ListViewSubItem
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItemCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewSubItemConverter.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ListViewTests.cs
Labels: ready-to-merge

#6873 Enable nullability in CheckedListBox
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.cs
  src/System.Windows.Forms/tests/UnitTests/CheckedListBoxTests.cs
Labels: area: NRT

#6872 Enable nullability in TextBox
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/TextBox.cs
Labels: area: NRT

#6866 Remove not used interfaces
  src/System.Windows.Forms.Primitives/src/Interop/Mshtml/Interop.IHTMLScreen.cs
  src/System.Windows.Forms.Primitives/src/Interop/Mshtml/Interop.IHTMLWindow2.cs
  src/System.Windows.Forms.Primitives/src/Interop/Mshtml/Interop.IOmNavigator.cs
  src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.CoRegisterMallocSpy.cs
  src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.IMallocSpy.cs
  src/System.Windows.Forms.Primitives/tests/TestUtilities/IMallocSpy.cs
  src/System.Windows.Forms.Primitives/tests/TestUtilities/MallocSpy.cs
  src/System.Windows.Forms.Primitives/tests/TestUtilities/MallocSpyScope.MasterSpy.cs
  src/System.Windows.Forms.Primitives/tests/TestUtilities/MallocSpyScope.cs
Labels: code cleanup, :octocat: automerge

#6870 Enable nullability in FontDialog
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/FontDialog.cs
Labels: area: NRT

#6883 Update troubleshooting.md
  docs/designer/troubleshooting.md
Labels: :books: documentation

#6891 Add release activities doc
  docs/release-activity.md
Labels: :books: documentation

#6913 Move ToolStripOverflowAccessibleObject to a separate file and enable nullability to it
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripOverflow.ToolStripOverflowAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripOverflow.cs
Labels: code cleanup, area: NRT

#6912 Move SpecialFolderEnumConverter to a separate file
  src/System.Windows.Forms/src/System/Windows/Forms/SpecialFolderEnumConverter.SpecialFolderEnumComparer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SpecialFolderEnumConverter.cs
Labels: code cleanup

#6892 Enable nullability in MaskedTextBox
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/MaskedTextBox.cs
Labels: area: NRT

#6390 Enable nullability in GroupBoxRenderer
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/GroupBoxRenderer.cs
Labels: area: NRT

#6911 Enable nullability in GridErrorDialog
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridErrorDialog.cs
Labels: area: NRT

#6910 Enable nullability in NumericUpDown
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/NumericUpDown.cs
Labels: area: NRT

#6918 Enable nullability in RadioButton
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/RadioButton.cs
Labels: :octocat: automerge, area: NRT

#6905 Enable nullability in some component editors
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxComponentEditor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2ComponentEditor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Design/WindowsFormsComponentEditor.cs
Labels: area: NRT

#6924 Enable nullability in FlowLayoutPanel
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/FlowLayoutPanel.cs
Labels: area: NRT

#6909 Enable nullability in ListViewGroupCollection and ListViewGroupItemCollection
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroupCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroupItemCollection.cs
Labels: area: NRT, waiting-on-team

#6493 Update ListViewGroup.CollapsedState from native when changed by keyboard
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ListViewTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroupTests.cs
Labels: :octocat: automerge

#6917 Enable nullability in DataGridViewSelectedRowCellsAccessibleObject
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.DataGridViewSelectedRowCellsAccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewSelectedRowCellsAccessibleObjectTests.cs
Labels: area: NRT

#6904 Enable nullability in Splitter
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Splitter.cs
Labels: area: NRT

#6931 Enable nullability in TextBoxBase
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
Labels: area: NRT

#6899 Replace Hashtable with Dictionary<> in AxContainer
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxContainer.cs
Labels: code cleanup, :octocat: automerge

#6932 Enable nullability in IconComparer
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.IconComparer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
Labels: :octocat: automerge, area: NRT

#6746 Create CCW for IDropSource
  src/System.Windows.Forms.Primitives/src/Interop/Interop.IID.cs
  src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.DoDragDrop.cs
  src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.IDropSourceVtbl.cs
  src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
Labels: :octocat: automerge
