Repository dotnet/winforms, pull requests merged in 2022-12, with the labels that each got.

#8255 Refactor `KeysConverter` to remove `ArrayList`
  src/System.Windows.Forms/src/System/Windows/Forms/KeysConverter.cs
Labels: ready-to-merge

#8276 Refactor GetStandardValues implementations to remove ArrayList
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomDesignerLoader.ModifierConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/CursorConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MdiWindowListItemConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SpecialFolderEnumConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextBoxAutoCompleteSourceConverter.cs
Labels: ready-to-merge

#8309 Convert `StubSite` to use Dictionary instead of HashTable and Enable Nullability
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripControlHost.StubSite.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripControlHostTests.cs
Labels: ready-to-merge

#8330 Convert Rest of Com Vtbls to New Pattern
  src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.DoDragDrop.cs
  src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.IDropSource.cs
  src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.IDropSourceNotify.cs
  src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.EnumFORMATETCWrapper.cs
  src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.IDataObjectVtbl.cs
  src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.IDropSourceNotifyVtbl.cs
  src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.IDropSourceVtbl.cs
  src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.IEnumFORMATETCVtbl.cs
  src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
  src/System.Windows.Forms.Primitives/src/Windows/Win32/System/Com/IDataObject.cs
  src/System.Windows.Forms.Primitives/src/Windows/Win32/System/Com/IEnumFORMATETC.cs
  src/System.Windows.Forms.Primitives/src/Windows/Win32/System/Com/STGMEDIUM.cs
  src/System.Windows.Forms.Primitives/src/Windows/Win32/System/Ole/IDropSource.cs
  src/System.Windows.Forms.Primitives/src/Windows/Win32/System/Ole/IDropSourceNotify.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataObject.FormatEnumerator.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DropSource.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
Labels: ready-to-merge

#8331 Enable nullability for TestUtilities Project
  src/Common/tests/TestUtilities/CommonMemberDataAttribute.cs
  src/Common/tests/TestUtilities/CommonTestHelper.cs
  src/Common/tests/TestUtilities/CustomConverter.cs
  src/Common/tests/TestUtilities/ITestAccessor.cs
  src/Common/tests/TestUtilities/ReflectionHelper.cs
  src/Common/tests/TestUtilities/System.Windows.Forms.Common.TestUtilities.csproj
  src/Common/tests/TestUtilities/TempFile.cs
  src/Common/tests/TestUtilities/TestAccessor.cs
  src/Common/tests/TestUtilities/TestAccessors.cs
  src/Common/tests/TestUtilities/XUnit/UseCultureAttribute.cs
Labels: area: NRT

#8329 Adding the ToolStripMenuItem checked state announcement
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripMenuItem.ToolStripMenuItemAccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripMenuItem.ToolStripMenuItemAccessibleObjectTests.cs
Labels: ready-to-merge

#8117 Make image nullable in ImageRectangle property of ToolStripMenuItem
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripMenuItem.ToolStripMenuItemInternalLayout.cs
Labels: area: NRT

#8324 Enable nullability in Application
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
Labels: area: NRT

#8347 Enable nullability in IComPropertyBrowser and ICom2PropertyPageDisplayService
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyPageUITypeConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/ICOM2PropertyPageDisplayService.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/IComPropertyBrowser.cs
Labels: area: NRT

#8367 Fix `Cursor(Stream)` to avoid incomplete reads and possible exception
  src/System.Windows.Forms/src/System/Windows/Forms/Cursor.cs
Labels: ready-to-merge

#8358 Cleanup explicit `EmbeddedResource` items in `System.Windows.Forms.Design.csproj`
  src/System.Windows.Forms.Design/src/Resources/System/WinForms/Design/Behavior/MoverGlyph.ico
  src/System.Windows.Forms.Design/src/Resources/System/WinForms/Design/MoverGlyph.bmp
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/EmbeddedResourceTests.cs
Labels: :octocat: automerge

#8378 Enable nullability in RTLAwareMessageBox
  src/Common/src/RTLAwareMessageBox.cs
Labels: area: NRT

#8380 Enable nullability in MenuCommandsChangedEventArgs
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/MenuCommandsChangedEventArgs.cs
Labels: area: NRT

#8323 Enable nullability in ToolStripPanelCell
  src/System.Windows.Forms/src/System/Windows/Forms/ArrangedElement.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelCell.cs
Labels: area: NRT, ready-to-merge

#8379 Enable nullability in SnapLine
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/SnapLine.cs
Labels: area: NRT, ready-to-merge

#8374 Removed designer-added tags from the project file
  src/System.Windows.Forms/src/System.Windows.Forms.csproj
Labels: ready-to-merge

#8365 Refactor Com2IManagedPerPropertyBrowsingHandler to replace ArrayList with List<Atrribute>
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IManagedPerPropertyBrowsingHandler.cs
Labels: ready-to-merge

#8393 added validation of the resource list for winforms and .Design assemblies
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/EmbeddedResourceTests.cs
  src/System.Windows.Forms.Primitives/tests/TestUtilities/Extensions/AssertExtensions.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/EmbeddedResourceTests.cs
Labels: waiting-review, ready-to-merge

#8394 Enable Nullability on a couple of Interfaces
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/Resources/Tools/ITargetAwareCodeDomProvider.cs
  src/System.Windows.Forms.Design/src/System/Runtime/InteropServices/UCOMITypeLib.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Automation/IAutomationLiveRegion.cs
Labels: ready-to-merge

#8400 Refactor `TabOrder` to enable Nullability and replace `ArrayList`/`HashTable`
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TabOrder.cs
Labels: ready-to-merge

#8060 Avoid excessive memory usage and slow `TrackBar` control
  src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/TrackBars.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/TrackBars.cs
Labels: ready-to-merge

#8418 Enable nullability in BindingNavigator
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/BindingNavigator.cs
Labels: area: NRT

#8426 Enable nullability in MergeHistory
  src/System.Windows.Forms/src/System/Windows/Forms/MergeHistory.cs
Labels: area: NRT

#8428 Enable nullability in HelpProvider
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/HelpProvider.cs
Labels: area: NRT

#8427 Enable nullability in HtmlHistory
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlHistory.cs
Labels: area: NRT
