Repository dotnet/winforms, pull requests merged in 2022-10, with the labels that each got.

#7633 Enable nullability in Com2IPerPropertyBrowsingEnum
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/Com2IPerPropertyBrowsingHandler.Com2IPerPropertyBrowsingEnum.cs
Labels: area: NRT

#7878 Port fix for IDataObject.GetData with non-serializable type returns null
  src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.DoDragDrop.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DragDropTests.cs
Labels: :boom: regression, servicing-approved

#7885 Update branding to 6.0.11
  eng/Versions.props
Labels: :octocat: automerge

#7741 Implementing UIA provider for TextBox and MaskedTextBox controls
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
  src/System.Windows.Forms/src/Resources/SR.resx
  src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxEditingControl.DataGridViewTextBoxEditingControlAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxEditingControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MaskedTextBox.MaskedTextBoxAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MaskedTextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewTextBox.GridViewTextBoxAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewTextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripTextBox.ToolStripTextBoxControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripTextBox.ToolStripTextBoxControlAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownEdit.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ToolStripTests.Designer.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Control.ControlAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MaskedTextBox.MaskedTextBoxAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TextBoxAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TextBoxBaseAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/TextBoxBaseTests.cs
Labels: :mailbox_with_mail: waiting-for-testing

#7886 Use native tools present on the machine rather than bootstraped tools in CI build
  Restore.cmd
  build.cmd
  global.json
Labels: :octocat: automerge

#7888 Enable CA1416
  Directory.Build.targets
  eng/CodeAnalysis.src.globalconfig
  src/System.Windows.Forms.Primitives/src/Interop/NtDll/Interop.RTL_OSVERSIONINFOEX.cs
  src/System.Windows.Forms.Primitives/src/Interop/NtDll/Interop.RtlGetVersion.cs
  src/System.Windows.Forms.Primitives/src/Interop/NtDll/Interop.RtlNtStatusToDosError.cs
  src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/DpiHelper.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/OsVersion.cs
  src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.AreDpiAwarenessContextsEqual.cs
  src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetDpiForWindow.cs
  src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetSystemMetrics.cs
  src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetThreadDpiAwarenessContext.cs
  src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.SetThreadDpiAwarenessContext.cs
  src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.SystemParametersInfo.cs
  src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/NtDll/RtlGetVersionTests.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ColumnHeader.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildNativeWindow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.AccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewLabelEditNativeWindow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarBodyAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarRowAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.MonthCalendarAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.ModalMenuFilter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
  src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/FormTests.cs
  src/System.Windows.Forms/tests/UnitTests/KeyboardTooltipStateMachineTests.cs
  src/System.Windows.Forms/tests/UnitTests/OsVersionTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FormTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolTipTests.cs
Labels: enhancement

#7889 Enabling analyzers that don't cause build failures and fix CA1853
  eng/CodeAnalysis.src.globalconfig
  eng/CodeAnalysis.test.globalconfig
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxContainer.cs
Labels: enhancement

#7915 Update getting-started.md
  docs/getting-started.md
Labels: :books: documentation, :octocat: automerge

#7920 Enable IDE0082 'typeof' can be converted to 'nameof'
  eng/CodeAnalysis.src.globalconfig
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/EventBindingService.EventPropertyDescriptor.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomLocalizationProvider.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ResourceCodeDomSerializer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemBaseAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelRow.ToolStripPanelRowControlCollection.cs
  src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/CustomControls/CustomButtonDesignerActionList.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DesignBehaviorsTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemBaseAccessibleObjectTests.cs
Labels: code cleanup

#7919 Enable IDE0100 Remove redundant equality
  eng/CodeAnalysis.src.globalconfig
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/WindowsFormsApplicationBase.vb
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CollectionCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/TypeCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/Behavior.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DragAssistanceManager.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/ResizeBehavior.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/CommandSet.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ComponentTray.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlCommandSet.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TextBoxBaseDesigner.cs
  src/System.Windows.Forms/src/System/Windows/Forms/BindingSource.cs
  src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Layout/FlowLayout.cs
  src/System.Windows.Forms/src/System/Windows/Forms/NumericUpDown.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.GridEntryAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollableControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Labels: code cleanup

#7917 Enable IDE0170 (simplify property pattern) analyzer and fix occurrences
  eng/CodeAnalysis.src.globalconfig
  src/System.Windows.Forms.Analyzers.CSharp/src/System/Windows/Forms/Generators/ApplicationConfigurationGenerator.cs
  src/System.Windows.Forms.PrivateSourceGenerators/src/System/Windows/Forms/SourceGenerators/SyntaxReceiver.cs
Labels: code cleanup

#7923 Enable IDE0062 Make local function 'static'
  eng/CodeAnalysis.src.globalconfig
  src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/SiteNestedContainerTests.cs
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/Behavior/SnapLineTests.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxUiaTextProvider.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewLabelEditUiaTextProvider.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseUiaTextProvider.cs
  src/System.Windows.Forms/tests/UnitTests/SerializableTypesTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CursorsTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MessageTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PowerStatusTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ProfessionalColorTableTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ProfessionalColorsTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/VisualStyles/VisualStyleElementTests.cs
Labels: enhancement

#7914 Remove duplicate `StatusCommandUI`
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/SelectionService.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/StatusCommandUI.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/StatusCommandUI.cs
Labels: code cleanup

#7746 [release/6.0] Update build images
  Restore.cmd
  azure-pipelines-richnav.yml
  azure-pipelines.yml
  build.cmd
  eng/pipelines/build.yml
  global.json
Labels: :octocat: automerge, area: infra

#7916 Enable IDE0200 (remove unnecessary lambda expression)
  eng/CodeAnalysis.src.globalconfig
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/CollectionEditor.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/CommandSet.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/EventHandlerService.cs
Labels: code cleanup

#7925 Merging internal commits for release/6.0
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  global.json
Labels: area: infra

#7962 SA1518: File is required to end with a single newline character
  eng/CodeAnalysis.src.globalconfig
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/BinaryEditor.BinaryUI.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/BinaryEditor.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/CodeMarkerEvent.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerEventService.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/MenuCommandService.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/MenuCommandsChangedEventArgs.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/MenuCommandsChangedEventHandler.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/BasicDesignerLoader.ReloadOptions.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomDesignerLoader.ModifierConverter.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomDesignerLoader.ModifiersExtenderProvider.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ComponentTypeCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ContainerCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/Drawing/Design/ContentAlignmentEditor.cs
  src/System.Windows.Forms.Design/src/System/Drawing/Design/CursorEditor.CursorUI.cs
  src/System.Windows.Forms.Design/src/System/Drawing/Design/CursorEditor.cs
  src/System.Windows.Forms.Design/src/System/Drawing/Design/FontNameEditor.cs
  src/System.Windows.Forms.Design/src/System/Drawing/Design/ToolboxItem.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ComboBoxDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ContainerSelectorActiveEventHandler.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlCommandSet.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerExtenders.NameExtenderProvider.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerExtenders.NameInheritedExtenderProvider.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerExtenders.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/GroupBoxDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ImageListImageEditor.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/LinkAreaEditor.LinkAreaUI.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/LinkAreaEditor.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ListBoxDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ListControlUnboundActionList.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ListViewActionList.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ListViewDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/PanelDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/PictureBoxActionList.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/PictureBoxDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/RadioButtonDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/RichTextBoxActionList.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/RichTextBoxDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/StringArrayEditor.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/StringCollectionEditor.StringCollectionForm.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/StringCollectionEditor.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripTemplateNode.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/UpDownBaseDesigner.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/WMExtensions.cs
  src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.LoadLibrary.cs
  src/System.Windows.Forms/src/misc/CoreSwitches.cs
  src/System.Windows.Forms/src/misc/ImageListUtils.cs
Labels: code cleanup

#7966 SA1001 Commas should not be preceded by whitespace
  eng/CodeAnalysis.src.globalconfig
  src/System.Windows.Forms.Design/src/System/Resources/Tools/StronglyTypedResourceBuilder.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs
Labels: code cleanup

#7965 SA1028 Code should not contain trailing whitespace
  eng/CodeAnalysis.src.globalconfig
  src/System.Windows.Forms.Design/src/System/Drawing/Design/ContentAlignmentEditor.ContentUI.cs
  src/System.Windows.Forms.Design/src/System/Drawing/Design/SelectionPanelBase.cs
  src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.IEnumFORMATETCVtbl.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/DpiHelper.cs
  src/System.Windows.Forms.Primitives/src/Windows/Win32/Graphics/Gdi/FW.cs
  src/System.Windows.Forms/src/System/Windows/Forms/BindableComponent.cs
  src/System.Windows.Forms/src/System/Windows/Forms/CommonDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.PageSelector.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
  src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.AccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ICommandBindingTargetProvider.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.AccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MaskedTextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SystemInformation.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripControlHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripProgressBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSeparator.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripTextBox.ToolStripTextBoxControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripTextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs
Labels: code cleanup

#7964 SA1212 A get accessor appears after a set accessor within a property …
  eng/CodeAnalysis.src.globalconfig
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
Labels: code cleanup

#7877 Enable nullability in LinkLabel
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.LinkLabelAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.cs
  src/System.Windows.Forms/src/System/Windows/Forms/LinkUtilities.cs
Labels: area: NRT

#7973 Fix top-level window size for non-linear dimensions based on AutoScaleMode
  src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Dpi/DpiMessageHelper.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Dpi/FormTests.Dpi.cs
Labels: :book: documentation: breaking

#8005 Enable nullability in AxPerPropertyBrowsingEnum
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxPerPropertyBrowsingEnum.cs
Labels: area: NRT

#8003 Enable nullability in ToolStripNumericUpDown
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripNumericUpDown.cs
Labels: area: NRT

#8000 Enable nullability in ToolStripLabel
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripLabel.cs
Labels: area: NRT

#8001 Enable nullability in ToolStripButton
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripButton.cs
Labels: area: NRT

#7991 Enable nullability in ComponentManager
  src/System.Windows.Forms/src/System/Windows/Forms/Application.ComponentManager.cs
Labels: area: NRT

#8002 Enable nullability in ToolStripProgressBar
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripProgressBar.cs
Labels: area: NRT

#7993 Enable nullability in MenuStrip
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/MenuStrip.cs
Labels: area: NRT

#7994 Enable nullability in ControlBoxMenuItem and SystemMenuItem
  src/System.Windows.Forms/src/System/Windows/Forms/MdiControlStrip.ControlBoxMenuItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MdiControlStrip.SystemMenuItem.cs
Labels: area: NRT

#7999 Enable nullability in ToolStripTextBox
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripTextBox.cs
Labels: area: NRT

#8008 Enable nullability in ToolStripScrollButton
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripScrollButton.cs
Labels: area: NRT

#8009 Enable nullability in ToolStripOverflowButton
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripOverflowButton.cs
Labels: area: NRT

#8007 Enable nullability in ToolStripStatusLabel
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripStatusLabel.cs
Labels: area: NRT

#7998 Enable nullability in MenuTimer
  src/System.Windows.Forms/src/System/Windows/Forms/MenuTimer.cs
Labels: area: NRT

#8004 Enable nullability in ToolStripDropTargetManager
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DragEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropTargetManager.cs
Labels: area: NRT

#8011 Enable nullability in PropertyGridToolStripButton
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridToolStripButton.cs
Labels: area: NRT

#8010 Enable nullability in ToolStripDropDownButton
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownButton.cs
Labels: area: NRT

#8027 Enable nullability in ToolStripPanelControlCollection
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.ToolStripPanelControlCollection.cs
Labels: area: NRT

#8012 Enable nullability in ToolStripComboBox
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripComboBox.cs
Labels: area: NRT

#8017 Enable nullability in ToolStripOverflow
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripOverflow.cs
Labels: area: NRT

#8026 Enable nullability in ToolStripCustomIComparer
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripCustomIComparer.cs
Labels: area: NRT

#8013 Enable nullability in ToolStripDropDownMenu
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownMenu.cs
Labels: area: NRT

#8016 Enable nullability in ModalMenuFilter
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.ModalMenuFilter.cs
Labels: area: NRT

#7992 Enable nullability in Link class
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.Link.LinkAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.Link.cs
  src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/CommandsPane.cs
Labels: area: NRT

#8031 CA2007 Consider calling ConfigureAwait on the awaited task
  eng/CodeAnalysis.src.globalconfig
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/WindowsFormsApplicationBase.vb
Labels: enhancement

#8042 Enable nullability in ToolStripProgressBarControl
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripProgressBar.ToolStripProgressBarControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripProgressBar.ToolStripProgressBarControlAccessibleObject.cs
Labels: area: NRT

#8041 Enable nullability in PropertyGridToolStrip
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridToolStrip.cs
Labels: area: NRT

#8040 Enable nullability in ToolStripSplitButton
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSplitButton.cs
Labels: area: NRT

#8043 Enable nullability in ToolStripSplitStackDragDropHandler
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSplitStackDragDropHandler.cs
Labels: area: NRT

#8044 Enable nullability in ToolStripSplitButtonButton
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSplitButton.ToolStripSplitButtonButton.cs
Labels: area: NRT

#8037 Fixed unit tests for "AccessibleObject.FragmentNavigate" method in ListViewItem-related classes
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemBaseAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemListAccessibleObjectTests.cs
Labels: waiting-review

#7491 Enable nullability in some Control members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MDIClient.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollableControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
Labels: area: NRT, waiting-on-team

#8051 Enable nullability in FeedbackDropDown
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.FeedbackRectangle.FeedbackDropDown.cs
Labels: area: NRT

#8050 Enable nullability in ToolStripComboBoxControl
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripComboBox.ToolStripComboBoxControl.ToolStripComboBoxControlAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripComboBox.ToolStripComboBoxControl.ToolStripComboBoxFlatComboAdapter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripComboBox.ToolStripComboBoxControl.cs
Labels: area: NRT

#8069 Enable nullability in ToolStripPanelRowManager
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelRow.ToolStripPanelRowManager.cs
Labels: area: NRT

#8068 Enable nullability in ToolStripNumericUpDownControl
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripNumericUpDown.ToolStripNumericUpDownControl.ToolStripNumericUpDownAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripNumericUpDown.ToolStripNumericUpDownControl.cs
Labels: area: NRT

#8057 Enable nullability in StatusStrip
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/StatusStrip.cs
Labels: area: NRT

#8056 Enable nullability in MdiWindowListStrip
  src/System.Windows.Forms/src/System/Windows/Forms/MDIWindowDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MdiWindowListStrip.cs
Labels: area: NRT

#8066 Enable nullability in GridToolTip
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridToolTip.cs
Labels: area: NRT

#8064 Enable nullability in MonthCalendar
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
Labels: area: NRT

#8049 Enable nullability in some ToolStripItem members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.ToolStripItemAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
Labels: area: NRT

#8071 Enable nullability in MultiSelectRootGridEntry
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MultiSelectRootGridEntry.cs
Labels: area: NRT

#8073 Enable nullability in MultiPropertyDescriptorGridEntry
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MultiPropertyDescriptorGridEntry.cs
Labels: area: NRT

#8075 Enable nullability in ToolStripContainerTypedControlCollection
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripContainer.ToolStripContainerTypedControlCollection.cs
Labels: area: NRT

#8058 Enable nullability in ToolStripDropDown
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/MenuTimer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDown.cs
Labels: area: NRT

#8079 Enable nullability in HorizontalRowManager
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelRow.HorizontalRowManager.cs
Labels: area: NRT

#8061 Enable nullability in LinkCollection
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.LinkCollection.cs
Labels: area: NRT
