Repository dotnet/winforms, pull requests merged in 2022-01, with the labels that each got.

#6418 Rewrite MAUIScrollBarTests
  Winforms.sln
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiScrollBarTests/MauiHScrollBarTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiScrollBarTests/MauiScrollBarTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiScrollBarTests/MauiScrollBarTests.csproj
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiScrollBarTests/MauiVScrollBarTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollBarTests.cs
Labels: ready-to-merge

#6419 Enable nullability in DisplayedBandsData
  src/System.Windows.Forms/src/System/Windows/Forms/Datagridview.DisplayedBandsData.cs
Labels: area: NRT, ready-to-merge

#6425 Enable nullability in DockingAttribute
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DockingAttribute.cs
Labels: area: NRT, ready-to-merge

#6426 Enable nullability in ProgressBarAccessibleObject
  src/System.Windows.Forms/src/System/Windows/Forms/ProgressBar.ProgressBarAccessibleObject.cs
Labels: area: NRT

#6446 Enable nullability in ImageIndexConverter
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ImageIndexConverter.cs
Labels: area: NRT, ready-to-merge

#6428 Enable nullability in SendKeys
  src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.GetModuleHandle.cs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/SendKeys.cs
Labels: area: NRT

#6447 Enable nullability in SelectionRange and SelectionRangeConverter
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/SelectionRange.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SelectionRangeConverter.cs
Labels: area: NRT, ready-to-merge

#6456 Enable nullability in LinkConverter
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/LinkConverter.cs
Labels: area: NRT, ready-to-merge

#6457 Enable nullability in ListViewItemStateImageIndexConverter
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItemStateImageIndexConverter.cs
Labels: area: NRT, ready-to-merge

#6454 Use generic queue in Control
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
Labels: ready-to-merge

#6458 Enable nullability in UITypeEditor
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Drawing/Design/UITypeEditor.cs
Labels: area: NRT, ready-to-merge

#6482 [servicing6.0*] Fixing incorrect state set for State.Created flag on the Control
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
Labels: servicing-approved, ready-to-merge

#6388 Enable nullability in WinCategoryAttribute
  src/System.Windows.Forms/src/System/Windows/Forms/WinCategoryAttribute.cs
Labels: area: NRT, ready-to-merge

#6262 Rewrite printPreviewDialog, label and DataGridView MAUI tests
  Winforms.sln
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiDataGridViewTests/MauiDataGridViewTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiDataGridViewTests/MauiDataGridViewTests.csproj
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiLabelTests/MauiLabelTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiLabelTests/MauiLabelTests.csproj
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiPrintPreviewDialogTests/MauiPrintPreviewDialogTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiPrintPreviewDialogTests/MauiPrintPreviewDialogTests.csproj
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.Maui.IntegrationTests/System.Windows.Forms.Maui.IntegrationTests.csproj
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DataGridViewTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PrintPreviewDialogTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/LabelTests.cs
Labels: test-enhancement

#6488 Fixing incorrect mouse tooltip for TabPage of TabControl
  src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolTipTests.cs
Labels: :mailbox_with_mail: waiting-for-testing

#6484 Make toolStrip non-nullable in ToolStripGripRenderEventArgs and ToolStripRenderEventArgs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripGripRenderEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripRenderEventArgs.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripGripRenderEventArgsTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripRenderEventArgsTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripRendererTests.cs
Labels: :book: documentation: breaking, ready-to-merge

#6470 Make s_events non-nullable in SendKeys
  src/System.Windows.Forms/src/System/Windows/Forms/SendKeys.SendKeysHookProc.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SendKeys.cs
Labels: area: NRT, ready-to-merge

#6395 Enable nullability in MouseHoverTimer
  src/System.Windows.Forms/src/System/Windows/Forms/MouseHoverTimer.cs
Labels: area: NRT

#6507 Make ToolStripItem non-nullable in ToolStripItemRenderEventArgs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItemImageRenderEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItemRenderEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSeparatorRenderEventArgs.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripGripRenderEventArgsTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemImageRenderEventArgsTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemRenderEventArgsTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripRenderEventArgsTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripRendererTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripSeparatorRenderEventArgsTests.cs
Labels: :book: documentation: breaking, area: NRT

#6135 Enable nullability in DataGridViewEditingControlShowingEventArgs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewEditingControlShowingEventArgs.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewEditingControlShowingEventArgsTests.cs
Labels: :book: documentation: breaking, area: NRT

#6510 Make contentPanel non-nullable in ToolStripContentPanelRenderEventArgs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripContentPanelRenderEventArgs.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripContentPanelRenderEventArgsTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripRendererTests.cs
Labels: :book: documentation: breaking, area: NRT

#6422 Enable nullability in ToolStripPanelRenderEventArgs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelRenderEventArgs.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripPanelRenderEventArgsTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripRendererTests.cs
Labels: :book: documentation: breaking, area: NRT

#6476 Enable nullability in classes that inherit from ToolStripDropDownItemAccessibleObject
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownButton.ToolStripDropDownButtonAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripMenuItem.ToolStripMenuItemAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripOverflowButton.ToolStripOverflowButtonAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSplitButton .ToolStripSplitButtonUiaProvider.cs
Labels: area: NRT

#6522 Reverting fix with drawing a border for a standard button
  src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/ButtonBaseAdapter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/ButtonStandardAdapter.cs
Labels: :boom: regression, ready-to-merge

#6504 Marked problematic test with "Skip" attribute
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PrintPreviewDialogTests.cs
Labels: :mailbox_with_no_mail: waiting-author-feedback

#6516 Improve build on Linux
  eng/common/native/init-compiler.sh
  eng/packageContent.targets
Labels: :octocat: automerge, area: infra

#6523 Enable nullability in PageSetupDialog
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Printing/PageSetupDialog.cs
Labels: area: NRT

#6543 Add new msftbot rules
  .github/fabricbot.json
Labels: area: infra

#6472 Enable nullability in Button and IButtonControl
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Button.cs
  src/System.Windows.Forms/src/System/Windows/Forms/IButtonControl.cs
Labels: area: NRT

#6525 Replaces deprecated build image
  azure-pipelines.yml
Labels: area: infra

#6410 Enable nullability in NativeWindow
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.CreateWindowExW.cs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.WindowClass.cs
  src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs
Labels: area: NRT

#5319 Add support for IFileOpenDialog
  src/System.Windows.Forms.Primitives/src/Interop/Interop.IID.cs
  src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.CoCreateInstance.cs
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.COMDLG_FILTERSPEC.cs
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.IFileDialog.cs
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.IFileOpenDialog.cs
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.IShellItem.cs
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SHCreateShellItem.cs
  src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileOpenDialogWrapper.cs
  src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.ShellItemWrapper.cs
  src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
  src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.Vista.cs
  src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
Labels: :mailbox_with_mail: waiting-for-testing, ready-to-merge

#6473 Enable nullability in ContainerInfo
  src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.ContainerInfo.cs
Labels: area: NRT

#6407 Enable nullability in EnumUnknown
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.EnumUnknown.cs
Labels: :octocat: automerge, area: NRT

#6578 Enable nullability in UpDownButtonsAccessibleObject
  src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.UpDownButtonsAccessibleObject.DirectionButtonAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.UpDownButtonsAccessibleObject.cs
Labels: area: NRT

#6391 Enable nullability in ToolStripSystemRenderer
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSystemRenderer.cs
Labels: area: NRT

#6404 Enable nullability in DataStreamFromComStream
  src/System.Windows.Forms/src/System/Windows/Forms/DataStreamFromComStream.cs
Labels: area: NRT, waiting-on-team

#6564 Speedup BeginInvoke a little.
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
Labels: :octocat: automerge

#6575 Prevent accidental changing of IID.IAccessible
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs
  src/System.Windows.Forms.Primitives/src/Interop/Oleacc/Interop.LresultFromObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildNativeWindow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
Labels: :octocat: automerge

#6577 Enable nullability in ListControl
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ItemArray.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListControl.cs
Labels: area: NRT
