Repository dotnet/winforms, pull requests merged in 2022-08, with the labels that each got.

#7242 Fixing issue with announcing of PropertyGrid expanded state
  src/System.Windows.Forms/src/Resources/SR.resx
  src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
Labels: :mailbox_with_mail: waiting-for-testing, tenet-accessibility, waiting-review

#6669 Fixing text pattern of a multiline text box
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Automation/UiaTextProvider.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Automation/UiaTextRange.cs
  src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/Automation/UiaTextRangeTests.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxUiaTextProvider.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseUiaTextProvider.cs
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/MainFormControlsTabOrder.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/TextBoxes.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/TextBoxes.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/TextBoxes.resx
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TextBoxBase.TextBoxBaseUiaTextProviderTests.cs
Labels: tenet-accessibility

#6309 Improving accessible object for label edit in ListView
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.SetWinEventHook.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.UnhookWinEvent.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.WINEVENT.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.WINEVENTPROC.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewLabelEditAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewLabelEditNativeWindow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewLabelEditUiaTextProvider.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewLabelEditAccessibleObjectTests.cs
Labels: tenet-accessibility

#7532 Adding the ListViewItem CheckBox check announcement
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemBaseAccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemBaseAccessibleObjectTests.cs
Labels: tenet-accessibility, :octocat: automerge

#7330 Fixing memory leaks of Numeric/DomainUpDown elements accessible objects
  docs/list-of-diagnostics.md
  src/Common/src/Obsoletions.cs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
  src/System.Windows.Forms/src/System.Windows.Forms.csproj
  src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainItemAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainItemListAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainUpDownAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.cs
  src/System.Windows.Forms/src/System/Windows/Forms/NumericUpDown.NumericUpDownAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/NumericUpDown.cs
  src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownBaseAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.UpDownButtonsAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.cs
  src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DirectionButtonAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DomainUpDown.DomainItemAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DomainUpDown.DomainItemListAccessibleObjectTests.cs
Labels: tenet-accessibility, :book: documentation: breaking, :octocat: automerge

#7453 Fixing TabPage memory leaks
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabPage.TabAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPage.TabAccessibleObjectTests.cs
Labels: tenet-accessibility, tenet-performance, :octocat: automerge

#7319 Fixing memory leaks of ComboBox elements and items accessible objects
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildNativeWindow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ObjectCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxChildNativeWindowTests.cs
Labels: tenet-accessibility

#7537 Moving common logic of keyboard's simulation into the helper class.
  src/System.Windows.Forms/tests/TestUtilities/KeyboardSimulator.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Labels: test-enhancement

#7569 Change ReleaseUiaProvider method to set Accessibility object to null
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarBodyAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarRowAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.MonthCalendarAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
Labels: tenet-accessibility, tenet-performance, ready-to-merge

#7395 Fixing of ToolStrip elements accessible objects
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownMenu.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemTests.cs
Labels: tenet-accessibility, tenet-performance

#7362 Refactoring of `UiaDisconnectProvider` usage implementation
  src/System.Windows.Forms.Primitives/src/Interop/UiaCore/Interop.UiaDisconnectProvider.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ColumnHeader.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.AccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemDetailsAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewLabelEditNativeWindow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarBodyAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarRowAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.MonthCalendarAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
  src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.UpDownButtonsAccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolTipTests.cs
Labels: tenet-accessibility, :octocat: automerge

#7590 Temporarily fix VB App Framework Logging.
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Logging/Log.vb
Labels: draft

#7529 Hiding TabStop property of PrintPreviewControl from Designer and setting the default value as false.
  src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewControl.cs
Labels: tenet-accessibility, :octocat: automerge

#7643 Replace "up for grabs" with "help wanted"
  .github/fabricbot.json
  CONTRIBUTING.md
  docs/developer-guide.md
  docs/issue-guide.md
  docs/roadmap.md
Labels: :octocat: automerge, area: infra

#7659 Move to -Svc pool provider in release branches
  azure-pipelines-richnav.yml
  azure-pipelines.yml
  eng/pipelines/build.yml
Labels: area: infra

#7664 Update VS redist package version
  Directory.Build.targets
  docs/testing-in-vs.md
  eng/Versions.props
  global.json
  src/System.Windows.Forms/tests/AccessibilityTests/Accessibility_Core_App.csproj
Labels: area: infra

#7671 Remove unused enums
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GA.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.ICON.cs
Labels: :octocat: automerge

#7684 Set Targeting Ref pack version to MicrosoftNETCoreAppRuntimewinx64PackageVersion
  Directory.Build.targets
Labels: area: infra

#7694 Update build images
  azure-pipelines-richnav.yml
  azure-pipelines.yml
  eng/pipelines/build.yml
Labels: area: infra

#7698 Update build images (release/7.0)
  azure-pipelines-richnav.yml
  azure-pipelines.yml
  eng/pipelines/build.yml
Labels: area: infra
