Repository dotnet/winforms, pull requests merged in 2022-06, with the labels that each got.

#7234 Enable nullability in ToolStripSettings and ToolStripSettingsManager
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSettings.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSettingsManager.SettingsStub.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSettingsManager.cs
Labels: area: NRT

#7235 Enable nullability in DataGridViewHitTestTypeInternal and DataGridViewValidateCellInternal
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.DataGridViewHitTestTypeInternal.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.DataGridViewValidateCellInternal.cs
Labels: area: NRT

#7259 Enable nullability in ComponentEditorForm
  src/System.Windows.Forms.Primitives/src/Interop/Gdi32/Interop.ExtTextOutW.cs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.ComponentEditorPageSite.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.PageSelector.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.cs
Labels: area: NRT

#7210 Rewrite MauiComboBoxTests #3617
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiComboBoxTests/DerivedComboBox.cs
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiComboBoxTests/MauiComboBoxTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiComboBoxTests/MauiComboBoxTests.csproj
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.Maui.IntegrationTests/System.Windows.Forms.Maui.IntegrationTests.csproj
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ComboBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
Labels: test-enhancement, waiting-review

#7204 Restore ToolboxSnapDragDropEventArgs implementation
  Winforms.sln
  eng/Versions.props
  src/Common/tests/TestUtilities/XUnit/UseCultureAttribute.cs
  src/Common/tests/TestUtilities/XUnit/UseDefaultXunitCultureAttribute.cs
  src/System.Windows.Forms.Design/src/Properties/AssemblyInfo.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/ToolboxSnapDragDropEventArgs.SnapDirection.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/ToolboxSnapDragDropEventArgs.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.SPI.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.SystemParametersInfoW.cs
  src/System.Windows.Forms.Primitives/src/Properties/AssemblyInfo.cs
  src/System.Windows.Forms/src/Properties/AssemblyInfo.cs
  src/System.Windows.Forms/tests/IntegrationTests/NativeHost/NativeHost.vcxproj
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ButtonTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ComboBoxTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DataGridViewTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DesignBehaviorsTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Directory.Build.props
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DragDropTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/FormTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/GlobalSuppressions.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ImageListTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/DenyExecutionSynchronizationContext.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/SendInput.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ListViewTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/MDITests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/MonthCalendarAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/MonthCalendarTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PrintPreviewDialogTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PropertyGridInternal/DropDownButton.DropDownButtonAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PropertyGridInternal/PropertyGridView.DropDownHolder.DropDownHolderAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PropertyGridInternal/PropertyGridView.GridViewListBox.GridViewListBoxAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PropertyGridInternal/PropertyGridView.GridViewTextBox.GridViewTextBoxAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PropertyGridViewTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Resources/image.png
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/RichTextBoxTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/System.Windows.Forms.UI.IntegrationTests.csproj
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/TabControlTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/xunit.runner.json
  src/System.Windows.Forms/tests/TestUtilities/Properties/InternalsVisibleTo.cs
  src/System.Windows.Forms/tests/TestUtilities/PropertyGridInternal/SubPropertyGrid.cs
Labels: servicing-approved

#7274 Fix typo in 3.1 template.
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-CSharp/.template.config/template.json
Labels: servicing-approved

#7293 Enable nullability in DataGridViewTextBoxEditingControl and IDataGridViewEditingControl
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewEditingControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxEditingControl.cs
Labels: area: NRT

#7289 Enable nullability in ListViewNativeItemCollection
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewNativeItemCollection.cs
Labels: :octocat: automerge, area: NRT

#7290 Produce trim warning as part of the build
  Directory.Build.props
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms.Primitives/src/System.Windows.Forms.Primitives.csproj
  src/System.Windows.Forms/src/System.Windows.Forms.csproj
Labels: area: trimming

#7304 Cleanup trimming warnings from Primitives project
  src/System.Windows.Forms.Primitives/src/System.Windows.Forms.Primitives.csproj
  src/System.Windows.Forms.Primitives/src/System/TrimmingConstants.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Message.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/PaddingConverter.cs
Labels: :octocat: automerge

#7144 Enable nullability in some Control members
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/Resources/SR.resx
  src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.OleInterfaces.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.PageSelector.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Label.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridErrorDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/RadioButton.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollableControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SplitContainer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Splitter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SplitterPanel.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolstripProfessionalRenderer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.UpDownButtonsAccessibleObject.DirectionButtonAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserSiteBase.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHostTests.cs
Labels: :book: documentation: breaking, area: NRT

#7315 Enable nullability in MarshalingControl
  src/System.Windows.Forms/src/System/Windows/Forms/Application.MarshallingControl.cs
Labels: area: NRT

#7298 Enable nullability in ToolStripItemInternalLayout
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.ToolStripItemInternalLayout.ToolStripLayoutData.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.ToolStripItemInternalLayout.cs
Labels: area: NRT

#7309 Enable nullability in some Control members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
  src/System.Windows.Forms/src/System/Windows/Forms/GroupBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ProgressBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DesignBehaviorsTests.cs
Labels: :octocat: automerge, area: NRT

#7311 Use LibraryImport in some Interop User32
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.AdjustWindowRectEx.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.AdjustWindowRectExForDpi.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.BeginPaint.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.DrawEdge.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.DrawFrameControl.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.DrawText.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.DrawTextEx.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.EnumChildWindows.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.EnumDisplayMonitors.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.EnumThreadWindows.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.EnumWindows.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.FillRect.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.FindWindowW.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetAwarenessFromDpiAwarenessContext.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetClassLong.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetClientRect.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetClipCursor.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetDC.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetDCEx.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetDlgItemInt.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetIconInfo.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetMenuItemInfoW.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetMessagePos.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetMonitorInfoW.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetScrollInfo.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetSysColor.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetSysColorBrush.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetThreadDpiAwarenessContext.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetUpdateRect.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetUpdateRgn.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetUserObjectInformationW.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetWindowDpiAwarenessContext.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetWindowRect.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetWindowRgn.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetWindowText.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.InvalidateRgn.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.MessageBoxW.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.MonitorFromRect.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.RedrawWindow.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.RegisterClassW.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.RegisterClipboardFormatW.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.RegisterWindowMessageW.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.ReleaseDC.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.ScrollWindow.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.SetScrollInfo.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.SetThreadDpiAwarenessContext.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.SetWindowText.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.TrackMouseEvent.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.VkKeyScanW.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.WindowFromDC.cs
Labels: :octocat: automerge

#7256 Add trimming annotations
  src/System.Windows.Forms.Primitives/src/System/TrimmingConstants.cs
  src/System.Windows.Forms/src/System.Windows.Forms.csproj
  src/System.Windows.Forms/src/System/Resources/ResXSerializationBinder.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxPropertyDescriptor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/BindingManagerBase.cs
  src/System.Windows.Forms/src/System/Windows/Forms/BindingSource.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ColumnHeader.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2AboutBoxPropertyDescriptor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2ExtendedTypeConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2ExtendedUITypeEditor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IDispatchConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/ComNativeDescriptor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.AxSourcingSite.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewBand.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewButtonCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewButtonColumn.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCheckBoxCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumn.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxColumn.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewImageCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewImageColumn.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewLinkCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewLinkColumn.cs
  src/System.Windows.Forms/src/System/Windows/Forms/FlatButtonAppearanceConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlToClrEventProxy.cs
  src/System.Windows.Forms/src/System/Windows/Forms/LinkArea.LinkAreaConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MergePropertyDescriptor.MergedAttributeCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MergePropertyDescriptor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollableControl.DockPaddingEdges.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SelectionRangeConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SpecialFolderEnumConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutPanelCellPosition.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextBoxAutoCompleteSourceConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripControlHost.StubSite.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
Labels: :octocat: automerge, area: trimming

#7299 Build with VS 2022 / C++ toolset v143
  eng/init-vs-env.cmd
  eng/pipelines/build.yml
  src/System.Windows.Forms/tests/InteropTests/NativeTests/NativeTests.proj
Labels: :octocat: automerge, area: infra

#7314 Adding UIA support for WebBrowser
  src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowser.WebBrowserAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowser.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Control.ControlAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/WebBrowser.WebBrowserAccessibleObjectTests.cs
Labels: tenet-accessibility

#7350 Fixed accessibility BoundingRectangle of nested Forms
  src/System.Windows.Forms/src/System/Windows/Forms/Form.AccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Form.FormAccessibleObjectTests.cs
Labels: waiting-review, waiting-on-team

#7206 Refactoring AutomationId at the accessible object classes #6603
  src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Button.ButtonAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/CheckBox.CheckBoxAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildEditUiaProvider.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildListUiaProvider.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.DataGridViewCellAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/GroupBox.GroupBoxAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Label.LabelAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemBaseAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Panel.PanelAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PictureBox.PictureBoxAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.GridEntryAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/RadioButton.RadioButtonAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollBar.ScrollBarAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Splitter.SplitterAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabControlAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabPage.TabAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabPage.TabPageAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripContainer.ToolStripContainerAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.TrackBarAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowser.WebBrowserAccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ButtonBase.ButtonBaseAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Control.ControlAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/GroupBoxAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/LabelAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemBaseAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PictureBox.PictureBoxAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControl.TabControlAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPage.TabPageAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TrackBar.TrackBarAccessibleObjectTests.cs
Labels: tenet-accessibility, :book: documentation: breaking, waiting-review
