Repository dotnet/winforms, pull requests merged in 2022-07, with the labels that each got.

#6576 Add support for drag images and drop descriptions
  src/System.Windows.Forms.Primitives/src/Interop/Interop.CLSID.cs
  src/System.Windows.Forms.Primitives/src/Interop/Interop.IID.cs
  src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.IDropSourceNotify.cs
  src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.OleDuplicateData.cs
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.DROPDESCRIPTION.cs
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.DROPIMAGETYPE.cs
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.IDragSourceHelper2.cs
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.IDropTargetHelper.cs
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SHDRAGIMAGE.cs
  src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.IDropSourceNotifyVtbl.cs
  src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
  src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DragDropFormat.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DragEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DropImageType.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DropSource.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DropTarget.cs
  src/System.Windows.Forms/src/System/Windows/Forms/GiveFeedbackEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.OleCallback.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropTargetManager.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/MainFormControlsTabOrder.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DragDropTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Resources/3dwarro.cur
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Resources/3dwno.cur
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Resources/move.bmp
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/System.Windows.Forms.UI.IntegrationTests.csproj
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Data/DragDrop/DragAccept.bmp
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Data/DragDrop/DragAccept.rtf
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Data/DragDrop/NyanCat1.bmp
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Data/DragDrop/NyanCat2.bmp
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Data/DragDrop/NyanCat3.bmp
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Data/DragDrop/NyanCat4.bmp
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Data/DragDrop/NyanCat5.bmp
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Data/DragDrop/NyanCatAscii.txt
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Data/DragDrop/NyanCatAscii_301.bmp
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Data/DragDrop/ToolStripAsciiCat.bmp
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Data/DragDrop/ToolStripDragAccept.bmp
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Data/DragDrop/ToolStripNyanCat.bmp
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/DragDrop.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/DragDrop.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/DragDrop.resx
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/WinformsControlsTest.csproj
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DragDropFormatTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DragDropHelperTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DragEventArgsTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/GiveFeedbackEventArgsTests.cs
Labels: ready-to-merge

#7377 Update branding to 6.0.8
  eng/Versions.props
Labels: :octocat: automerge

#7399 update version to .NET 7 RC1
  eng/Versions.props
Labels: :octocat: automerge

#7400 Create an RC1 milestone
  .github/fabricbot.json
Labels: :octocat: automerge

#7398 Disable localization in the servicing branch for .NET7 preview7
  azure-pipelines.yml
Labels: :octocat: automerge

#7409 Returning the AccessibilityObject of a DataGridViewRowHeaderCell instead of a DataGrid...
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.AccessibleObject.cs
Labels: :octocat: automerge

#7420 Enable nullability in TableLayoutStyle
  src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutStyle.cs
Labels: area: NRT

#7435 Enable nullability in ToolStripContainer
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripContainer.cs
Labels: area: NRT

#7434 Enable nullability in AxPropertyTypeEditor
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxPropertyTypeEditor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyPageUITypeConverter.cs
Labels: area: NRT

#7317 Enable nullability in RelatedImageListAttribute
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ImageIndexEditor.cs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/RelatedImageListAttribute.cs
  src/System.Windows.Forms/src/misc/ImageListUtils.cs
Labels: area: NRT

#7418 Enable nullability in IBindableComponent
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/IBindableComponent.cs
Labels: area: NRT

#7436 Fix ToolTip on MenuStrip with dropdown.
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownItem.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MenuStripAndCheckedListBox.Designer.cs
Labels: ready-to-merge

#7450 Enable nullability in ExceptionEditor
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.ExceptionEditor.cs
Labels: area: NRT

#7449 Enable nullability in ToolStripGrip
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripGrip.cs
Labels: area: NRT

#7438 Enable nullability in DataGridViewDataErrorEventArgs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.DataConnection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewDataErrorEventArgs.cs
Labels: area: NRT, ready-to-merge

#7447 Update CONTRIBUTING.md
  CONTRIBUTING.md
  docs/developer-guide.md
Labels: :books: documentation

#7441 Enable nullability in classes that inherit from ToolStripItemInternalLayout
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownButton.ToolStripDropDownButtonInternalLayout.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripLabel.ToolStripLabelLayout.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripMenuItem.ToolStripMenuItemInternalLayout.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSplitButton .ToolStripSplitButtonButtonLayout.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripStatusLabel.ToolStripStatusLabelLayout.cs
Labels: area: NRT

#7416 Enable nullability in some Control members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Button.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.Ime.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/KeyboardToolTipStateMachine.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SplitContainer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WinFormsUtils.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DragDropTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs
Labels: area: NRT

#7437 Enable nullability in ToolStripPanel
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.cs
Labels: area: NRT

#7421 Setting UIA_IsDialogPropertyId correctly when Form.ShowDialog() was called
  src/System.Windows.Forms.Primitives/src/Interop/UiaCore/Interop.UIA.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.AccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Form.FormAccessibleObjectTests.cs
Labels: ready-to-merge

#7456 Enable nullability in some Control members and LayoutEventArgs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/LayoutEventArgs.cs
Labels: area: NRT, ready-to-merge

#7462 Enable nullability in some Control members, ControlTabOrderHolder and ControlTabOrderComparer
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlTabOrderComparer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlTabOrderHolder.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/AttributeTypeSorter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SplitContainer.cs
Labels: area: NRT, ready-to-merge

#7459 Adding supports of UIA provider for ToolStripPanel
  src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.ToolStripPanelAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripPanel.ToolStripPanelAccessibleObjectTests.cs
Labels: ready-to-merge

#7486 Enable nullability in ContainerControl
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
  src/System.Windows.Forms/src/System/Windows/Forms/IContainerControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollableControl.cs
Labels: area: NRT

#7487 Enable nullability in IDropTarget and ISupportOleDropSource
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ISupportOleDropSource.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ISupportOleDropTarget.cs
Labels: area: NRT

#7488 Enable nullability in ComponentEditorPage
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorPage.cs
Labels: area: NRT

#7403 Make the TreeView respect the DoubleBuffered property
  src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
Labels: ready-to-merge

#7402 Attempt to get the default error icon from the OS
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SHGSI.cs
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SHGetStockIconInfo .cs
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SHSTOCKICONID.cs
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SHSTOCKICONINFO.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.cs
Labels: ready-to-merge

#7489 Adding a unit test to check ListView.GroupCollapsedStateChanged event work
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObjectTests.cs
Labels: test-enhancement, ready-to-merge

#7451 User32 ActivateKeyBoardLayout
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.ActivateKeyboardLayout.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetKeyboardLayout.cs
  src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetKeyboardLayoutList.cs
  src/System.Windows.Forms.Primitives/src/NativeMethods.txt
  src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
Labels: ready-to-merge
