Repository dotnet/winforms, pull requests merged in 2022-05, with the labels that each got.

#7120 Enable nullability in ColumnHeaderConverter
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ColumnHeaderConverter.cs
Labels: area: NRT

#7119 Enable nullability in ContextMenuStrip
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ContextMenuStrip.cs
Labels: area: NRT

#7115 Enable nullability in ListViewItemConverter
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItemConverter.cs
Labels: area: NRT

#7114 Enable nullability in UpDownBase
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.cs
Labels: area: NRT

#7109 Enable nullability in DataGridViewUtilities
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewUtilities.cs
Labels: area: NRT

#7122 Enable nullability in UserControl
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/UserControl.cs
Labels: area: NRT

#7112 Enable nullability in some DataGridView converters
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellStyleConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnConverter.cs
Labels: area: NRT

#7121 Enable nullability in TabPage
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
Labels: area: NRT

#6886 Fixing TextBox accessible object leaks
  src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
  src/System.Windows.Forms/tests/UnitTests/TextBoxBaseTests.cs
Labels: tenet-accessibility

#7126 Enable nullability in TreeViewImageKeyConverter
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/TreeViewImageKeyConverter.cs
Labels: area: NRT

#7046 Enable nullability in NotifyIcon
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/NotifyIcon.cs
Labels: area: NRT

#7118 Enable nullability in ToolStripProfessionalRenderer
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ToolstripProfessionalRenderer.cs
Labels: area: NRT

#7127 Enable nullability in ExceptionConverter
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.ExceptionConverter.cs
Labels: area: NRT

#7110 Enable nullability in some Control members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/CheckBox.CheckBoxAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewTextBox.GridViewTextBoxAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.TrackBarAccessibleObject.cs
Labels: area: NRT

#6920 Fixing ToolStripScrollBtton display issue
  src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
  src/System.Windows.Forms/src/Resources/SR.resx
  src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.ToolStripAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownItemAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownMenu.ToolStripDropDownMenuAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownMenu.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.ToolStripItemAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripOverflow.ToolStripOverflowAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripOverflowButton.ToolStripOverflowButtonAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripScrollButton.StickyLabel.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripScrollButton.StickyLabelAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripScrollButton.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSplitButton .ToolStripSplitButtonUiaProvider.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripDropDownMenu.ToolStripDropDownMenuAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripOverflow.ToolStripOverflowAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripScrollButton.ToolStripScrollButtonAccessibleObjectTests.cs
Labels: tenet-accessibility, waiting-review, waiting-on-team

#7137 Enable nullability in ReservationGrid
  src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.ReservationGrid.cs
Labels: :octocat: automerge, area: NRT

#7142 Enable nullability in ToolStripProfessionalLowResolutionRenderer
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripProfessionalLowResolutionRenderer.cs
Labels: :octocat: automerge, area: NRT

#6978 Workaround for empty finalizers in DataGridView.
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewBand.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumn.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewElement.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewHeaderCell.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewElementTests.cs
Labels: tenet-performance, :octocat: automerge

#7131 Enable nullability in some Control members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ProgressBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.SnappableControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Splitter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripTextBox.ToolStripTextBoxControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.cs
Labels: area: NRT

#7148 Enable nullability in CommonProperties
  src/System.Windows.Forms/src/System/Windows/Forms/Layout/CommonProperties.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Layout/LayoutTransaction.cs
Labels: area: NRT

#7125 Fixing TreeView TreeNode accessible object supports Expand-Collapse pattern even if the node can't expand.
  src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNode.TreeNodeAccessibleObjectTests.cs
Labels: tenet-accessibility, waiting-review

#7152 Enable nullability in TabPageCollection
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
Labels: area: NRT

#7117 Removing an extra NotSortedAccessibleStatus for an empty DataGridView by adding check for empty DVG
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.AccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewAccessibleObjectTests.cs
Labels: tenet-accessibility, waiting-review

#7163 Merging internal commits for release/5.0
  NuGet.config
  eng/Version.Details.xml
  eng/Versions.props
  global.json
Labels: :octocat: automerge

#7164 Enable nullability in GridViewTextBox
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewTextBox.cs
Labels: area: NRT

#6997 Enable nullability in OpenFileDialog
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.Vista.cs
  src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/OpenFileDialog.cs
Labels: area: NRT

#7167 Enable nullability in SaveFileDialog
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SaveFileDialog.cs
Labels: area: NRT

#7176 Enable nullability in HelpPane
  src/System.Windows.Forms/src/System/Windows/Forms/Label.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/HelpPane.cs
Labels: area: NRT

#7179 Enable nullability in ToolStripHighContrastRenderer
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripHighContrastRenderer.cs
Labels: area: NRT

#7157 Enable nullability in CheckedListViewItemCollection
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.CheckedListViewItemCollection.cs
Labels: area: NRT

#7103 Enable nullability in LinkArea and LinkAreaConverter
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/LinkArea.LinkAreaConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/LinkArea.cs
  src/System.Windows.Forms/src/System/Windows/Forms/LinkConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutPanelCellPosition.cs
Labels: area: NRT

#7183 Fix TreeView overflow exception
  src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
Labels: servicing-consider

#7177 Enable nullability in DataGridViewAdvancedBorderStyle
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewAdvancedBorderStyle.cs
Labels: area: NRT

#6863 Fixing UIA tree for ToolStripDropDownMenu
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownItemAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownMenu.ToolStripDropDownMenuAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.ToolStripItemAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripOverflow.ToolStripOverflowAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripOverflowButton.ToolStripOverflowButtonAccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripDropDownMenu.ToolStripDropDownMenuAccessibleObjectTests.cs
Labels: tenet-accessibility

#7187 Enable nullability in SelectedListViewItemCollection
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.CheckedListViewItemCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.SelectedListViewItemCollection.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListView.CheckedListViewItemCollectionTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListView.SelectedListViewItemCollectionTests.cs
Labels: :book: documentation: breaking, area: NRT

#7198 Enable nullability in ToolStripItemDesignerAvailabilityAttribute
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Design/ToolStripItemDesignerAvailabilityAttribute.cs
Labels: area: NRT

#7207 Enable nullability in DataGridViewEditingPanel
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.DataGridViewEditingPanel.cs
Labels: :octocat: automerge, area: NRT

#6249 Fixing NullReferenceException when user removes ListViewItem
  src/System.Windows.Forms/src/Resources/SR.resx
  src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemBaseAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemDetailsAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemListAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemTileAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItemTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Labels: tenet-accessibility

#7191 Test that numeric up-down successfully focused
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/NumericUpDownTests.cs
Labels: test-enhancement, :octocat: automerge

#7192 Enable nullability in TableLayoutPanel
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutPanel.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutSettings.cs
Labels: :mailbox_with_no_mail: waiting-author-feedback, area: NRT

#7223 revert Exception on accessing accessible object after control is disposed
  src/System.Windows.Forms/src/Resources/SR.resx
  src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItemTests.cs
Labels: :octocat: automerge

#7243 Update version to 3.1 in templates
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/.template.config/template.json
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-CSharp/.template.config/template.json
Labels: servicing-approved
