Repository dotnet/winforms, pull requests merged in 2022-02, with the labels that each got.

#6571 Remove using empty base AO ctor
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.TopRowAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainItemAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainItemListAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.Link.LinkAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.GridEntryAccessibleObject.cs
Labels: code cleanup, :octocat: automerge

#6594 Update branding to 6.0.3
  eng/Versions.props
Labels: :octocat: automerge

#6593 Update branding to 5.0.15
  eng/Versions.props
Labels: :octocat: automerge

#6588 Fix NRE in ToolStripItem.InvalidateItemLayout
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MdiControlStripTests.cs
Labels: :octocat: automerge

#6592 Enable nullability in DetailsButton
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/DetailsButton.DetailsButtonAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/DetailsButton.cs
Labels: :octocat: automerge, area: NRT

#6591 Enable nullability in PrintDialog
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintDialog.cs
Labels: area: NRT

#6526 Replaces deprecated build image
  azure-pipelines.yml
Labels: area: infra

#6595 Fix NRE in ToolStripItem.InvalidateItemLayout
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MdiControlStripTests.cs
Labels: servicing-approved

#6412 Enable nullability in ActiveXImpl
  src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.IOleInPlaceFrame.cs
  src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.IOleInPlaceUIWindow.cs
  src/System.Windows.Forms.Primitives/src/Interop/OleAut32/Interop.IPropertyBag.cs
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.PropertyBagStream.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
Labels: area: NRT

#6598 Enable nullability in ComboBox Uia providers
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildDropDownButtonUiaProvider.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildEditUiaProvider.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildTextUiaProvider.cs
Labels: :octocat: automerge, area: NRT

#6622 update arcade version and re-enable template localization
  eng/Version.Details.xml
  eng/Versions.props
  eng/common/templates/job/job.yml
  eng/common/templates/steps/source-build.yml
  global.json
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/Microsoft.Dotnet.Winforms.ProjectTemplates.csproj
Labels: :octocat: automerge, area: infra

#6618 Update winforms-designer.md
  docs/designer-accessibility.md
  docs/winforms-designer.md
Labels: :books: documentation, area: VS designer

#6619 Fixing issue with getting ListViewItem.AccessibilityObject when ListView does not exist (port to 6.0)
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewNativeItemCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItemTests.cs
Labels: servicing-consider

#6631 Enable nullability in ProgressBar
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ProgressBar.cs
Labels: area: NRT

#6630 Enable nullability in Screen
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DisplayInformation.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Screen.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/TabControlTests.cs
Labels: area: NRT

#6445 Enable nullability in ListBindingConverter
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ListBindingConverter.cs
Labels: :octocat: automerge, area: NRT

#6629 Enable nullability in ImageKeyConverter
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ImageKeyConverter.cs
Labels: area: NRT

#6634 added hidden column and row to a DGV in the integration test
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/DataGridViewTest.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/DataGridViewTest.cs
Labels: :octocat: automerge

#6599 Added "Skip" attribute for fail unit tests in arm64 and x86
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ImageListTests.cs
  src/System.Windows.Forms/tests/TestUtilities/ConditionalWinFormsFactAttribute.cs
  src/System.Windows.Forms/tests/TestUtilities/ConditionalWinFormsTheoryAttribute.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
Labels: test-bug, ready-to-merge

#6628 Enable nullability on ScrollableControl
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollableControl.DockPaddingEdges.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollableControl.DockPaddingEdgesConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ScrollableControl.cs
Labels: area: NRT, ready-to-merge

#6632 Enable nullability in SelectedIndexCollection and SelectedObjectCollection
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.SelectedIndexCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.SelectedObjectCollection.cs
Labels: area: NRT, ready-to-merge

#6545 Enable nullability in ButtonBase
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ImageList.Indexer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Label.LabelImageIndexer.cs
Labels: area: NRT, ready-to-merge

#6649 Delete unnecessary Regex.IsMatch usage
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
Labels: :octocat: automerge

#6655 Adding more `Skip` attributes for flaky tests
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/TabControlTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
Labels: waiting-review

#6664 Enable nullability in Panel
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Panel.cs
Labels: ready-to-merge

#6633 Enable nullability in SnappableControl and CommandsPane
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.SnappableControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/CommandsPane.cs
Labels: area: NRT, ready-to-merge

#6376 Enable nullability in DataObject
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DataObject.BitmapBinder.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataObject.DataStore.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataObject.FormatEnumerator.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataObject.OleConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataObject.RestrictedTypeDeserializationException.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/IDataObject.cs
  src/System.Windows.Forms/src/misc/CompatibleIComparer.cs
Labels: area: NRT, ready-to-merge

#6677 Removed redundant condition
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
Labels: :octocat: automerge

#6688 Enable nullability in Label
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Label.cs
Labels: area: NRT

#6674 Enable nullability in FormAccessibleObject
  src/System.Windows.Forms/src/System/Windows/Forms/Form.AccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.AccessibleObject.cs
Labels: waiting-review, area: NRT

#6608 Finish ComWrappers for file dialogs
  src/System.Windows.Forms.Primitives/src/Interop/Interop.HRESULT.cs
  src/System.Windows.Forms.Primitives/src/Interop/Interop.IID.cs
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.IFileDialogCustomize.cs
  src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.IFileSaveDialog.cs
  src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileDialogWrapper.cs
  src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileOpenDialogWrapper.cs
  src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileSaveDialogWrapper.cs
  src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.ShellItemArrayWrapper.cs
  src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
  src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/OpenFileDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SaveFileDialog.cs
Labels: :octocat: automerge, waiting-review

#6668 Pin assembly versions to prevent revving those in servicing releases
  Directory.Build.props
  eng/Versions.props
  pkg/Microsoft.Private.Winforms/Directory.Build.targets
  pkg/Microsoft.Private.Winforms/sdk/dotnet-windowsdesktop/UpdateFileClassification.ps1
  src/System.Windows.Forms.Analyzers.CSharp/src/System.Windows.Forms.Analyzers.CSharp.csproj
  src/System.Windows.Forms.Analyzers/src/System.Windows.Forms.Analyzers.csproj
Labels: :octocat: automerge, area: infra

#6667 Pin assembly versions to prevent revving those in servicing releases
  Directory.Build.props
  eng/Versions.props
  pkg/Microsoft.Private.Winforms/Directory.Build.targets
  pkg/Microsoft.Private.Winforms/sdk/dotnet-windowsdesktop/UpdateFileClassification.ps1
  src/System.Windows.Forms.Analyzers.CSharp/src/System.Windows.Forms.Analyzers.CSharp.csproj
  src/System.Windows.Forms.Analyzers/src/System.Windows.Forms.Analyzers.csproj
Labels: servicing-approved, area: infra

#6585 Enable nullability in various ToolStrip accessible objects
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridToolStrip.PropertyGridToolStripAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.ToolStripAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.ToolStripAccessibleObjectWrapperForItemsOnOverflow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripComboBox.ToolStripComboBoxControl.ToolStripComboBoxControlAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDown.ToolStripDropDownAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownButton.ToolStripDropDownButtonAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownItemAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripGrip.ToolStripGripAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripMenuItem.ToolStripMenuItemAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripNumericUpDown.ToolStripNumericUpDownControl.ToolStripNumericUpDownAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripProgressBar.ToolStripProgressBarControlAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSplitButton .ToolStripSplitButtonUiaProvider.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSplitButton.ToolStripSplitButtonExAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripStatusLabel.ToolStripStatusLabelAccessibleObject.cs
Labels: area: NRT

#6275 Enable nullability in FileDialog
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.Vista.cs
  src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs
Labels: area: NRT

#6726 Enable nullability in CursorConverter
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Cursor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/CursorConverter.cs
Labels: area: NRT

#6728 Enable nullability in LayoutSettings, FlowLayoutSettings and TableLayoutSettings
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/FlowLayoutSettings.cs
  src/System.Windows.Forms/src/System/Windows/Forms/LayoutSettings.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutSettings.cs
Labels: area: NRT

#6620 Implementing uia provider support for DTP control
  src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.DateTimePickerAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Control.ControlAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DateTimePicker.DateTimePickerAccessibleObjectTests.cs
Labels: ready-to-merge

#6735 Enable nullability in DropDownButton
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/DropDownButton.DropDownButtonAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/DropDownButton.cs
Labels: :octocat: automerge, area: NRT

#6049 [5.0] WinForms .NET designer freezes when JAWS is narrating
  src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
Labels: tenet-accessibility, a11yMAS, servicing-approved

#6048 [3.1] WinForms .NET designer freezes when JAWS is narrating
  src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
Labels: tenet-accessibility, a11yMAS, servicing-approved

#6436 Fixing empty value of DefaultAction of DateTimePicker control
  src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.DateTimePickerAccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DateTimePicker.DateTimePickerAccessibleObjectTests.cs
Labels: tenet-accessibility

#6627 Enable nullability in ListView
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ColumnHeader.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ItemCheckedEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.ColumnHeaderCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewNativeItemCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.SelectedIndexCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.SelectedListViewItemCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ItemCheckedEventArgsTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Labels: area: NRT

#6741 Enable nullability in DomainUpDown
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainItemListAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainUpDownItemCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainUpDownItemCompare.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.cs
Labels: ready-to-merge

#6759 Generate SBOM manifest
  eng/pipelines/build.yml
Labels: area: infra

#6725 Enable nullability in FolderBrowserDialog
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
Labels: area: NRT, ready-to-merge

#6692 Explicitly use ComWrappers for file dialogs
  src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileDialogWrapper.cs
  src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileOpenDialogWrapper.cs
  src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileSaveDialogWrapper.cs
  src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.ShellItemArrayWrapper.cs
  src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.Vista.cs
  src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.VistaDialogEvents.cs
  src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/OpenFileDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SaveFileDialog.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FileDialogTests.cs
Labels: ready-to-merge

#6448 Enable nullability in KeysConverter
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/Resources/SR.resx
  src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms/src/System/Windows/Forms/KeysConverter.cs
Labels: area: NRT, ready-to-merge
