Repository dotnet/winforms, pull requests merged in 2022-09, with the labels that each got.

#7739 [Servicing] Fixing "Collection was modified ..." exception while MonthCalendar AO tree rebuilding
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarBodyAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarRowAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.MonthCalendarAccessibleObject.cs
Labels: servicing-approved

#7748 Fixed HasKeyboardFocusProperty for DGV's AO
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.AccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewAccessibleObjectTests.cs
Labels: ready-to-merge

#7738 Fixing "Collection was modified ..." exception while MonthCalendar AO tree rebuilding
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarBodyAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarRowAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.MonthCalendarAccessibleObject.cs
Labels: ready-to-merge

#7769 Fixing DataGridView mouse toolTips regression
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DataGridViewTests.cs
Labels: ready-to-merge

#7711 Add drag drop UI test from Explorer
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DragDropTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Interop/UiaClient/Interop.IUIAutomation.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Interop/UiaClient/Interop.IUIAutomationElement.cs
Labels: test-enhancement

#7595 Update template branding
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/.template.config/template.json
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/.template.config/template.json
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-CSharp/.template.config/template.json
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-VisualBasic/.template.config/template.json
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-CSharp/.template.config/template.json
  pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-VisualBasic/.template.config/template.json
Labels: area: templates

#7611 Skipping disabled items from ToolStrip.
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripButton.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripButtonTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
Labels: tenet-accessibility

#7793 Explicitly declare HighDpiMode in the project file for integration test
  Directory.Build.props
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/WinformsControlsTest.csproj
Labels: test-enhancement

#7788 Released AccessibleObjects of ToolStripItems
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildEditUiaProvider.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildListUiaProvider.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripControlHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripComboBox.ToolStripComboBoxAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripControlHost.ToolStripControlHostAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripDropDownItemAccessibleObjectTests.cs
Labels: :octocat: automerge

#7841 Use native tools present on the machine rather than bootstraped tools in CI build
  Restore.cmd
  build.cmd
  global.json
Labels: :octocat: automerge

#7851 Add section on how to run/debug test runner crashes
  docs/testing.md
Labels: :books: documentation
