Repository dotnet/winforms, pull requests merged in 2023-12, with the labels that each got.

#10186 Enable nullability in some DataGridViewComboBoxCell members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewComboBoxCell.ItemComparer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewComboBoxCell.cs
Labels: ready-to-merge, area: NRT

#10329 Refactor `RichTextBox.Find` to use `EM_FINDTEXT` when checking for kashida
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/RichTextBox/RichTextBox.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/RichTextBoxes.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/RichTextBoxes.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
Labels: ready-to-merge

#10319 Verify that the drop source target window is in-process
  src/System.Windows.Forms.Primitives/src/NativeMethods.txt
  src/System.Windows.Forms/src/System/Windows/Forms/OLE/DragDropHelper.cs
  src/System.Windows.Forms/src/System/Windows/Forms/OLE/DropSource.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DragDropHelperTests.cs
Labels: ready-to-merge

#10417 Enable nullability in remaining DataGridViewComboBoxCell members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewComboBoxCell.cs
Labels: ready-to-merge, area: NRT

#10295 Add ValuePattern.Value changed event to TextBox
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBoxBase.TextBoxBaseAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBoxBase.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/Control.ControlAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/MaskedTextBox.MaskedTextBoxAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/TextBoxBaseAccessibleObjectTests.cs
Labels: ready-to-merge

#10392 Enable nullability in some DataGridView.Methods members
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridView.Methods.cs
Labels: area: NRT

#10321 [API Proposal]: add ToolStripItem.SelectedChanged event #8548
  src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
  src/System.Windows.Forms/src/Resources/SR.resx
  src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripItem.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemTests.cs
Labels: :books: documentation, ready-to-merge

#10433 Change `PropertyDescriptorGridEntry.NotifyParentsOfChanges` to fix wrong behavior
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/MultiPropertyDescriptorGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/PropertyDescriptorGridEntry.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridTests.cs
Labels: ready-to-merge

#10420 Enable nullability in MultiSelectRootGridEntry.PropertyMerger
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/MultiSelectRootGridEntry.PropertyMerger.cs
Labels: ready-to-merge, area: NRT

#10432 Replace ArrayList with List in several designers
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.DesignerControlCollectionCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FlowLayoutPanelDesigner .cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TabControlDesigner.cs
Labels: ready-to-merge

#9408 Enable nullability in ComponentDesigner
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ComponentDesigner.ShadowPropertyCollection.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ComponentDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/BindingNavigatorDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/BindingSourceDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.ControlDesignerAccessibleObject.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewColumnDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/NotifyIconDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/PrintDialogDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/SplitContainerDesigner.OrientationActionList.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/SplitContainerDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/SplitterPanelDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripContainerDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripPanelDesigner.cs
  src/System.Windows.Forms.Design/tests/UnitTests/ControlDesignerTests.cs
  src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ComponentDesignerTests.cs
Labels: :book: documentation: breaking, ready-to-merge, area: NRT

#10426 Using CurrentUICulture to localize instead of using the CurrentCulture
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripMenuItem.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripMenuItemTests.cs
Labels: ready-to-merge

#10484 Change default opt-in to false for AnchorLayoutV2 (#9942)
  docs/design/anchor-layout-changes-in-net80.md
  src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
  src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/LocalAppContextSwitchesTest.cs
Labels: draft

#10464 Makes UIA consider starting row as 1 (new default) for new lines in DataGridView
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridView.Methods.cs
Labels: draft

#10478 Hide the RichTextBox drag image and drop description if the Effect is set to None
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/RichTextBox/RichTextBox.OleCallback.cs
Labels: ready-to-merge

#10463 Enable nullability in some DataGridView.Methods members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridView.Methods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewRowCollection.RowComparer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewSortCompareEventArgs.cs
Labels: ready-to-merge, area: NRT

#10459 Update the logic of the function GetIconResourceAsBitmap in class Sca…
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DesignerActionGlyph.cs
Labels: ready-to-merge

#10131 Fix issue 9999: Update IconEditor to offset the icon within the property grid entry
  src/System.Windows.Forms.Design/src/System/Drawing/Design/IconEditor.cs
Labels: ready-to-merge, :boom: regression-release

#10511 Enable nullability in some DataGridView.Methods members
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridView.Methods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewCell.DataGridViewCellAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewImageCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewRow.DataGridViewRowAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewTopLeftHeaderCell.DataGridViewTopLeftHeaderCellAccessibleObject.cs
Labels: ready-to-merge, area: NRT

#10423 More uses of ArgumentOutOfRangeException throw helpers
  src/System.Windows.Forms.Primitives/src/System/IntrinsicExtensions.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Count.cs
  src/System.Windows.Forms/src/Resources/SR.resx
  src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/Buttons/ButtonBase.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/Buttons/FlatButtonAppearance.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridView.Methods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewBand.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewColumn.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewRowHeightInfoNeededEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewTextBoxCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DateTimePicker/DateTimePicker.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/Labels/Label.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ListBoxes/ListBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ListView/ColumnHeader.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ListView/ListViewGroup.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ListView/ListViewItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/MonthCalendar/MonthCalendar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ProgressBar/ProgressBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/RichTextBox/RichTextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/TabControl/TabControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/TabControl/TabPage.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBoxBase.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripSplitButton.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/TreeView/TreeNode.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/TreeView/TreeView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/UpDown/DomainUpDown.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/UpDown/NumericUpDown.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Layout/Containers/SplitContainer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Panels/TableLayoutPanel/TableLayoutSettings.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Panels/TableLayoutPanel/TableLayoutStyle.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Scrolling/ScrollBar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Scrolling/ScrollProperties.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolTip/ToolTip.cs
Labels: ready-to-merge
