Repository dotnet/winforms, pull requests merged in 2023-05, with the labels that each got.

#7316 Enable nullability in TabControl
  src/System.Windows.Forms.Design/src/System/Drawing/Design/ColorEditor.ColorUI.ColorEditorTabControl.cs
  src/System.Windows.Forms.Design/src/System/Drawing/Design/ColorEditor.ColorUI.cs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControl.ControlCollectionTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControl.TabPageCollectionTests.cs
Labels: area: NRT

#9057 Make task dialog sample menu window readable on high-DPI settings
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/TaskDialogSamples.cs
Labels: ready-to-merge

#9018 Fix null reference in PermonV2 mode.
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripRenderer.cs
Labels: Servicing-approved

#7047 Enable nullability in AutoCompleteStringCollection
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/AutoCompleteStringCollection.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AutoCompleteStringCollectionTests.cs
Labels: area-NRT, draft, area: NRT

#9077 Enable nullability in ToolStripPanelRowCollection and remove some unnecessary DEBUG pre-processor checks
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomDesignerLoader.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewRowCollectionCodeDomSerializer.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Message.cs
  src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.SelectionScope.cs
  src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.SetBkModeScope.cs
  src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.SetMapModeScope.cs
  src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.SetRop2Scope.cs
  src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.SetTextAlignmentScope.cs
  src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.SetTextColorScope.cs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Layout/CommonProperties.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MDIWindowDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextRenderer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.ToolStripPanelRowCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelRow.VerticalRowManager.cs
Labels: area: NRT

#9076 Enable nullability in Adorner
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/Adorner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DesignerActionGlyph.cs
Labels: ready-to-merge, area: NRT

#9079 Enable nullability in PropertyManager
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/BindingManagerBase.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyManager.cs
Labels: ready-to-merge, area: NRT

#9080 Enable nullability in CustomColorDialog
  src/System.Windows.Forms.Design/src/System/Drawing/Design/ColorEditor.CustomColorDialog.cs
Labels: area: NRT

#9081 Enable nullability in TextBoxDesigner
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TextBoxDesigner.cs
Labels: area: NRT

#9090 Enable nullability in HtmlToClrEventProxy
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlToClrEventProxy.cs
Labels: area: NRT

#9091 Enable nullability in WebBrowserSiteBase
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserSiteBase.cs
Labels: area: NRT

#9092 Enable nullability in ContainerSelectionUIItem and SelectionUIItem
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/SelectionUIService.ContainerSelectionUIItem.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/SelectionUIService.SelectionUIItem.cs
Labels: ready-to-merge, area: NRT

#9072 Enable nullability in ToolStripItemCollection
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItemCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSettingsManager.cs
Labels: ready-to-merge, area: NRT

#9094 Enable nullability in ToolStripPanelRowControlCollection
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelRow.ToolStripPanelRowControlCollection.cs
Labels: area: NRT

#9098 Enable nullability in WebBrowserEvent
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowser.WebBrowserEvent.cs
Labels: ready-to-merge, area: NRT

#8123 Enable nullability in some ListViewItem members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroupItemCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.IKeyboardToolTip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemImageAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItemCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObjectTests.cs
Labels: area-NRT, area: NRT

#9103 Enable nullability in classes that inherit from Button in System.Windows.Forms.Design
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/CollectionEditor.SplitButton.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.EditorPropertyLine.EditorButton.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.EditorPropertyLine.cs
Labels: area: NRT

#9097 Enable nullability in some ToolTip members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.TipInfo.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
Labels: area: NRT

#9146 Add a unit test for PrintPreviewControlAccessibleObject.Bounds property
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PrintPreviewControl.PrintPreviewControlAccessibleObjectTests.cs
Labels: waiting-review

#9142 Added ToggleStatePropertyChanged UIA event for ToolStripButton.
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripButton.ToolStripButtonAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripButton.cs
Labels: :octocat: automerge

#8480 Fix JAWS announcing 'context menu' and not announcing 'leaving menus' when navigating through MenuStrip items
  src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ContextMenuStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MenuStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDown.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownItem.cs
Labels: :octocat: automerge
