Repository dotnet/winforms, pull requests merged in 2023-08, with the labels that each got.

#9542 Enable nullability in DataGridViewButtonCell
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewButtonCell.DataGridViewButtonCellRenderer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewButtonCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewHeaderCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewLinkCell.cs
Labels: area: NRT

#9560 Port TableLayoutPanelDesigner, TabControlDesigner to runtime
  src/System.Design/src/System.Design.Forwards.cs
  src/System.Windows.Forms.Design/src/Resources/SR.resx
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/TableLayoutPanelBehavior.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/TableLayoutPanelResizeGlyph.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FlowPanelDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TabControlDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TabPageDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TableLayoutPanelDesigner.cs
  src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/DesignerAttributeTests.cs
Labels: Net9.0

#9595 Add PrintDialogDesigner.cs
  src/System.Design/src/System.Design.Forwards.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/PrintDialogDesigner.cs
  src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/DesignerAttributeTests.cs
Labels: ready-to-merge, Net9.0

#9636 Enable nullability in FontEditor and FontNameEditor
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/Drawing/Design/FontEditor.cs
  src/System.Windows.Forms.Design/src/System/Drawing/Design/FontNameEditor.cs
Labels: area: NRT

#9640 Enable nullability in InheritanceService
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/InheritanceService.cs
Labels: area: NRT

#9575 Add AssociatedComponents test of ToolStripDropDownDesigner ToolStripDropDownItemDesigner ToolStripMenuItemDesigner
  src/System.Windows.Forms.Design/tests/UnitTests/ControlDesignerTests.cs
  src/System.Windows.Forms.Design/tests/UnitTests/Mocks/MockSite.cs
  src/System.Windows.Forms.Design/tests/UnitTests/SplitContainerDesignerTests.cs
  src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ComponentDesignerTests.cs
  src/System.Windows.Forms.Design/tests/UnitTests/ToolStripDesignerTests.cs
  src/System.Windows.Forms.Design/tests/UnitTests/ToolStripDropDownDesignerTest.cs
  src/System.Windows.Forms.Design/tests/UnitTests/ToolStripDropDownItemDesignerTest.cs
  src/System.Windows.Forms.Design/tests/UnitTests/ToolStripMenuItemDesignerTest.cs
Labels: test-enhancement, waiting-CI-to-pass

#9608 Enable nullability in CursorEditor
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/Drawing/Design/CursorEditor.CursorUI.cs
  src/System.Windows.Forms.Design/src/System/Drawing/Design/CursorEditor.cs
Labels: area: NRT

#9649 Enable nullability in DockEditor, ContentAlignmentEditor and SelectionPanelBase
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/Drawing/Design/ContentAlignmentEditor.cs
  src/System.Windows.Forms.Design/src/System/Drawing/Design/SelectionPanelBase.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DockEditor.cs
Labels: ready-to-merge, area: NRT

#9664 Enable nullability in CodeDomSerializerException
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializerException.cs
Labels: ready-to-merge, area: NRT

#9616 fix System.ArgumentOutOfRangeException: Value of '-22' is not valid for 'LargeChange'#9596
  src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewControl.cs
Labels: ready-to-merge

#9607 Enable nullability in UndoEngine
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/UndoEngine.UndoUnit.AddRemoveUndoEvent.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/UndoEngine.UndoUnit.ChangeUndoEvent.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/UndoEngine.UndoUnit.RenameUndoEvent.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/UndoEngine.UndoUnit.UndoEvent.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/UndoEngine.UndoUnit.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/UndoEngine.cs
  src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/UndoUnitTests.cs
Labels: area: NRT

#9658 Port FlowLayoutPanelDesigner to runtime
  src/System.Design/src/System.Design.Forwards.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ComponentDesigner.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/FlowLayoutPanelDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FlowLayoutPanelDesigner .cs
  src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/DesignerAttributeTests.cs
Labels: Net9.0

#9670 Enable nullability in ImageListCodeDomSerializer
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ImageCollectionCodeDomSerializer.cs
Labels: area: NRT

#9692 Enable nullability in LoadedEventArgs
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/LoadedEventArgs.cs
Labels: area: NRT

#9700 Enable nullability in BorderSidesEditor
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/BorderSidesEditor.BorderSidesEditorUI.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/BorderSidesEditor.cs
Labels: area: NRT

#9682 Issus 4908 port save file dialog designer and folder browser dialog designer
  src/System.Design/src/System.Design.Forwards.cs
  src/System.Windows.Forms.Design/src/PublicAPI.Unshipped.txt
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ComponentDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FolderBrowserDialogDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FolderNameEditor.FolderBrowser.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/SaveFileDialogDesigner.cs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
  src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/DesignerAttributeTests.cs
Labels: ready-to-merge, Net9.0

#9681 Fix `Help.ShowHelp` to use `FindExecutable` to enable passing full local URL to default browser
  src/System.Windows.Forms.Primitives/src/NativeMethods.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Help.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HelpProvider.cs
Labels: ready-to-merge

#9645 Port PropertyGridDesigner and NotifyIconDesigner to runtime #4908
  src/System.Design/src/System.Design.Forwards.cs
  src/System.Windows.Forms.Design/src/Resources/SR.resx
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/NotifyIconDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/NotifyIconDesignerActionList.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/PropertyGridDesigner.cs
  src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/DesignerAttributeTests.cs
Labels: ready-to-merge, Net9.0

#9710 Fixing indeterminate image color
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripRenderer.cs
Labels: ready-to-merge, Net9.0

#9691 Enable nullability in BinaryEditor
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/BinaryEditor.BinaryUI.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/BinaryEditor.cs
Labels: area: NRT

#9709 Add "SetTextualDefaultProperty = false" for MaskedTextBox
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/MaskedTextBoxDesigner.cs
  src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.cs
Labels: ready-to-merge

#9707 Enable nullability in MaskDescriptor
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/MaskDescriptor.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/MaskDescriptorComparer.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/MaskDescriptorTemplate.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/MaskDesignerDialog.cs
Labels: ready-to-merge, area: NRT

#9749 Port BindingSourceDesigner, BindingNavigatorDesigner to runtime
  src/System.Design/src/System.Design.Forwards.cs
  src/System.Windows.Forms.Design/src/PublicAPI.Unshipped.txt
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DataSourceDescriptor.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DataSourceDescriptorCollection.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DataSourceGroup.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DataSourceGroupCollection.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DataSourceProviderService.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/BindingNavigatorDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/BindingSourceDesigner.cs
  src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/DesignerAttributeTests.cs
Labels: ready-to-merge

#9775 Enable nullability in AnchorEditor
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/AnchorEditor.AnchorUI.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/AnchorEditor.cs
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/AnchorEditorTests.cs
Labels: area: NRT

#9779 Enable nullability in BasicDesignerLoader and CodeDomDesignerLoader
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/BasicDesignerLoader.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomDesignerLoader.ModifierConverter.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomDesignerLoader.ModifiersExtenderProvider.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomDesignerLoader.ModifiersInheritedExtenderProvider.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomDesignerLoader.cs
  src/System.Windows.Forms.Primitives/src/System/ComponentModel/MemberDescriptorExtensions.cs
  src/System.Windows.Forms.Primitives/src/System/ComponentModel/TypeDescriptorHelper.cs
Labels: area: NRT

#9699 Enable nullability in some TreeView members
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TreeViewActionList.cs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.PageSelector.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeNodeCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs
Labels: ready-to-merge, area: NRT
