Repository dotnet/winforms, pull requests merged in 2023-03, with the labels that each got.

#7431 Workaround for empty finalizer in ApplicationContext.
  src/System.Windows.Forms/src/System/Windows/Forms/Application.ModalApplicationContext.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ApplicationContext.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ApplicationContextTests.cs
Labels: ready-to-merge

#8739 Enable nullability in ListViewNativeItemCollection
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewNativeItemCollection.cs
Labels: area: NRT

#8767 Enable nullability in ShortcutKeysUI
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ShortcutKeysEditor.ShortcutKeysUI.cs
Labels: area: NRT

#8766 Enable nullability in MdiControlStrip
  src/System.Windows.Forms/src/System/Windows/Forms/MDIControlStrip.cs
Labels: area: NRT

#8775 Enable nullability in CodeMethodMap
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeMethodMap.cs
Labels: area: NRT

#8763 Enable nullability in MultilineStringEditor
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/MultilineStringEditor.cs
Labels: area: NRT

#8776 Enable nullability in ExpressionContext and ExpressionTable
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ExpressionContext.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ExpressionTable.cs
Labels: area: NRT

#8765 Enable nullability in ColorPaletteAccessibleObject and ControlDesignerAccessibleObject
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/Drawing/Design/ColorEditor.ColorPalette.ColorPaletteAccessibleObject.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.ControlDesignerAccessibleObject.cs
Labels: area: NRT

#8762 Enable nullability in ToolStripPanelRow
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelRow.HorizontalRowManager.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelRow.VerticalRowManager.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelRow.cs
Labels: area: NRT

#8781 Enable nullability in ListBindingHelper
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ListBindingHelper.cs
Labels: area: NRT

#8784 Enable nullability in ComponentCache
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ComponentCache.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ComponentCodeDomSerializer.cs
Labels: area: NRT

#8719 Add interpolated string handler to TraceSwitchExtensions.TraceVerbose
  src/Common/src/TraceSwitchExtensions.cs
Labels: ready-to-merge

#8787 Enable nullability in CodeMarkers
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/CodeMarkers.cs
Labels: area: NRT, ready-to-merge

#8793 Dispose Cursor in tests
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHostTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CursorConverterTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CursorTests.cs
Labels: ready-to-merge

#8736 Refactor CodeDomSerializerBase.Trace methods for string interpolation
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializerBase.TraceIfInterpolatedStringHandler.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializerBase.TraceInterpolatedStringHandler.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializerBase.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CollectionCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ComponentCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ContainerCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/EnumCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/EventMemberCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/PrimitiveCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/PropertyMemberCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ResourceCodeDomSerializer.SerializationResourceManager.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ResourceCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/TypeCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlCodeDomSerializer.cs
Labels: ready-to-merge

#8916 Added a new test for ListBox Control to the WinformsControlsTest
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/MainFormControlsTabOrder.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListBoxes.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListBoxes.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListBoxes.resx
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs
Labels: test-enhancement
