Repository dotnet/winforms, pull requests merged in 2023-02, with the labels that each got.

#8546 Fix `KeyUp` event on `Listview` control
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Labels: ready-to-merge

#8509 Refactor `ToolStripControlHost.Control` property to throw `ObjectDisposedException` if null
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripControlHost.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripControlHostTests.cs
Labels: :book: documentation: breaking

#8528 Refactor `SelectionService` to replace `ArrayList` and enable Nullability
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/SelectionService.cs
Labels: ready-to-merge

#8594 Add ContainsObjectThatIsNotNull method in PropertyStore and use it where possible
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewBand.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewHeaderCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyStore.cs
Labels: ready-to-merge

#8574 Removed extra validation in flaky DataGridView unit tests.
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTests.cs
Labels: test-bug, waiting-review

#8588 Fix ToolStrip/MenuStrip/StatusStrip arrow keys navigation
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
Labels: ready-to-merge

#8592 Fix menu item without sub menu leaking focus on arrow keys
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownItem.cs
Labels: ready-to-merge

#8595 Enable nullability in FeedbackRectangle
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.FeedbackRectangle.cs
Labels: area: NRT

#8618 Prevent disposing Icons that are not owned by the caller.
  src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProviderTests.cs
Labels: ready-to-merge

#8628 Enable nullability in PropertyTabCollection
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.PropertyTabCollection.cs
Labels: :book: documentation: breaking, area: NRT

#8622 Enable nullability in WindowsFormsSynchronizationContext
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/WindowsFormsSynchronizationContext.cs
Labels: area: NRT

#8645 Enable nullability in some ToolTip members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/KeyboardToolTipStateMachine.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
Labels: area: NRT

#8649 Enable nullability in more small line count files
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Drawing/Design/IPropertyValueUIService.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellLinkedListElement.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewSelectedColumnCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewSelectedRowCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxColumn.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Design/IUIService.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlWindow.HTMLWindowEvents2.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.LayoutInfo.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListManagerBindingsCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MDIClient.ControlCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/ImmutablePropertyDescriptorGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MergePropertyDescriptor.MultiMergeCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.ControlCollection.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControl.ControlCollectionTests.cs
Labels: area: NRT

#8675 Enable nullability and refactor `LocalizationCodeDomSerializer` to replace `Hashtable` with `HashSet`
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/LocalizationCodeDomSerializer.cs
Labels: area: NRT

#8676 Enable nullability and refactor `CfCodeToolboxItem` to replace `Hashtable` with `Dictionary`
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/OleDragDropHandler.CfCodeToolboxItem.cs
Labels: area: NRT

#8672 Refactor `DesignerHost` to replace `ArrayList` with `List<T>`
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerHost.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/BasicDesignerLoader.cs
Labels: ready-to-merge

#8518 Removed the DefaultValue attribute from ListBox.ItemHeight property
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBoxTests.cs
Labels: :beetle: bug, tenet-compatibility, :book: documentation: breaking, area: VS designer, area: designer support

#8474 Removed DefaultValue attribute from the RowTemplate.Height property
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewRowTests.cs
Labels: tenet-compatibility, :book: documentation: breaking, area: VS designer

#8570 Enable nullability in some ToolStrip members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/MenuStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDown.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownMenu.cs
Labels: area: NRT

#8691 Enable nullability in some ToolStrip members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/MenuStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
Labels: area: NRT

#8707 Enable nullability in HtmlWindowCollection
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlWindowCollection.cs
Labels: area: NRT

#8708 Enable nullability in ListViewItemCollection
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewItemCollection.cs
Labels: area: NRT

#8698 Enable nullability in ObjectCollection
  src/Common/src/IComparerHelpers.cs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ObjectCollection.cs
Labels: area: NRT, ready-to-merge

#8711 Enable nullability in remaining ToolStrip members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/MdiControlStrip.SystemMenuItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MenuStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.ToolStripAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropTargetManager.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripLabel.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripMenuItem.cs
Labels: area: NRT

#8706 Enable nullability in TextBoxBaseDesigner
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ComboBoxDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TextBoxBaseDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripItemDesigner.cs
Labels: area: NRT

#6793 Enable nullability in ToolStripControlHost
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripControlHost.ToolStripControlHostAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripControlHost.cs
Labels: area: NRT, ready-to-merge
