Repository dotnet/winforms, pull requests merged in 2023-09, with the labels that each got.

#9733 Make sure the Narrator won't announce the password text
  src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseUiaTextProvider.cs
Labels: ready-to-merge

#9792 Enable nullability in some DataGridView members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs
Labels: area: NRT

#9809 Enable nullability in some TreeView members
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ObjectSelectorEditor.Selector.cs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeView.TreeViewAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
Labels: area: NRT

#9853 Release COM object when wrapping in PictureWrapper
  src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
Labels: Servicing-approved

#9798 Enable nullability in EventBindingService
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/EventBindingService.EventPropertyDescriptor.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/EventBindingService.cs
Labels: ready-to-merge, area: NRT

#9838 Add Password tests to WinformsControlsTest
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/MainFormControlsTabOrder.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Password.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Password.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Password.resx
Labels: ready-to-merge

#9861 Fix application hang on exit
  src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.GetExitCodeThread.cs
Labels: Servicing-approved

#9842 Enable nullability in several internal CodeDomSerializers
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ComponentCache.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ComponentCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ContainerCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/EnumCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/EventMemberCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/PrimitiveCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ResourceCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripMenuItemCodeDomSerializer.cs
Labels: ready-to-merge, area: NRT

#9856 Make sure no exception pop up when edit label is accessed in ListView with viewMode: LargeIcon,SmallIcon,Tile
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemTileAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemWithImageAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewLabelEditAccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemWithImageAccessibleObjectTests.cs
Labels: ready-to-merge

#9897 Enable nullability in RelatedCurrencyManager
  src/System.Windows.Forms/src/System/Windows/Forms/BindingManagerBase.cs
  src/System.Windows.Forms/src/System/Windows/Forms/RelatedCurrencyManager.cs
Labels: ready-to-merge, area: NRT

#9872 Enable nullability in some Binding members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Binding.cs
  src/System.Windows.Forms/src/System/Windows/Forms/BindingContext.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Formatter.cs
Labels: ready-to-merge, area: NRT

#9904 Enable nullability in several internal CodeDomSerializers, part 2
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TableLayoutPanelCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripCodeDomSerializer.cs
Labels: area: NRT

#9912 Convert interop RichEdit enums to use `CsWin32`
  src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.CFE.cs
  src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.CFM.cs
  src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.CHARFORMAT2W.cs
  src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.ECO.cs
  src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.ECOOP.cs
  src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.EN.cs
  src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.ENM.cs
  src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.ES.cs
  src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.GETTEXTEX.cs
  src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.GETTEXTLENGTHEX.cs
  src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.GT.cs
  src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.GTL.cs
  src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.ICM.cs
  src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.MAX_TAB_STOPS.cs
  src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.PARAFORMAT.cs
  src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.PFN.cs
  src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.RECO.cs
  src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.SCF.cs
  src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.SEL.cs
  src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.SELCHANGE.cs
  src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.SF.cs
  src/System.Windows.Forms.Primitives/src/NativeMethods.txt
  src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/RichTextBoxTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/RichTextBoxes.cs
  src/System.Windows.Forms/tests/InteropTests/RichTextBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
Labels: ready-to-merge

#9891 Enable nullability in MemberCodeDomSerializer and all derived classes
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomLocalizationProvider.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/MemberCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/PropertyMemberCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ResourcePropertyMemberCodeDomSerializer.cs
Labels: ready-to-merge, area: NRT

#9902 Enable nullability in DataGridViewCellStyle
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewCellStyleBuilder.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewColumnCollectionDialog.cs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellStyle.cs
Labels: ready-to-merge, area: NRT

#9937 Enable nullability in SelectionUIService
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ISelectionUIService.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/SelectionUIService.HitTestInfo.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/SelectionUIService.SelectionUIItem.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/SelectionUIService.cs
Labels: ready-to-merge, area: NRT

#9936 Enable nullability in BehaviorServiceAdornerCollection and GlyphCollection
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/AdornerCollection.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/GlyphCollection.cs
Labels: ready-to-merge, area: NRT

#9871 Enable nullability in some DataGridView members
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewDesigner.cs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.DataGridViewEditingPanelAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.DataGridViewRowAccessibleObject.cs
Labels: ready-to-merge, area: NRT

#9840 Enable nullability in TableLayout
  src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutPanel.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutSettings.TableLayoutSettingsStub.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutSettings.cs
Labels: area: NRT

#9839 Enable nullability in DataGridViewRow
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
Labels: ready-to-merge, area: NRT

#9791 Enable nullability in some DataGridView.Methods members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
Labels: ready-to-merge, area: NRT

#9841 Enable nullability in some PictureBox members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/PictureBox.cs
Labels: ready-to-merge, area: NRT

#9933 Fix the color contrast ratio of ToolStripMenuItem's checked style is less than 3 : 1
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripHighContrastRenderer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolstripProfessionalRenderer.cs
Labels: ready-to-merge

#9857 Enable nullability in remaining TreeView members
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignBindingPicker.cs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/TreeNodeMouseClickEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
Labels: ready-to-merge, area: NRT

#9663 Enable nullability in StronglyTypedResourceBuilder
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/Resources/Tools/StronglyTypedResourceBuilder.ResourceData.cs
  src/System.Windows.Forms.Design/src/System/Resources/Tools/StronglyTypedResourceBuilder.cs
Labels: ready-to-merge, area: NRT, Net9.0

#9622 use generic overload of Enum.IsDefined to avoid boxing
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/DpiHelper.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewBand.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellStyle.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewHeaderCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/KeyEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/KeysConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PreviewKeyDownEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowser.WebBrowserSite.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ApplicationTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PowerStatusTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/SystemInformationTests.cs
Labels: ready-to-merge

#9984 Enable nullability in DataGridViewTextBoxCell
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxCell.cs
Labels: ready-to-merge, area: NRT

#9952 Enable nullability in DataGridViewLinkCell
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewLinkCell.cs
Labels: ready-to-merge, area: NRT

#9953 Enable nullability in DataGridViewRowCollection
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowCollection.RowList.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowCollection.cs
Labels: ready-to-merge, area: NRT

#9993 Enable nullability in some DataGridViewColumn members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumn.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxColumn.cs
Labels: ready-to-merge, area: NRT

#9643 Enable nullability in ToolboxItem and derived classes
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/Drawing/Design/ToolboxItem.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DocumentDesigner.AxToolboxItem.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/OleDragDropHandler.CfCodeToolboxItem.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripContainerDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripPanelDesigner.cs
  src/System.Windows.Forms.Primitives/src/System/ComponentModel/TypeDescriptorHelper.cs
  src/System.Windows.Forms.Primitives/src/System/ServiceExtensions.cs
Labels: ready-to-merge, area: NRT

#10003 Don't invalidate Cursors cursors (#9994)
  src/System.Windows.Forms/src/System/Windows/Forms/Cursor.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CursorTests.cs
Labels: Servicing-approved

#10000 Update FlowLayoutPanelDesigner.cs and ToolStripContainerDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FlowLayoutPanelDesigner .cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripContainerDesigner.cs
Labels: ready-to-merge

#9888 Enable nullability in some PropertyGridView members
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.DropDownHolder.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.PropertyGridViewAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PropertyGridInternal/PropertyGridView.DropDownHolder.DropDownHolderAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PropertyGridInternal/PropertyGridView.GridViewListBox.GridViewListBoxAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PropertyGridInternal/PropertyGridView.GridViewTextBox.GridViewTextBoxAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/TestUtilities/PropertyGridInternal/SubPropertyGrid.cs
Labels: ready-to-merge, area: NRT

#9966 Enable nullability in DesignerFrame and clean it up
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.AdornerWindow.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerFrame.cs
Labels: area: NRT

#10004 Enable nullability in some DataGridView.Methods members
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxEditingControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewDataErrorEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewEditingCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewEditingControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxEditingControl.cs
Labels: ready-to-merge, area: NRT

#10002 Enable nullability in some CurrencyManager members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/BindingManagerBase.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/CurrencyManager.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListControl.cs
Labels: ready-to-merge, area: NRT

#10010 Update troubleshooting.md
  docs/designer/troubleshooting.md
Labels: ready-to-merge

#9995 Enable nullability in DataGridViewCellCollection
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellCollection.cs
Labels: ready-to-merge, area: NRT

#9992 Enable nullability in MenuCommandService
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/MenuCommandService.cs
Labels: ready-to-merge, area: NRT

#9982 Enable nullability in remaining DataGridView members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs
Labels: ready-to-merge, area: NRT

#9967 add shortcut on Control.Invoke when the delegate is SendOrPostCallback
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/WindowsFormsSynchronizationContextTests.cs
Labels: ready-to-merge

#9914 Enable nullability in CodeDomLocalizationProvider and clean it up
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomLocalizationProvider.LanguageCultureInfoConverter.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomLocalizationProvider.LanguageExtenders.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomLocalizationProvider.cs
  src/System.Windows.Forms.Primitives/src/System/ComponentModel/Design/Serialization/DesignerSerializationManagerHelper.cs
Labels: ready-to-merge, area: NRT
