Repository dotnet/winforms, pull requests merged in 2023-06, with the labels that each got.

#9084 Enable nullability in classes that inherit from DesignerActionList
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ContextMenuStripActionList.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.DockingActionList.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerActionVerbList.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ListControlUnboundActionList.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ListViewActionList.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/MaskedTextBoxDesignerActionList.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/PictureBoxActionList.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/RichTextBoxActionList.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TextBoxActionList.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripActionList.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TreeViewActionList.cs
Labels: area: NRT

#9109 Enable nullability in remaining ListViewItem members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs
Labels: waiting-review, area: NRT

#9150 [Release/7.0] Disable tests on internal CI or ARM64.
  eng/pipelines/build.yml
Labels: :no_entry_sign: * NO-MERGE *

#9149 [Release/6.0] Disable tests on internal CI or ARM64
  eng/pipelines/build.yml
Labels: :no_entry_sign: * NO-MERGE *

#9246 Update control owning field of Label and Panel to using weak references
  src/System.Windows.Forms/src/System/Windows/Forms/Label.LabelAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Panel.PanelAccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Control.ControlAccessibleObjectTests.cs
Labels: ready-to-merge

#9192 Enable nullability in DesignSurface related code
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ActiveDesignSurfaceChangedEventArgs.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignSurface.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignSurfaceCollection.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignSurfaceEvent.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignSurfaceManager.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignSurfaceServiceContainer.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerEventService.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ReferenceService.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DesignBehaviorsTests.cs
Labels: ready-to-merge, area: NRT

#9078 Use generic list instead of array in TreeNode
  src/System.Windows.Forms/src/System/Windows/Forms/ArraySubsetEnumerator.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeNodeCollection.cs
  src/System.Windows.Forms/tests/UnitTests/SerializableTypesTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNode.TreeNodeAccessibleObjectTests.cs
Labels: ready-to-merge

#6945 Enable nullability in ComboBox
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildNativeWindow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxUiaTextProvider.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
Labels: area-NRT, ready-to-merge, draft, area: NRT

#9338 Enable nullability in WebBrowserSite and fix annotations in WebBrowserEvent
  src/System.Windows.Forms.Primitives/src/Interop/Mshtml/Interop.IDocHostUIHandler.cs
  src/System.Windows.Forms.Primitives/src/Interop/SHDocVw/Interop.DWebBrowserEvents2.cs
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowser.WebBrowserEvent.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowser.WebBrowserSite.cs
Labels: area: NRT

#9337 Enable nullability in remaining Control members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ThreadMethodEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
Labels: ready-to-merge, area: NRT

#9341 Enable nullability in Glyph classes and BehaviorService
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorDragDropEventArgs.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.AdornerWindow.MouseHook.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.AdornerWindow.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.MenuCommandHandler.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorServiceAdornerCollectionEnumerator.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/Glyph.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/SplitContainerDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripItemGlyph.cs
Labels: area: NRT

#9102 Enable nullability in classes that inherit from Form and FormatTypeClass in System.Windows.Forms.Design
  src/Common/src/RTLAwareMessageBox.cs
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/BinaryEditor.BinaryUI.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/CollectionEditor.CollectionForm.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.EditorPropertyLine.FlyoutDialog.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.EditorPropertyLine.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewCellStyleBuilder.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FormatControl.CurrencyFormatType.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FormatControl.CustomFormatType.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FormatControl.DateTimeFormatType.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FormatControl.NoFormattingFormatType.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FormatControl.NumericFormatType.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FormatControl.ScientificFormatType.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FormatControl.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FormatStringDialog.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/LinkAreaEditor.LinkAreaUI.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/MaskDesignerDialog.cs
Labels: ready-to-merge, area: NRT

#9328 Prevent checkable ToolStripButton from losing focus on check/uncheck
  src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripButton.cs
Labels: ready-to-merge

#9357 Defer StackTrace rendering
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/DisposalTracking.cs
Labels: ready-to-merge

#9356 Include stack trace from log method
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/DataCollectionService.cs
Labels: ready-to-merge

#9385 Fix UIA tree structure for ToolStrip overflow menu
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripOverflow.ToolStripOverflowAccessibleObject.cs
Labels: waiting-review

#9395 Fixed TreeView custom sorting failure when TreeNode has child nodes
  src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs
Labels: waiting-review

#9340 Enable nullability in DesignerHost and SiteNestedContainer
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignSurface.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerHost.DesignerHostTransaction.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerHost.Site.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerHost.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/SiteNestedContainer.cs
  src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/DesignerHostTests.cs
  src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/SiteNestedContainerTests.cs
Labels: area: NRT
