Repository dotnet/winforms, pull requests merged in 2023-11, with the labels that each got.

#10194 Enable nullability in remaining DataGridViewCheckBoxCell members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCheckBoxCell.cs
Labels: ready-to-merge, area: NRT

#10172 Review usage of string.Split across codebase
  src/System.Windows.Forms.Primitives/src/System/ComponentModel/TypeConverterHelper.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/PaddingConverter.cs
  src/System.Windows.Forms/src/System/Resources/ResXDataNode.cs
  src/System.Windows.Forms/src/System/Resources/ResXResourceReader.cs
  src/System.Windows.Forms/src/System/Resources/ResXSerializationBinder.cs
  src/System.Windows.Forms/src/System/Windows/Forms/BindingSource.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/KeysConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/LinkArea.LinkAreaConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/LinkConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/LinkUtilities.cs
  src/System.Windows.Forms/src/System/Windows/Forms/SelectionRangeConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutPanelCellPositionTypeConverter.cs
Labels: ready-to-merge

#10205 Enable nullability in some DataGridView.Methods members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellErrorTextNeededEventArgs.cs
Labels: ready-to-merge, area: NRT

#10158 Enable nullability in DataGridViewHeaderCell
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnHeaderCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewHeaderCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowHeaderCell.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewHeaderCellTests.cs
Labels: :book: documentation: breaking, ready-to-merge, area: NRT

#9755 Replacing some ArgumentOutOfRangeException with custom messages with throw helpers
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ImageListDesigner.OriginalImageCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Clipboard.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ObjectCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxCell.ObjectCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowsRemovedEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlElementCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlHistory.cs
  src/System.Windows.Forms/src/System/Windows/Forms/HtmlWindowCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ImageList.ImageCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.IntegerCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.ObjectCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.CheckedIndexCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.ColumnHeaderCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewItemCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewNativeItemCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.SelectedIndexCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.SelectedListViewItemCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItemCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/NotifyIcon.cs
  src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutPanelCellPosition.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutSettings.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeNodeCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs
Labels: ready-to-merge

#10170 Enable nullability in some GridEntry members
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MultiPropertyDescriptorGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.PropertyGridViewAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/SingleSelectRootGridEntry.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PropertyGridInternal/DropDownButton.DropDownButtonAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PropertyGridInternal/PropertyGridView.GridViewTextBox.GridViewTextBoxAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/TestUtilities/PropertyGridInternal/SubPropertyGrid.cs
Labels: ready-to-merge, area: NRT

#10203 Enable nullability in some BindingSource members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/BindingSource.cs
Labels: area: NRT

#10231 Introduce a throw helper in DataGridView.Methods
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellCancelEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellFormattingEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellMouseEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellPaintingEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellParsingEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellValidatingEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellValueEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/IDataGridViewCellEventArgs.cs
Labels: ready-to-merge

#10187 Enable nullability in some DataGridViewCell members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewButtonCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.DataGridViewCellAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellFormattingEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCheckBoxCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnHeaderCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewHeaderCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewImageCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewLinkCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowHeaderCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxCell.cs
Labels: ready-to-merge, area: NRT

#10224 Enable nullability in some DataGridView.Methods members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
Labels: area: NRT

#10236 Refactor `ResizeBehavior` to use `List<T>` instead of `ArrayList`
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/ResizeBehavior.cs
Labels: ready-to-merge

#10269 Enable nullability in some PropertyDescriptorGridEntry members
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/ImmutablePropertyDescriptorGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MultiPropertyDescriptorGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.DropDownHolder.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/AccessibleObjects/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObjectTests.cs
Labels: area: NRT

#9998 Enable nullability in ByteViewer and remove allocations when drawing
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ByteViewer.cs
  src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ByteViewerTests.cs
Labels: area: NRT

#10294 Enable nullability in some DataGridView.Methods members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
Labels: area: NRT

#10317 Replace `Gdip` `HashTable` with `Dictionary<object, object>`
  src/System.Drawing.Common/src/System/Drawing/Brushes.cs
  src/System.Drawing.Common/src/System/Drawing/Gdiplus.cs
  src/System.Drawing.Common/src/System/Drawing/Pens.cs
  src/System.Drawing.Common/src/System/Drawing/SystemBrushes.cs
  src/System.Drawing.Common/src/System/Drawing/SystemPens.cs
Labels: ready-to-merge

#10253 Enable nullability in remaining BindingSource members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/BindingSource.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/BindingSourceTests.cs
Labels: :book: documentation: breaking, ready-to-merge, area: NRT

#9541 Enable nullability in DataGridViewIntLinkedList
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView/DataGridViewCellLinkedList.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView/DataGridViewIntLinkedList.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView/DataGridViewIntLinkedListEnumerator.cs
Labels: area: NRT

#10306 Issue 5761 normalize runtime id to base
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox/ComboBox.ComboBoxAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Labels/LinkLabel.LinkLabelAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox/ListBox.AccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid/PropertyGridInternal/PropertyGridView.GridViewTextBox.GridViewTextBoxAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeView/TreeView.TreeViewAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/UpDown/UpDownBase.UpDownButtons.UpDownButtonsAccessibleObject.cs
Labels: ready-to-merge

#10347 Remove unneeded catch
  src/System.Windows.Forms/src/System/Windows/Forms/Containers/ContainerControl.cs
Labels: ready-to-merge

#10325 Enable nullability in some DataGridView.Methods members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView/DataGridView.Methods.cs
Labels: area: NRT

#10330 Add chartControl to WinformsControlsTest project
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/MainFormControlsTabOrder.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ChartControl.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ChartControl.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ChartControl.resx
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/WinformsControlsTest.csproj
Labels: ready-to-merge

#9457 Enable nullability in ResourceCodeDomSerializer.SerializationResourceManager
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ComponentCache.ResourceEntry.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ComponentCache.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ResourceCodeDomSerializer.SerializationResourceManager.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ResourceCodeDomSerializer.cs
Labels: area: NRT

#10353 Enable nullability in some DataGridView.Methods members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView/DataGridView.Methods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView/DataGridView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView/DataGridViewColumnCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView/DataGridViewRowErrorTextNeededEventArgs.cs
Labels: area: NRT

#10398 [release/8.0] Fix Clear and Remove after Sort in TreeView
  src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs
Labels: Servicing-approved
