Repository dotnet/winforms, pull requests merged in 2023-01, with the labels that each got.

#8425 Fix InvalidCastException in ErrorProvider
  src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProviderTests.cs
Labels: ready-to-merge

#8351 Changed type of the `handle` parameter from `IntPtr` to `HWND` in the `Control.ReleaseUiaProvider` method
  src/System.Windows.Forms.Primitives/src/Interop/UiaCore/Interop.UiaReturnRawElementProvider.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildNativeWindow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxEditingControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxEditingControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewLabelEditNativeWindow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripControlHost.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.cs
  src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ColumnHeader.ListViewColumnHeaderAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBoxAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPage.TabAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNode.TreeNodeAccessibleObjectTests.cs
Labels: ready-to-merge

#8388 Fix generator incrementality
  src/System.Windows.Forms.Analyzers.CSharp/src/System/Windows/Forms/Generators/ApplicationConfigurationGenerator.cs
  src/System.Windows.Forms.Analyzers.CSharp/src/System/Windows/Forms/Generators/ProjectFileReader.cs
  src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilderTests.GenerateInitialize_DefaultFont=SansSerif.verified.txt
  src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilderTests.GenerateInitialize_DefaultFont=Tahoma.verified.txt
  src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilderTests.GenerateInitialize_DefaultFont=default.verified.txt
  src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilderTests.cs
  src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/MockData/ApplicationConfigurationGeneratorTests.GenerateInitialize_user_settings_boilerplate.cs
  src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/MockData/ApplicationConfigurationGeneratorTests.GenerateInitialize_user_top_level.cs
  src/System.Windows.Forms.Analyzers/src/System/Windows/Forms/ApplicationConfig.FontDescriptor.cs
  src/System.Windows.Forms.Analyzers/src/System/Windows/Forms/ApplicationConfig.FontStyle.cs
  src/System.Windows.Forms.Analyzers/src/System/Windows/Forms/ApplicationConfig.GraphicsUnit.cs
  src/System.Windows.Forms.Analyzers/src/System/Windows/Forms/ApplicationConfig.cs
  src/System.Windows.Forms.Analyzers/tests/UnitTests/System/Windows/Forms/Analyzers/ApplicationConfigTests.FontDescriptor.cs
Labels: ready-to-merge

#8447 [Porting] Fix InvalidCastException in ErrorProvider
  src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProviderTests.cs
Labels: servicing-approved

#8429 Enable nullability in some ToolStrip members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/StatusStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
Labels: area: NRT, ready-to-merge

#8413 Enabling nullability annotations to `System.Windows.Forms.Design` classes
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/Resources/SR.resx
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ComponentDesigner.CDDesignerCommandSet.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionHeaderItem.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionItem.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionItemCollection.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.DesignerActionPanelHeaderItem.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPropertyItem.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionTextItem.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerCommandSet.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerHost.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ExceptionCollection.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/HostDesigntimeLicenseContext.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/IMultitargetHelperService.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ObjectSelectorEditor.SelectorNode.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ProjectTargetFrameworkAttribute.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ICodeDomDesignerReload.cs
  src/System.Windows.Forms.Design/src/System/Drawing/Design/ColorEditor.ColorUI.ColorEditorListBox.cs
  src/System.Windows.Forms.Design/src/System/Drawing/Design/ColorEditor.ColorUI.ColorEditorTabControl.cs
  src/System.Windows.Forms.Design/src/System/Drawing/Design/ColorEditor.ColorUI.cs
  src/System.Windows.Forms.Design/src/System/Drawing/Design/ColorEditor.SystemColorComparer.cs
  src/System.Windows.Forms.Design/src/System/Drawing/Design/IToolboxItemProvider.cs
  src/System.Windows.Forms.Design/src/System/Drawing/Design/ToolboxComponentsCreatedEventArgs.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ContextMenuStripGroup.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ContextMenuStripGroupCollection.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataMemberFieldConverter.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/IContainsThemedScrollbarWindows.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ServiceProviderExtensions.cs
  src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ExceptionCollectionTests.cs
Labels: :book: documentation: breaking, area: NRT, ready-to-merge

#8434 Fix UIA tree structure for MenuStrip
  src/System.Windows.Forms/src/System/Windows/Forms/MenuStrip.MenuStripAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownMenu.ToolStripDropDownMenuAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.ToolStripItemAccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MenuStrip.MenuStripAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripDropDownMenu.ToolStripDropDownMenuAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemAccessibleObjectTests.cs
Labels: ready-to-merge

#8461 Follow up to change ArgumentException to use string.Format
  src/System.Windows.Forms.Design/src/Resources/SR.resx
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms.Design/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ExceptionCollection.cs
Labels: ready-to-merge

#8390 Enable Nullability in multiple `Design` classes
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/Drawing/Design/BitmapEditor.cs
  src/System.Windows.Forms.Design/src/System/Drawing/Design/ColorEditor.ColorUI.cs
  src/System.Windows.Forms.Design/src/System/Drawing/Design/ColorEditor.cs
  src/System.Windows.Forms.Design/src/System/Drawing/Design/IconEditor.cs
  src/System.Windows.Forms.Design/src/System/Drawing/Design/ImageEditor.cs
  src/System.Windows.Forms.Design/src/System/Drawing/Design/MetafileEditor.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ImageListImageEditor.cs
Labels: ready-to-merge

#8430 Fixed flaky PrintPreviewDialog tests and added a new test
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PrintPreviewDialogTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PrintPreviewDialogTests.cs
Labels: test-bug

#8366 Change default `ImageList.ColorDepth` to 32bit
  src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageListTests.cs
Labels: :book: documentation: breaking, :mailbox_with_no_mail: waiting-author-feedback

#8452 Enable nullability in SingleSelectRootGridEntry
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/SingleSelectRootGridEntry.cs
Labels: area: NRT

#8435 Enable nullability in Formatter
  src/System.Windows.Forms/src/System/Windows/Forms/Formatter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ListControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MaskedTextBox.cs
Labels: area: NRT

#8325 Enable nullability in ControlItem
  src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.ControlItem.ControlItemAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.ControlItem.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProvider.ControlItem.ControlItemAccessibleObjectTests.cs
Labels: area: NRT, ready-to-merge

#8470 Refactor collection remove methods to fix ownership issues
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/Resources/SR.resx
  src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroupCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutStyleCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItemCollection.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TableLayoutStyleCollectionTests.cs
Labels: :book: documentation: breaking

#8408 Adding UIA's PositionInSet and SizeOfSet properties to ToolStripMenuItemAccessibleObject
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripMenuItem.ToolStripMenuItemAccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripMenuItem.ToolStripMenuItemAccessibleObjectTests.cs
Labels: ready-to-merge

#8486 Scaling ErrorProvider for high dpi
  src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
  src/System.Windows.Forms/src/Resources/System/Windows/Forms/Error.ico
  src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.ErrorWindow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.IconRegion.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.cs
  src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProviderTests.cs
Labels: :books: documentation

#8375 Fixed memory leaking of PropertyGrid
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewListBoxAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewTextBox.GridViewTextBoxAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.PropertyGridViewAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
Labels: ready-to-merge

#8372 Specify `Font` in `HH_POPUPW` when calling `ShowHTML10Help` in `Help.ShowPopup` to allow for unicode characters
  src/System.Windows.Forms/src/System/Windows/Forms/Help.cs
Labels: waiting-review

#8507 Making `DataGridView` icons more clear
  src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowHeaderCell.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlPaintTests.cs
Labels: ready-to-merge

#8503 Description of modernization in winforms code-behind generation in the VS 2022 17.5 Preview3
  docs/designer/modernization-of-code-behind-in-OOP-designer/images/Form1-Designer-C#-comparison.png
  docs/designer/modernization-of-code-behind-in-OOP-designer/images/Form1-Designer-VB-comparison.png
  docs/designer/modernization-of-code-behind-in-OOP-designer/modernization-of-code-behind-in-oop-designer.md
  docs/designer/readme.md
Labels: waiting-review

#8531 Refactored `DropSourceBehavior` to partial and split `BehaviorDataObject` into its own file
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DropSourceBehavior.BehaviorDataObject.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DropSourceBehavior.cs
Labels: ready-to-merge

#6957 Fixed unsharing of last shared row in DataGridViewRowCollection.
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowCollection.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewHeaderCellTests.cs
Labels: area: DataGridView, ready-to-merge

#8439 Fix keyboard layout name returned from System.Windows.Forms.InputLanguage.LayoutName
  src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/InputLanguageTests.cs
Labels: ready-to-merge
