Repository dotnet/winforms, pull requests merged in 2024-03, with the labels that each got.

#10899 [release/7.0] Bump Nuget.Packaging and System.Data.SqlClient Versions
  eng/Versions.props
  src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System.Windows.Forms.Analyzers.CSharp.Tests.csproj
  src/System.Windows.Forms.Analyzers/tests/UnitTests/System.Windows.Forms.Analyzers.Tests.csproj
Labels: :no_entry_sign: * NO-MERGE *

#10867 [release/8.0] Fix empty `OpenFileDialog.FileNames` when `AutoUpgradeEnabled=false` and `Multiselect = true`
  src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Dialogs.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FileDialogTests.cs
Labels: :no_entry_sign: * NO-MERGE *, Servicing-approved

#10910 [release/8.0] WinForms TreeView null reference exception 'owningTreeView'
  src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs
Labels: :no_entry_sign: * NO-MERGE *, Servicing-approved

#10976 Add test coverage for Label
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/LabelTests.cs
Labels: ready-to-merge

#10978 Add test coverage for MaskedTextBox
  src/System.Windows.Forms/tests/UnitTests/MaskedTextBoxTests.cs
Labels: ready-to-merge

#10994 Add code coverage for RichTextBox
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
Labels: ready-to-merge

#10872 Enable nullability in some GridEntry members
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/ArrayElementGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/CategoryGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/GridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/ImmutablePropertyDescriptorGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/MultiPropertyDescriptorGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/PropertyDescriptorGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/PropertyGridView.GridViewTextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/PropertyGridView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/SingleSelectRootGridEntry.cs
Labels: ready-to-merge, area: NRT

#11076 Enable nullability in DesignerExtenders
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerExtenders.NameExtenderProvider.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerExtenders.NameInheritedExtenderProvider.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerExtenders.cs
Labels: ready-to-merge, area: NRT

#11066 Add unit test for TrackBar
  src/System.Windows.Forms/tests/UnitTests/TrackBarTests.cs
Labels: ready-to-merge

#11105 Enable nullability in some GridEntry members
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/ArrayElementGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/CategoryGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/GridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/ImmutablePropertyDescriptorGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/MultiPropertyDescriptorGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/PropertyDescriptorGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/PropertyGridView.cs
Labels: area: NRT

#11107 Enable nullability in ColumnHeaderCollectionEditor
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ColumnHeaderCollectionEditor.cs
Labels: area: NRT

#11121 Enable nullability in DesignerActionUIService and DesignerActionUIStateChangeEventArgs
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionUIService.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionUIStateChangeEventArgs.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DesignerActionKeyboardBehavior.cs
Labels: ready-to-merge, area: NRT

#11134 Fix NPE Error
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ToolTip/ToolTip.cs
Labels: ready-to-merge

#11127 Enable nullability in some GridEntry members
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/GridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/PropertyGridView.cs
Labels: ready-to-merge, area: NRT
