Repository dotnet/winforms, pull requests merged in 2024-01, with the labels that each got.

#10556 Fix dynamic invocation of InitializeStatics
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Dpi/FormDpiTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Dpi/SplitContainerTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Dpi/ToolStripItemTests.Dpi.cs
Labels: ready-to-merge

#10369 [release/8.0] Add ValuePattern.Value changed event to TextBox
  src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Control.ControlAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MaskedTextBox.MaskedTextBoxAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TextBoxBaseAccessibleObjectTests.cs
Labels: Servicing-approved

#10472 fix [Accessibility] Accessibility Insights tool keeps loading when mouse-over DataGridView #10343
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxEditingControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxEditingControl.cs
Labels: Servicing-approved

#10483 Fix RichTextBox drag and drop (#10475)
  src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
Labels: Servicing-approved

#10507 [release/8.0.x] Fix expandable property grid entries
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MultiPropertyDescriptorGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridTests.cs
Labels: Servicing-approved

#10538 Avoid finalization in Cursor.cs if freeing handle not needed
  src/System.Windows.Forms/src/System/Windows/Forms/Input/Cursor.cs
Labels: ready-to-merge

#10543 Enable nullability in some DataGridView.Methods members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridView.Methods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridView.cs
Labels: area: NRT

#10357 Add multiselect to FolderBrowserDialog
  src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
  src/System.Windows.Forms/src/Resources/SR.resx
  src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms/src/System/Windows/Forms/Dialogs/CommonDialogs/FolderBrowserDialog.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FolderBrowserDialogTests.cs
Labels: :books: documentation, ready-to-merge

#10584 Fix `StackOverflow` in `ControlDesigner`
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs
Labels: ready-to-merge

#10570 [release/8.0] [Accessibility]Inspect or AccessibilityInsights tool's rectangle can't focus on the entire Treeview with scrollBar
  src/System.Windows.Forms/src/System/Windows/Forms/TreeView.TreeViewAccessibleObject.cs
Labels: Servicing-approved

#10291 Refactor `WeakRefCollection` to Generics
  src/Common/src/WeakRefCollection.cs
  src/System.Drawing.Common/src/System.Drawing.Common.csproj
  src/System.Drawing.Common/src/System/Drawing/ClientUtils.cs
  src/System.Drawing.Common/src/misc/GDI/DeviceContexts.cs
  src/System.Windows.Forms.Primitives/src/System.Windows.Forms.Primitives.csproj
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/WeakRefCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripManager.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripPanelCell.cs
Labels: waiting-review

#10578 Enable nullability in some DataGridView.Methods members
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridView.Methods.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridView.SelectedCellsAccessibleObject.cs
Labels: ready-to-merge, area: NRT

#10529 Scale icon to Dpi when initializing icon in ThreadExceptionDialog
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/InheritanceUI.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripTemplateNode.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/ScaleHelper.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/GridErrorDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Dialogs/ThreadExceptionDialog.cs
Labels: ready-to-merge

#10629 Enable nullability in remaining DataGridView.Methods members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridView.Methods.cs
Labels: area: NRT

#10142 fix bug The code generated by the ListBox control is not consistent with Framework
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ListBoxes/ListBox.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBoxTests.cs
Labels: ready-to-merge

#10642 Update EnsureRun to return null when _textRegion is null
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/Labels/LinkLabel.cs
Labels: ready-to-merge

#10110 Enable nullability in some PropertyGrid members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGrid.cs
  src/System.Windows.Forms/tests/TestUtilities/PropertyGridInternal/SubPropertyGrid.cs
Labels: ready-to-merge, area: NRT

#10690 add and fix unit tests as a follow up pr 10561
  src/System.Windows.Forms/src/System/Windows/Forms/Panels/Panel.PanelAccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/Panel.PanelAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/TabPage.TabPageAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/TextBoxBaseAccessibleObjectTests.cs
Labels: ready-to-merge

#10689 fix [Accessibility] Narrator cannot announce the leaf node information(level 1) for nodes in TreeView
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/TreeView/TreeNode.TreeNodeAccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/TreeNode.TreeNodeAccessibleObjectTests.cs
Labels: ready-to-merge

#10694 avoid explicit calls to Dispose() in favor of 'using' statement
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewLinkCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewRowHeaderCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ListBoxes/ListBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/MaskedTextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/TreeView/TreeView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Dialogs/ThreadExceptionDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Layout/Containers/SplitContainer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MDI/MDIControlStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Rendering/ControlPaint.cs
Labels: ready-to-merge

#10675 Adds tests for AxSystemMonitor
  src/System.Windows.Forms/tests/AxHosts/AxHosts.csproj
  src/System.Windows.Forms/tests/UnitTests/System.Windows.Forms.Tests.csproj
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxSystemMonitorTests.cs
Labels: ready-to-merge

#10536 dispose graphics in TabControl.WmReflectDrawItem()
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/TabControl/TabControl.cs
Labels: ready-to-merge

#10698 Enable nullability in some PropertyGrid members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/ComNativeDescriptor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGrid.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/CommandsPane.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/PropertyGridView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Design/EventsTab.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Design/PropertyTab.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PropertyGridViewTests.cs
  src/System.Windows.Forms/tests/TestUtilities/PropertyGridInternal/SubPropertyGrid.cs
Labels: area: NRT

#10701 Enable nullability in some GridEntry members
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/CategoryGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/GridEntry.EventEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/GridEntry.cs
Labels: area: NRT

#10707 7027 : fix treeview sorter issue when treeviewnodesorter is null set …
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/TreeView/TreeView.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs
Labels: ready-to-merge

#10757 Enable nullability in some PropertyGrid members
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGrid.cs
Labels: area: NRT

#10768 Fix ListView CancelEdit
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ListView/ListView.cs
Labels: Servicing-consider
