Repository dotnet/winforms, pull requests merged in 2024-02, with the labels that each got.

#10758 Enable nullability in some GridEntry members
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/CategoryGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/GridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/MultiPropertyDescriptorGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/PropertyDescriptorGridEntry.cs
Labels: area: NRT

#10770 Enable nullability in some PropertyGrid members
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGrid.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/HelpPane.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/PropertyGridView.cs
Labels: area: NRT

#10732 Use CurrentUICulture in KeysConverter.cs when converting to name in d…
  src/System.Windows.Forms/src/System/Windows/Forms/Input/KeysConverter.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/KeysConverterTests.cs
Labels: :mailbox_with_mail: waiting-for-testing

#10787 Add unit tests for Label
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/LabelTests.cs
Labels: ready-to-merge

#10829 Update the return Type of the function GetDisplayOrder and GetKeyNames
  src/System.Windows.Forms/src/System/Windows/Forms/Input/KeysConverter.cs
Labels: ready-to-merge

#10710 Add test if running in DesignMode to the MessageBox.Show method
  src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Accessibility/AccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Accessibility/Control.ControlAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Dialogs/MessageBox.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/MessageBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/DataGridViewCellAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/DataGridViewRowAccessibleObjectTests.cs
Labels: ready-to-merge

#10819 Add extension function for DesignerActionItemCollection
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionItemCollectionExtensions.cs
Labels: ready-to-merge

#10725 [release/8.0] Fix ImageList rendering of transparent images
  src/System.Windows.Forms.Primitives/src/Windows/Win32/Foundation/COLORREF.cs
  src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.ImageList.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs
Labels: Servicing-approved

#10697 [release/8.0] Fix regression in KeysConverter.GetStandardValues
  src/System.Windows.Forms/src/System/Windows/Forms/KeysConverter.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/KeysConverterTests.cs
Labels: Servicing-approved

#10669 [release/8.0] [Accessibility]Inspect or AccessibilityInsights tool's rectangle can't focus on the entire FlowLayoutPanel/Panel/SplitContainer/TableLayoutPanel/TabControl/TextBox with scrollBar
  src/System.Windows.Forms/src/System/Windows/Forms/Panel.PanelAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabPage.TabPageAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
  src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseAccessibleObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Panel.PanelAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPage.TabPageAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TextBoxBaseAccessibleObjectTests.cs
Labels: Servicing-approved

#10832 Enable nullability in some GridEntry members
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/GridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/MultiSelectRootGridEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/PropertyGridView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/SingleSelectRootGridEntry.cs
Labels: area: NRT

#10847 Adds control for ErrorProvider on WinformsControlTest
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ErrorProviderTest.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ErrorProviderTest.cs
Labels: ready-to-merge

#10460 Suppress finalizeation of ThreadMethodEntry class. Fix #10361.
  src/System.Windows.Forms/src/System/Windows/Forms/Control.ThreadMethodEntry.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
Labels: waiting-review

#10858 [VMR] Don't error out on non-fatal file locking warnings
  eng/SourceBuild.props
Labels: area-Infrastructure

#10860 Delete Thumbs.db cache file and add it to .gitignore
  .gitignore
  src/System.Windows.Forms/src/Resources/System/Windows/Forms/Design/Thumbs.db
Labels: ready-to-merge

#10702 Enable nullability in some Designer classes
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ButtonBaseDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ComboBoxDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/LabelDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/MaskedTextBoxDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/PictureBoxDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/RadioButtonDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/RichTextBoxDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ScrollableControlDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TextBoxBaseDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TreeViewDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/UpDownBaseDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/UserControlDocumentDesigner.cs
  src/System.Windows.Forms.Primitives/src/System/ComponentModel/MemberDescriptorExtensions.cs
  src/System.Windows.Forms.Primitives/src/System/ComponentModel/PropertyDescriptorCollectionExtensions.cs
  src/System.Windows.Forms.Primitives/src/System/ComponentModel/PropertyDescriptorExtensions.cs
Labels: area: NRT

#10729 Enable CA1815 - Override equals and operator equals on value types
  eng/CodeAnalysis.src.globalconfig
  eng/CodeAnalysis.test.globalconfig
  src/System.Drawing.Common/src/GlobalSuppressions.cs
  src/System.Windows.Forms.Design/src/GlobalSuppressions.cs
  src/System.Windows.Forms.Primitives/src/GlobalSuppressions.cs
  src/System.Windows.Forms/src/GlobalSuppressions.cs
Labels: ready-to-merge

#10749 Enable nullability in DragAssistanceManager
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DragAssistanceManager.Line.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DragAssistanceManager.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/ToolboxItemSnapLineBehavior.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/CommandSet.cs
Labels: ready-to-merge, area: NRT

#10843 Refactor `BindingSource` and `CurrencyManager` to use flags enum field instead of individual boolean fields
  src/System.Windows.Forms/src/System/Windows/Forms/DataBinding/Binding.BindingStates.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataBinding/Binding.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataBinding/BindingSource.BindingSourceStates.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataBinding/BindingSource.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataBinding/CurrencyManager.CurrencyManagerStates.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataBinding/CurrencyManager.cs
Labels: ready-to-merge

#10893 Make IMsoComponent support opt-in
  src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Application.ComponentThreadContext.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Application.LightThreadContext.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
  src/System.Windows.Forms/tests/UnitTests/ThreadContextTests.cs
Labels: :book: documentation: breaking

#10720 fix bug: No text for new tabpage item that added by TabPages property in the properties window in the DemoConsole application
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/CollectionEditor.CollectionEditorCollectionForm.cs
  src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.cs
  src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DesignSurfaceExt/PropertyGridExt.cs
Labels: ready-to-merge

#10857 Add missing Stream overloads in DataStreamFromComStream
  src/System.Windows.Forms/src/System/Windows/Forms/ActiveX/DataStreamFromComStream.cs
Labels: ready-to-merge

#10907 fix Issue "ColumnType is disabled for Columns in EditColumns dialog"
  src/System.Design/src/System.Design.Forwards.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewColumnCollectionDialog.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewColumnTypeEditor.Picker.ListBoxItem.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewColumnTypeEditor.Picker.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewColumnTypeEditor.cs
Labels: ready-to-merge

#10914 Add ToolStripMenuItem test UI in WinformsControlTests
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ToolStripTests.Designer.cs
Labels: ready-to-merge

#10922 Suppress codeQL warnings in tests "BitmapTests" and "ImageListTests"
  src/System.Drawing.Common/tests/mono/System.Drawing/BitmapTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageListTests.cs
Labels: ready-to-merge

#10905 Fix `null` values in `AutoCompleteCustomSource`
  src/System.Windows.Forms/src/System/Windows/Forms/AutoCompleteStringCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/StringSource.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AutoCompleteStringCollectionTests.cs
Labels: ready-to-merge

#10939 Replace MD5 with SHA256
  src/System.Drawing.Common/tests/DrawingTest.cs
  src/System.Drawing.Common/tests/System/Drawing/Graphics_DrawBezierTests.cs
  src/System.Drawing.Common/tests/System/Drawing/Graphics_DrawLineTests.cs
  src/System.Drawing.Common/tests/mono/System.Drawing/BitmapTests.cs
Labels: ready-to-merge
