Repository dotnet/winforms, pull requests merged in 2024-12, with the labels that each got.

#12478 [release/9.0] Informational text in PrintPreviewControl has low contrast in basic and HightContrast themes.
  src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewControl.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Printing/PrintPreviewControlTests.cs
Labels: Servicing-approved

#12559 [release/8.0] Fix issue 12495: Infinite loop in ToolStripItemCollection.AddRange
  src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItemCollection.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemCollectionTests.cs
Labels: Servicing-approved

#12558 [release/9.0] Fix issue 12495: Infinite loop in ToolStripItemCollection.AddRange
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripItemCollection.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemCollectionTests.cs
Labels: Servicing-approved

#12553 Add code coverage for DataGridViewColumnDesignTimeVisibleAttribute
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewColumnDesignTimeVisibleAttributeTests.cs
Labels: waiting-review

#12580 Add code coverage for DataGridViewComboBoxCell.ObjectCollection
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewComboBoxCell.ObjectCollectionTests.cs
Labels: ready-to-merge

#11545 Adding new strongly typed methods to Clipboard, DataObject and IDataObject.
  docs/list-of-diagnostics.md
  src/Common/src/Obsoletions.cs
  src/Common/tests/TestUtilities/AppContextSwitchNames.cs
  src/Common/tests/TestUtilities/BinaryFormatterInClipboardDragDropScope.cs
  src/Common/tests/TestUtilities/NrbfSerializerInClipboardDragDropScope.cs
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/MyServices/ClipboardProxy.vb
  src/Microsoft.VisualBasic.Forms/src/Obsoletions.vb
  src/Microsoft.VisualBasic.Forms/src/PublicAPI.Unshipped.txt
  src/Microsoft.VisualBasic/tests/UnitTests/Microsoft/VisualBasic/MyServices/ClipboardProxyTests.cs
  src/System.Private.Windows.Core/src/System/Private/Windows/Core/Nrbf/SerializationRecordExtensions.cs
  src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
  src/System.Windows.Forms/src/GlobalSuppressions.cs
  src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Internal/Formatter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Internal/TypeExtensions.cs
  src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
  src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.BinaryFormatUtilities.cs
  src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.Binder.cs
  src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.NativeToWinFormsAdapter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.TypeNameComparer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.cs
  src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.DataStore.cs
  src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObjectExtensions.cs
  src/System.Windows.Forms/src/System/Windows/Forms/OLE/IDataObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/OLE/ITypedDataObject.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DesignBehaviorsTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/runtimeconfig.template.json
  src/System.Windows.Forms/tests/UnitTests/System.Windows.Forms.Tests.csproj
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/BinaryFormat/WinFormsBinaryFormattedObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/BinaryFormatUtilitiesTests.BinaryFormatterFullCompatScope.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/BinaryFormatUtilitiesTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ClipboardTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataObjectExtensionsTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataObjectTests.ClipboardTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DragDropHelperTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/NativeToWinFormsAdapterTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.ClipboardTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TypeExtensionsTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TypeNameComparerTests.cs
Labels: draft

#12622 Add code coverage for DataGridViewCellConverter
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellConverterTests.cs
Labels: ready-to-merge

#12651 Add MSAA event to method OnGotFocus of the Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/PropertyGridView.GridViewTextBox.cs
Labels: ready-to-merge

#12613 Avoids a `System.InvalidCastException` error to be thrown when passing `ObjectCollection` to `AddRangeInternal` of the `DataGridViewComboBoxCell.ObjectCollection` class
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewComboBoxCell.ObjectCollection.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewComboBoxCell.ObjectCollectionTests.cs
Labels: ready-to-merge
