Repository dotnet/winforms, pull requests merged in 2024-10, with the labels that each got.

#12246 [release/9.0] Extra Border Color in DataGridView with RightToLeft layout
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewRow.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewRowTests.cs
Labels: Servicing-approved

#12216 [release/8.0] Avoid Creating Graphics in TabControl.WmReflectDrawItem()
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
Labels: Servicing-approved

#12175 Configure repo for Central Package Management
  Directory.Build.targets
  Directory.Packages.props
  NuGet.config
  eng/ApiCompatibility/PublicApiAnalyzer.targets
  eng/CodeCoverage.proj
  eng/CodeStyle.targets
  eng/FacadeAssemblies.props
  eng/Test.props
  eng/Versions.props
  eng/common/internal/Tools.csproj
  src/Common/tests/TestUtilities/System.Windows.Forms.Common.TestUtilities.csproj
  src/Microsoft.VisualBasic/tests/UnitTests/Microsoft.VisualBasic.Tests.csproj
  src/System.Drawing.Common/src/System.Drawing.Common.csproj
  src/System.Drawing.Common/tests/System.Drawing.Common.Tests.csproj
  src/System.Drawing/src/System.Drawing.Facade.csproj
  src/System.Private.Windows.Core/src/System.Private.Windows.Core.csproj
  src/System.Private.Windows.Core/tests/BinaryFormatTests/BinaryFormatTests.csproj
  src/System.Private.Windows.Core/tests/System.Private.Windows.Core.Tests/System.Private.Windows.Core.Tests.csproj
  src/System.Windows.Forms.Analyzers.CSharp/src/System.Windows.Forms.Analyzers.CSharp.csproj
  src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System.Windows.Forms.Analyzers.CSharp.Tests.csproj
  src/System.Windows.Forms.Analyzers.CodeFixes.CSharp/System.Windows.Forms.Analyzers.CodeFixes.CSharp.csproj
  src/System.Windows.Forms.Analyzers.CodeFixes.VisualBasic/System.Windows.Forms.Analyzers.CodeFixes.VisualBasic.vbproj
  src/System.Windows.Forms.Analyzers.VisualBasic/System.Windows.Forms.Analyzers.VisualBasic.vbproj
  src/System.Windows.Forms.Analyzers.VisualBasic/src/System.Windows.Forms.Analyzers.VisualBasic.vbproj
  src/System.Windows.Forms.Analyzers.VisualBasic/tests/UnitTests/System.Windows.Forms.Analyzers.VisualBasic.Tests/System.Windows.Forms.Analyzers.VisualBasic.Tests.vbproj
  src/System.Windows.Forms.Analyzers/src/System.Windows.Forms.Analyzers.csproj
  src/System.Windows.Forms.Analyzers/tests/UnitTests/System.Windows.Forms.Analyzers.Tests.csproj
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/CommandSet.cs
  src/System.Windows.Forms.Design/tests/UnitTests/System.Windows.Forms.Design.Tests.csproj
  src/System.Windows.Forms.Primitives/src/System.Windows.Forms.Primitives.csproj
  src/System.Windows.Forms.Primitives/tests/TestUtilities/System.Windows.Forms.Primitives.TestUtilities.csproj
  src/System.Windows.Forms.Primitives/tests/UnitTests/System.Windows.Forms.Primitives.Tests.csproj
  src/System.Windows.Forms.PrivateSourceGenerators/src/System.Windows.Forms.PrivateSourceGenerators.csproj
  src/System.Windows.Forms.PrivateSourceGenerators/tests/UnitTests/System.Windows.Forms.PrivateSourceGenerators.Tests.csproj
  src/System.Windows.Forms/src/System.Windows.Forms.csproj
  src/System.Windows.Forms/src/System/Resources/AssemblyNamesTypeResolutionService.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataBinding/BindingSource.cs
  src/System.Windows.Forms/tests/ComDisabledTests/ComDisabled.Tests.csproj
  src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/DemoConsole.csproj
  src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/System.Windows.Forms.IntegrationTests.Common.csproj
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/System.Windows.Forms.UI.IntegrationTests.csproj
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/WinformsControlsTest.csproj
  src/System.Windows.Forms/tests/TestUtilities/System.Windows.Forms.TestUtilities.csproj
  src/System.Windows.Forms/tests/UnitTests/System.Windows.Forms.Tests.csproj
Labels: ready-to-merge

#12141 Adds XML Comments to FileSystemProxy and SpecialDirectoriesProxy
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/MyServices/FileSystemProxy.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/MyServices/SpecialDirectoriesProxy.vb
Labels: ready-to-merge

#12289 [release/8.0] Ensure proper ref count of underlying ocx
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHostTests.cs
Labels: Servicing-approved

#12199 Add unit tests for ItemTypeToolStripMenuItem
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ItemTypeToolStripMenuItem.cs
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ItemTypeToolStripMenuItemTests.cs
Labels: ready-to-merge

#12261 Add unit tests for SingleInstanceHelper and fix formatting from simplifying PR #11863
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/SingleInstanceHelpers.vb
  src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/SingleInstanceHelpersTests.vb
Labels: ready-to-merge

#12282 Fixes the `Remove()` and `IndexOf()` methods in the `ImageListDesigner.OriginalImageCollection` class and adds coverage to it
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ImageListDesigner.OriginalImageCollection.cs
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ImageListDesignerOriginalImageCollectionTests.cs
Labels: ready-to-merge

#12342 [release/8.0] Fix ConnectionPointCookie usages
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.OleInterfaces.cs
  src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserSiteBase.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHostTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/WebBrowserTests.cs
Labels: Servicing-approved

#12269 Add test for SplitterPanelDesigner.cs
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/SplitterPanelDesignerTests.cs
Labels: ready-to-merge

#12337 Add unit tests for DesignerExtenders
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/DesignerExtendersTests.cs
Labels: ready-to-merge

#12249 Remove older feeds
  NuGet.config
  eng/Versions.props
Labels: :mailbox_with_no_mail: waiting-author-feedback

#12366 Add unit tests for ToolStripContentPanelDesigner
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ToolStripContentPanelDesignerTests.cs
Labels: waiting-review

#12347 Add code coverage for ToolStripComboBox
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripComboBoxTests.cs
Labels: ready-to-merge

#12385 Modified the test case to ensure corresponding constructor is called
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripStatusLabelTests.cs
Labels: waiting-review

#12226 Split Network.VB into 7 Files from PR #11863
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Network.Availability.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Network.DownloadFile.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Network.Ping.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Network.UploadFile.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Network.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/NetworkAvailableEventArgs.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/NetworkUtilities.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/WebClientExtended.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Logging/FileLogTraceListener.Properties.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/MyServices/Internal/WebClientCopy.vb
Labels: ready-to-merge
