Repository dotnet/winforms, pull requests merged in 2024-06, with the labels that each got.

#11472 Enable nullability in ImageListImage
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ImageListImage.cs
Labels: area: NRT

#11464 Add Code Coverage For ToolStrip
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/ToolStripDropDownButton.ToolStripDropDownButtonAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripCustomIComparerTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripDropDownTests.cs
  src/System.Windows.Forms/tests/UnitTests/ToolStripContainerTests.cs
Labels: waiting-review

#11407 Get TrimTest to 0 trim warnings
  src/System.Windows.Forms.Primitives/src/System/ComponentModel/TypeConverterHelper.cs
  src/System.Windows.Forms/src/Resources/SR.resx
  src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms/src/System/Drawing/Design/UITypeEditor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ActiveX/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/Buttons/ButtonBase.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ListControl/ListControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/OpacityConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripMenuItem.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataBinding/BindableComponent.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataBinding/Binding.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataBinding/BindingContext.cs
  src/System.Windows.Forms/src/System/Windows/Forms/DataBinding/IBindableComponent.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ImageIndexConverter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Internal/Formatter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Layout/Containers/ContainerControl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Layout/Containers/SplitContainer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/MDI/MDIWindowDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Panels/TableLayoutPanel/TableLayoutSettings.cs
  src/System.Windows.Forms/tests/ComDisabledTests/Control.ActiveXImplTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/TrimTest/TrimTest.csproj
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Control.ActiveXImplTests.cs
Labels: :books: documentation

#11425 Enable nullability in some ControlDesigner members
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ImageListDesigner.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TextBoxBaseDesigner.cs
Labels: ready-to-merge, area: NRT

#11432 add InheritedPropertyDescriptor unit tests
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/InheritedPropertyDescriptorTestExtensions.cs
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/InheritedPropertyDescriptorTests.cs
Labels: waiting-review

#11423 8768 :: Resolve Addrange issue after sorting.
  src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/TreeView/TreeNodeCollection.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNodeCollectionTests.cs
Labels: waiting-review

#11519 Add code coverage for monthcalendar
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/MonthCalendar.CalendarButtonAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/MonthCalendar.CalendarRowAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs
Labels: ready-to-merge

#11521 Add code coverage for LabelAccessibleObject
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/LabelAccessibleObjectTests.cs
Labels: ready-to-merge

#11522 Add test coverage for NumericUpDown
  src/System.Windows.Forms/tests/UnitTests/NumericUpDownTests.cs
Labels: waiting-review

#11539 Replacing usages of `LocalAppContextSwitches` with `AppContextSwitchScope`
  src/Common/tests/TestUtilities/AnchorLayoutV2Scope.cs
  src/Common/tests/TestUtilities/AppContextSwitchNames.cs
  src/Common/tests/TestUtilities/ApplyParentFontToMenusScope.cs
  src/Common/tests/TestUtilities/BinaryFormatterScope.cs
  src/Common/tests/TestUtilities/DataGridViewUIAStartRowCountAtZeroScope.cs
  src/Common/tests/TestUtilities/NoClientNotificationsScope.cs
  src/Common/tests/TestUtilities/ScaleTopLevelFormMinMaxSizeForDpiScope.cs
  src/Common/tests/TestUtilities/ServicePointManagerCheckCrlScope.cs
  src/Common/tests/TestUtilities/TreeNodeCollectionAddRangeRespectsSortOrderScope.cs
  src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
  src/System.Windows.Forms.Primitives/tests/TestUtilities/TargetFrameworkNameScope.cs
  src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/LocalAppContextSwitchesTest.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/AnchorLayoutTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Dpi/FormDpiTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/MessageBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/DataGridViewCellAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/DataGridViewRowAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PictureBoxTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNodeCollectionTests.cs
Labels: ready-to-merge

#11541 Add unit test case for DataGridView 10 events
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTests.cs
Labels: waiting-review

#11523 Create AccessibleObject for PrintStatusDialog
  src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintControllerWithStatusDialog.BackgroundThread.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintControllerWithStatusDialog.StatusDialog.cs
Labels: ready-to-merge

#11375 Fix `ToolboxBitmapAttribute` to improve error tolerance and better support `PNG` based `ICO` embedded resources
  src/System.Drawing.Common/src/System/Drawing/ToolboxBitmapAttribute.cs
Labels: ready-to-merge

#11555 Fix missing types in System.Drawing.Common netframework facade
  src/System.Drawing.Common/src/CompatibilitySuppressions.xml
  src/System.Drawing.Common/src/Special/Forwards.cs
Labels: waiting-review

#11542 use HttpClient to replace WebClient
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PictureBox/PictureBox.cs
Labels: :book: documentation: breaking, ready-to-merge

#11534 Updated 6 unit test cases to fully coverage code lines in DateTimePicker
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DateTimePickerTests.cs
Labels: waiting-review

#11565 Add code coverage for combobox
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
Labels: waiting-review

#11556 Add unit test case for DataGridView 16 events
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTests.cs
Labels: waiting-review

#11594 Add span overloads to GraphicsPathIterator
  src/System.Drawing.Common/src/CompatibilitySuppressions.xml
  src/System.Drawing.Common/src/System/Drawing/Drawing2D/GraphicsPathIterator.cs
  src/System.Drawing.Common/tests/System/Drawing/Drawing2D/GraphicsPathIteratorTests.cs
Labels: waiting-review
