Repository dotnet/winforms, pull requests merged in 2024-07, with the labels that each got.

#11590 [release/6.0] Switch to dSAS for internal runtimes
  NuGet.config
  azure-pipelines-PR.yml
  azure-pipelines.yml
  eng/Version.Details.xml
  eng/Versions.props
  eng/common/templates-official/job/source-build.yml
  eng/common/templates-official/job/source-index-stage1.yml
  eng/common/templates-official/jobs/source-build.yml
  eng/common/templates-official/post-build/common-variables.yml
  eng/common/templates-official/steps/enable-internal-runtimes.yml
  eng/common/templates-official/steps/get-delegation-sas.yml
  eng/common/templates-official/steps/get-federated-access-token.yml
  eng/common/templates/job/source-build.yml
  eng/common/templates/job/source-index-stage1.yml
  eng/common/templates/jobs/source-build.yml
  eng/common/templates/post-build/common-variables.yml
  eng/common/templates/steps/enable-internal-runtimes.yml
  eng/common/templates/steps/get-delegation-sas.yml
  eng/common/templates/steps/get-federated-access-token.yml
  eng/pipelines/build-PR.yml
  eng/pipelines/build.yml
  global.json
Labels: :no_entry_sign: * NO-MERGE *

#11591 [release/8.0] Switch to dSAS for internal runtimes
  NuGet.config
  azure-pipelines-PR.yml
  azure-pipelines.yml
  eng/Version.Details.xml
  eng/Versions.props
  eng/common/post-build/publish-using-darc.ps1
  eng/common/templates-official/job/publish-build-assets.yml
  eng/common/templates-official/job/source-build.yml
  eng/common/templates-official/job/source-index-stage1.yml
  eng/common/templates-official/jobs/source-build.yml
  eng/common/templates-official/post-build/post-build.yml
  eng/common/templates-official/steps/enable-internal-runtimes.yml
  eng/common/templates-official/steps/get-delegation-sas.yml
  eng/common/templates-official/steps/get-federated-access-token.yml
  eng/common/templates/job/publish-build-assets.yml
  eng/common/templates/job/source-build.yml
  eng/common/templates/job/source-index-stage1.yml
  eng/common/templates/jobs/source-build.yml
  eng/common/templates/post-build/post-build.yml
  eng/common/templates/post-build/setup-maestro-vars.yml
  eng/common/templates/steps/enable-internal-runtimes.yml
  eng/common/templates/steps/get-delegation-sas.yml
  eng/common/templates/steps/get-federated-access-token.yml
  eng/pipelines/build-PR.yml
  eng/pipelines/build.yml
  global.json
Labels: :no_entry_sign: * NO-MERGE *

#11606 Move all Clipboard related tests to a new class and remove SkipOnArchitecture label
  src/System.Windows.Forms/tests/UnitTests/TextBoxBaseTests.ClipboardTests.cs
  src/System.Windows.Forms/tests/UnitTests/TextBoxBaseTests.cs
Labels: ready-to-merge

#11618 Add unit test case for DataGridView 7 events
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTests.cs
Labels: ready-to-merge

#11624 Add test coverage for ListBox
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBoxTests.cs
Labels: waiting-review

#11520 Make the toolbar menu items support the support space key.
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripDropDown.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripMenuItem.ToolStripMenuItemAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripMenuItem.cs
Labels: ready-to-merge

#10593 Modify the accessibility of ToolStripItem's "Renderer" to enable subclasses to set custom renderers and reuse OnPaint logic
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripItem.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemTests.cs
Labels: ready-to-merge

#11656 Fix NullReferenceException when clicking the help button in TreeView smarttag
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/CollectionEditor.PropertyGridSite.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TreeNodeCollectionEditor.cs
  src/System.Windows.Forms.Design/tests/UnitTests/TreeNodeCollectionEditorTests.cs
Labels: ready-to-merge

#11674 Refactor `CategoryGridEntry` to replace Dictionary and lock object with `ConcurrentDictionary`
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/CategoryGridEntry.cs
Labels: ready-to-merge

#11688 Add unit tests for GroupBox
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/GroupBoxTests.cs
Labels: waiting-review

#11705 Shortened some nested classes names.
  src/System.Windows.Forms/src/GlobalSuppressions.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ActiveX/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.NativeToRuntimeAdapter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.NativeToWinFormsAdapter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.RuntimeToNativeAdapter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.WinFormsToNativeAdapter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.cs
  src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
Labels: :octocat: automerge

#11703 Add test code coverage for MaskDescriptor
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/MaskDescriptorTests.cs
Labels: waiting-review

#11715 Shortened a nested class name
  src/System.Windows.Forms/src/GlobalSuppressions.cs
  src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.NativeToRuntimeAdapter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.cs
Labels: waiting-review

#11678 Adds new tab to on DemoConsole, to contain instances of missing desig…
  src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.MyScrollableControl.cs
  src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.MyUserControl.cs
  src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.cs
Labels: waiting-review

#11513 Enable nullability in remaining ControlDesigner members
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs
Labels: area: NRT

#11298 Enable nullability in TransparentBehavior
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/ControlBodyGlyph.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.TransparentBehavior.cs
Labels: area: NRT

#11716 add Verify settings to editorconfig
  .editorconfig
Labels: waiting-review

#11725 Add unit test for ImageListDesigner
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ImageListDesignerTests.cs
Labels: ready-to-merge

#11736 Add unit test for ImageListImage
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ImageListImageTests.cs
Labels: ready-to-merge

#11737 Add tests for MaskedTextBoxTextEditor
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/MaskedTextBoxTextEditorTests.cs
Labels: ready-to-merge

#11741 Add binary Formatter package to DemoConsole
  src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/DemoConsole.csproj
Labels: ready-to-merge

#11712 Add tests for ListBoxDesigner
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ListBoxDesigner.cs
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ListBoxDesignerTests.cs
Labels: ready-to-merge

#11502 fix issue 11450 Color contrast ratio of focus indicator over 'toolStripSplitButton1' is 1.247:1 which is less than 3:1: A11y_.NET CoreWinforms_StripControls_Toolstripwithmenuitem_NonTextContrast
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/StatusStrip.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/StatusStripTests.cs
Labels: ready-to-merge

#11743 Add code coverage for MaskDescriptorTemplate
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/MaskDescriptorTemplateTests.cs
Labels: ready-to-merge

#11345 Visual Styles enabled or disabled, remove differentiation for border style in the left side of the row header when the style would have been set to `Outset`
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridView.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewRow.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewRowTests.cs
Labels: ready-to-merge
