Repository dotnet/winforms, pull requests merged in 2024-08, with the labels that each got.

#11732 Adjusting the counter to fix the naming errors in DemoConsole App
  src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DesignSurfaceExt/NameCreationServiceImp.cs
Labels: waiting-review

#11679 Do not crash when an invalid VirtualMode==true ListView is destroyed
  src/System.Windows.Forms/src/Resources/SR.resx
  src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ListView/ListView.ListViewItemCollection.IInnerList.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ListView/ListView.ListViewItemCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ListView/ListView.ListViewNativeItemCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ListView/ListView.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Labels: :mailbox_with_no_mail: waiting-author-feedback

#11766 Add unit test for image list action list
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ImageListActionListTests.cs
Labels: waiting-review

#11773 Add code coverage for toolstrip
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
Labels: waiting-review

#11785 Add a manual test case for clones ListViewItem to WinformsControlsApp
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/CloneTestListView.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListViewTest.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListViewTest.cs
Labels: ready-to-merge

#11848 Add code coverage for ToolStripTextBox
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTextBoxTests.cs
Labels: ready-to-merge

#11892 Fix OnItemChecked method throw exception when the ListViewItem is clone object.
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ListView/ListView.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/CloneTestListView.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Labels: ready-to-merge

#11923 [RC1/9.0] Backport SecAnalyzer (11904)
  src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/Analyzers/MissingPropertySerializationConfiguration/ControlPropertySerializationDiagnosticAnalyzerTest.cs
  src/System.Windows.Forms.Analyzers.CodeFixes.CSharp/System/Windows/Forms/CSharp/CodeFixes/AddDesignerSerializationVisibility/AddDesignerSerializationVisibilityCodeFixProvider.cs
  src/System.Windows.Forms.Analyzers.CodeFixes.VisualBasic/AddDesignerSerializationVisibility/AddDesignerSerializationVisibilityCodeFixProvider.vb
  src/System.Windows.Forms.Analyzers.VisualBasic/tests/UnitTests/System.Windows.Forms.Analyzers.VisualBasic.Tests/MissingPropertySerializationConfigurationAnalyzerTest.vb
Labels: Servicing-approved

#11924 [RC1/9.0] Backport Dark Mode fix
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/WindowsFormsApplicationBase.vb
  src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ApplicationTests.cs
Labels: Servicing-approved

#11930 [RC1/9.0] Backport MenuItemFix
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripDropDown.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripMenuItem.ToolStripMenuItemAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripMenuItem.cs
Labels: Servicing-approved

#11767 Mark the Form.OnClosed and OnClosing methods with the ObsoleteAttribute
  docs/list-of-diagnostics.md
  src/Common/src/Obsoletions.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.EditorPropertyLine.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewAddColumnDialog.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewColumnCollectionDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
  src/System.Windows.Forms/src/System/Windows/Forms/FormClosedEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/FormClosingEventArgs.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewDialog.cs
Labels: :books: documentation, ready-to-merge

#11363 fix winforms-designer/issues/2707 The comboBox incorrect display on form designer when setting its DropDownStyle as Simple after building the project
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
Labels: ready-to-merge

#11889 Sort VB Functions, Clean up XML Comments
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/ApplicationBase.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/ApplyApplicationDefaultsEventArgs.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/AssemblyInfo.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/CantStartSingleInstanceException.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/ConsoleApplicationBase.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/NoStartupFormException.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/SingleInstanceHelpers.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/StartupEventArgs.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/User.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/WindowsFormsApplicationBase.AuthenticationMode.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/WindowsFormsApplicationBase.ShutdownMode.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/WindowsFormsApplicationBase.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/CompilerServices/ExceptionUtils.VbErrors.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/CompilerServices/ExceptionUtils.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Audio.AudioPlayMode.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Audio.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Clock.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Computer.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/ComputerInfo.ComputerInfoDebugView.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/ComputerInfo.InternalMemoryStatus.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/ComputerInfo.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Keyboard.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Mouse.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Network.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/ServerComputer.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Helpers/FileSystemUtils.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Helpers/NativeMethods.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Helpers/NativeTypes.PROCESS_INFORMATION.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Helpers/NativeTypes.SECURITY_ATTRIBUTES.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Helpers/NativeTypes.STARTUPINFO.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Helpers/NativeTypes.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Helpers/SafeNativeMethods.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Helpers/UnsafeNativeMethods.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Helpers/VBInputBox.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Interaction.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Logging/FileLogTraceListener.ReferencedStream.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Logging/FileLogTraceListener.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Logging/Log.DefaultTraceSource.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Logging/Log.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Logging/Logging.DiskSpaceExhaustedOption.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Logging/Logging.LogFileCreationScheduleOption.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Logging/Logging.LogFileLocation.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/MyServices/ClipboardProxy.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/MyServices/FileSystemProxy.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/MyServices/Internal/ContextValue.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/MyServices/Internal/ProgressDialog.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/MyServices/Internal/WebClientCopy.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/MyServices/RegistryProxy.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/MyServices/SpecialDirectoriesProxy.vb
Labels: ready-to-merge

#11955 Add unit tests for MaskPropertyEditor
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/MaskPropertyEditorTests.cs
Labels: ready-to-merge

#11926 Update the TextFormatFlags of the HelpTextLabel
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignBindingPicker.cs
Labels: ready-to-merge

#11970 Move the remaining clipboard-related tests under System.Windows.Form.Tests to the new class
  src/Microsoft.VisualBasic/tests/UnitTests/Microsoft/VisualBasic/MyServices/ClipboardProxyTests.cs
  src/System.Windows.Forms/tests/ComDisabledTests/ClipboardComTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ClipboardTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataFormatsTests.ClipboardTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataFormatsTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataObjectTests.ClipboardTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DragDropFormatTests.cs
Labels: ready-to-merge

#11973 Adds code coverage to FolderNameEditor
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/FolderNameEditorTests.cs
Labels: ready-to-merge
