Repository dotnet/winforms, pull requests merged in 2024-09, with the labels that each got.

#11912 fix issue #11862 The DemoConsole application in the Winforms repo sto…
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionUI.cs
Labels: ready-to-merge

#12043 Add code coverage for toolStripStatusLabel
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripStatusLabelTests.cs
Labels: waiting-review

#12035 Add unit tests for CustomMenuItemCollection
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/CustomMenuItemCollectionTests.cs
Labels: ready-to-merge

#12052 Cleanup SelectionManager long lines and spelling issues
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/SelectionManager.cs
Labels: ready-to-merge

#11964 Add UI test for MenuItem about Space key
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripDropDown.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/MenuStripTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MenuStripAndCheckedListBox.Designer.cs
  src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ToolStripTests.Designer.cs
Labels: ready-to-merge

#12046 Set IsDialog property and AccessibleName property for StatusDialog
  src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintControllerWithStatusDialog.StatusDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Printing/StatusDialogAccessibility.cs
Labels: ready-to-merge

#12032 Add Clipboard.Clear(); at the end of the tests
  src/System.Windows.Forms/tests/UnitTests/TextBoxBaseTests.ClipboardTests.cs
Labels: ready-to-merge

#12045 fix issue #11450 scenario 2. Color contrast ratio of focus indicator over 'toolStripSplitButton1' is 1.247:1 which is less than 3:1: A11y_.NET CoreWinforms_StripControls_Toolstripwithmenuitem_NonTextContrast
  src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewDialog.cs
Labels: ready-to-merge

#11724 Add code coverage for ListBoxAccessibleObject and ListBoxItemAccessib…
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ListBoxAccesibleObjectTests.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ListBoxItemAccessibleObjestTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/ListBox.ListBoxItemAccessibleObjectTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/ListBoxAccessibleObjectTests.cs
Labels: waiting-review

#12060 Fixes term due to compliance
  src/System.Windows.Forms/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/WebBrowser/HtmlElement.cs
Labels: :book: documentation: breaking, waiting-review

#12063 Shorten more lines
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Logging/FileLogTraceListener.vb
  src/System.Drawing.Common/src/Windows/Win32/PInvoke.SHGetStockIconInfo.cs
  src/System.Private.Windows.Core/src/System/Private/Windows/Core/BinaryFormat/BinaryType.cs
  src/System.Private.Windows.Core/src/System/Private/Windows/Core/BinaryFormat/ClassRecord.cs
  src/System.Private.Windows.Core/src/System/Private/Windows/Core/BinaryFormat/RecordType.cs
  src/System.Private.Windows.Core/src/Windows/Win32/Graphics/Gdi/CreateBitmapScope.cs
  src/System.Private.Windows.Core/src/Windows/Win32/System/Com/IManagedWrapper.cs
  src/System.Private.Windows.Core/src/Windows/Win32/System/Com/SafeArrayScope.cs
  src/System.Private.Windows.Core/src/Windows/Win32/UI/Controls/Dialogs/DEVNAMES.cs
  src/System.Private.Windows.Core/src/Windows/Win32/UI/Controls/Dialogs/PRINTDLGEXW.cs
  src/System.Private.Windows.Core/src/Windows/Win32/UI/Controls/Dialogs/PRINTPAGERANGE.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionListsChangedType.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionUIService.cs
  src/System.Windows.Forms.Primitives/src/Microsoft/Office/IMsoComponent.cs
  src/System.Windows.Forms.Primitives/src/Microsoft/Office/IMsoComponentManager.cs
  src/System.Windows.Forms.Primitives/src/Microsoft/VisualStudio/Shell/IProvidePropertyBuilder.cs
  src/System.Windows.Forms.Primitives/src/System/Diagnostics/TraceSwitchExtensions.cs
  src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/AccessibiltyExtensions.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Automation/UiaTextProvider.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Automation/UiaTextRange.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/HighDpiMode.cs
  src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/ScaleHelper.cs
  src/System.Windows.Forms.Primitives/src/Windows/Win32/Foundation/COLORREF.cs
  src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.MaxClassName.cs
  src/System.Windows.Forms.Primitives/src/Windows/Win32/SetTextAlignmentScope.cs
  src/System.Windows.Forms.Primitives/src/Windows/Win32/System/Com/ComSafeArrayScope.cs
  src/System.Windows.Forms.Primitives/src/Windows/Win32/System/Com/ComSafeArrayScopeExtensions.cs
  src/System.Windows.Forms.Primitives/src/Windows/Win32/System/Ole/ClassPropertyDispatchAdapter.cs
  src/System.Windows.Forms.Primitives/src/Windows/Win32/UI/Accessibility/UIAHelper.cs
  src/System.Windows.Forms.Primitives/src/Windows/Win32/UI/Controls/Dialogs/CHOOSECOLORW.cs
  src/System.Windows.Forms.Primitives/src/Windows/Win32/UI/Controls/Dialogs/CHOOSEFONTW.cs
  src/System.Windows.Forms.Primitives/src/Windows/Win32/UI/Controls/Dialogs/PAGESETUPDLGW.cs
  src/System.Windows.Forms.Primitives/src/Windows/Win32/UI/Controls/Dialogs/PRINTDLGW_64.cs
  src/System.Windows.Forms.Primitives/tests/TestUtilities.Tests/PathLengthTests.cs
  src/System.Windows.Forms/src/System/Resources/ResXResourceReader.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Accessibility/AccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Accessibility/AccessibleObjectExtensions.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ActiveX/Control.ActiveXImpl.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Dialogs/CommonDialogs/FileDialog.Vista.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Dialogs/TaskDialog/TaskDialog.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Input/InputLanguage.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/DataCollectionService.cs
  src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ScreenRecordService.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ApplicationTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/BinaryFormatUtilitiesTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/InputLanguageTests.cs
Labels: ready-to-merge

#12082 Add code coverage for ToolStripSplitStackDragDropHandler
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripSplitStackDragDropHandlerTests.cs
Labels: waiting-review

#11982 Modernize VB ExceptionUtils add Test Coverage, fix Time Tests REVIEW 1st
  src/Microsoft.VisualBasic.Forms/src/GlobalSuppressions.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/Properties/AssemblyInfo.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/CantStartSingleInstanceException.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/NoStartupFormException.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/WindowsFormsApplicationBase.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/CompilerServices/ExceptionUtils.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/CompilerServices/Utils.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Audio.AudioPlayMode.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Audio.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Computer.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/ComputerInfo.ComputerInfoDebugView.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/ComputerInfo.InternalMemoryStatus.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Keyboard.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Network.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Helpers/IVbHost.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Helpers/UnsafeNativeMethods.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Helpers/VBInputBox.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Interaction.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Logging/FileLogTraceListener.ReferencedStream.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/MyServices/FileSystemProxy.vb
  src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/AssemblyPublicKeyIsAsExpectedTest.vb
  src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/ControlInvokeTests.vb
  src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/ExceptionUtilsTests.vb
  src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/TestUtilitiesTests.vb
  src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/TimeTests.vb
  src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/TestUtilities/TestData/DualTimeZones.TimeZone.vb
  src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/TestUtilities/TestData/DualTimeZones.vb
  src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/TestUtilities/TestData/TimeTestData.vb
  src/Microsoft.VisualBasic/tests/UnitTests/Microsoft/VisualBasic/Devices/ComputerTests.cs
  src/Microsoft.VisualBasic/tests/UnitTests/Microsoft/VisualBasic/Logging/FileLogTraceListenerTests.cs
Labels: ready-to-merge

#12095 Add unit tests for TextBoxDesigner
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/TextBoxDesignerTests.cs
Labels: waiting-review

#12070 Notify the drag-image manager prior to invoking the DragDrop and DragLeave events
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/RichTextBox/RichTextBox.OleCallback.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripDropTargetManager.cs
  src/System.Windows.Forms/src/System/Windows/Forms/OLE/DropTarget.cs
Labels: ready-to-merge

#11358 Fix ToolStrip memory leak due to MouseHoverTimer and #4808
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripItemCollection.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Input/MouseHoverTimer.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
Labels: waiting-review

#12131 Add code coverage for RichTextBoxActionList
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/RichTextBoxActionListTests.cs
Labels: waiting-review

#12168 Adds code coverage to FormatControl
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/FormatControlTests.cs
Labels: waiting-review

#12193 [release/9.0] Fix GetFormats and GetDataPresent
  src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.NativeToWinFormsAdapter.cs
Labels: Servicing-approved

#12192 [release/9.0] Clear Clipboard Correctly
  src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
Labels: Servicing-approved

#12185 Adds code coverage to FormatStringDialog
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/FormatStringDialogTests.cs
Labels: waiting-review
