Repository dotnet/winforms, pull requests merged in 2025-07, with the labels that each got.

#13642 Extend DarkMode opt-out option for multiple descendant scenarios.
  src/System.Windows.Forms/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/System/Windows/Forms/Controls/Buttons/Button.cs
  src/System.Windows.Forms/System/Windows/Forms/Controls/ListView/ListView.cs
  src/System.Windows.Forms/System/Windows/Forms/Controls/TextBox/TextBoxBase.cs
Labels: area-DarkMode

#13667 Add code coverage for DataGridViewButtonCell
  src/test/unit/System.Windows.Forms/System/Windows/Forms/DataGridViewButtonCellTests.cs
Labels: waiting-review, area-test coverage

#13682 Add unit test for ListView.CheckedIndexCollection file
  src/test/unit/System.Windows.Forms/System/Windows/Forms/ListView.CheckedIndexCollectionTests.cs
Labels: waiting-review, area-test coverage

#13654 Add code coverage for DataGridViewComboBoxCell
  src/test/unit/System.Windows.Forms/System/Windows/Forms/DataGridViewComboBoxCellTests.cs
Labels: waiting-review, area-test coverage

#13685 Add unit test for ListView.CheckedListViewItemCollection file
  src/test/unit/System.Windows.Forms/System/Windows/Forms/ListView.CheckedListViewItemCollectionTests.cs
Labels: waiting-review, area-test coverage

#13683 Update xunit.v3 to 3.0.0
  eng/Versions.props
Labels: area-Infrastructure

#13702 [release/8.0] FontStyle.Bold Not Visually Applied to LinkLabel at Runtime via Code
  src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewLinkCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/LinkUtilities.cs
Labels: servicing-approved

#13703 [release/9.0] FontStyle.Bold Not Visually Applied to LinkLabel at Runtime via Code
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewLinkCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/Labels/LinkUtilities.cs
Labels: servicing-approved

#13684 Update SetScreenCaptureModeInternal by reset WINDOW_DISPLAY_AFFINITY to NONE before setting new affinity
  src/System.Windows.Forms/System/Windows/Forms/Form.cs
Labels: waiting-review, needs-area-label

#13691 Add code coverage for ToolStripProfessionalLowResolutionRenderer
  src/test/unit/System.Windows.Forms/System/Windows/Forms/ToolStripProfessionalLowResolutionRendererTests.cs
Labels: waiting-review, area-test coverage

#13715 Do not activate the form if MinimumSize changes
  src/System.Windows.Forms/System/Windows/Forms/Form.cs
  src/test/integration/UIIntegrationTests/FormTests.cs
Labels: needs-area-label

#13734 Add Version.Details.props
  eng/Version.Details.props
Labels: area-Infrastructure

#13712 Add judgement for test ListView_Click_On_Second_Column_Does_Not_Alter_CheckBoxesAsync
  src/test/integration/UIIntegrationTests/ListViewTests.cs
Labels: area-Infrastructure

#13713 Add code coverage for MultiPropertyDescriptorGridEntry
  src/test/unit/System.Windows.Forms/System/Windows/Forms/MultiPropertyDescriptorGridEntryTests.cs
Labels: waiting-review, area-test coverage

#13721 DarkMode (b): Fix rendering of disabled TextBox types
  src/System.Windows.Forms/System/Windows/Forms/Control.cs
  src/System.Windows.Forms/System/Windows/Forms/Controls/Buttons/Button.cs
  src/System.Windows.Forms/System/Windows/Forms/Controls/ComboBox/ComboBox.cs
  src/System.Windows.Forms/System/Windows/Forms/Controls/ListView/ListView.cs
  src/System.Windows.Forms/System/Windows/Forms/Controls/RichTextBox/RichTextBox.cs
  src/System.Windows.Forms/System/Windows/Forms/Controls/TextBox/TextBoxBase.cs
Labels: area-DarkMode

#13748 [Preview7/Release] Backport 13747 DarkMode: SystemControlButton rendering
  src/System.Windows.Forms/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/DropDownButton.cs
  src/System.Windows.Forms/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/PropertyGridView.cs
  src/System.Windows.Forms/System/Windows/Forms/Controls/UpDown/UpDownBase.UpDownButtons.cs
  src/System.Windows.Forms/System/Windows/Forms/Controls/UpDown/UpDownBase.cs
  src/System.Windows.Forms/System/Windows/Forms/Rendering/ControlPaint.ModernControlButton.cs
  src/System.Windows.Forms/System/Windows/Forms/Rendering/ControlPaint.ModernControlButtonState.cs
  src/System.Windows.Forms/System/Windows/Forms/Rendering/ControlPaint.cs
  src/System.Windows.Forms/System/Windows/Forms/Rendering/ControlPaint_ModernControlButtonRenderer.cs
Labels: :no_entry_sign: * NO-MERGE *, servicing-approved, area-DarkMode

#13731 Add code coverage for ButtonPopupAdapter
  src/test/unit/System.Windows.Forms/System/Windows/Forms/ButtonPopupAdapterTests.cs
Labels: waiting-review, area-test coverage

#13733 Update stafact to latest stable
  eng/Versions.props
Labels: area-Infrastructure
