Repository dotnet/winforms, pull requests merged in 2025-09, with the labels that each got.

#13818 fix #13813 : Dark Mode: The ForeColor & BackColor properties are not working for the controls
  src/System.Windows.Forms/PublicAPI.Unshipped.txt
  src/System.Windows.Forms/System/Windows/Forms/Controls/Buttons/ButtonBase.cs
  src/System.Windows.Forms/System/Windows/Forms/Controls/Buttons/ButtonInternal/DarkMode/ButtonDarkModeAdapter.cs
  src/System.Windows.Forms/System/Windows/Forms/Controls/Buttons/ButtonInternal/DarkMode/ButtonDarkModeRendererBase.cs
  src/System.Windows.Forms/System/Windows/Forms/Controls/Buttons/ButtonInternal/DarkMode/FlatButtonDarkModeRenderer.cs
  src/System.Windows.Forms/System/Windows/Forms/Controls/Buttons/ButtonInternal/DarkMode/IButtonRenderer.cs
  src/System.Windows.Forms/System/Windows/Forms/Controls/Buttons/ButtonInternal/DarkMode/PopupButtonDarkModeRenderer.cs
  src/System.Windows.Forms/System/Windows/Forms/Controls/Buttons/ButtonInternal/DarkMode/SystemButtonDarkModeRenderer.cs
Labels: servicing-approved, area-DarkMode

#13842 Update LocProject.json with new language set
  eng/Localize/LocProject.json
Labels: area-Infrastructure

#13793 Add unit test for ToolStrip.ToolStripAccessibleObjectWrapperForItemsOnOverflow.cs file
  src/test/unit/System.Windows.Forms/System/Windows/Forms/ToolStrip.ToolStripAccessibleObjectWrapperForItemsOnOverflowTests.cs
Labels: area-test coverage

#13833 Fix 12571 "DisplayMember" property cannot expand
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataMemberFieldEditor.cs
Labels: waiting-review, needs-area-label

#13830 Scale the Cursor editor according to DPI
  src/System.Windows.Forms.Design/src/System/Drawing/Design/CursorEditor.CursorUI.cs
Labels: waiting-review, needs-area-label

#13840 Fix Control.Dispose crash when dependent UserControl fails to load due to missing assembly
  src/System.Windows.Forms/System/Windows/Forms/Control.cs
Labels: waiting-review, needs-area-label

#13863 fix #13861 The custom ForeColor set on PrintPreviewControl is not rendered correctly
  src/System.Windows.Forms/System/Windows/Forms/Printing/PrintPreviewControl.cs
Labels: area-DarkMode

#13853 Scale the Anchor editor according to DPI
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/AnchorEditor.AnchorUI.cs
Labels: needs-area-label

#13890 Add unit tests for DocumentDesigner.cs file
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/DocumentDesignerTests.cs
Labels: area-test coverage
