Repository dotnet/winforms, pull requests merged in 2025-08, with the labels that each got.

#13752 Add code coverage for CheckBoxBaseAdapter
  src/test/unit/System.Windows.Forms/System/Windows/Forms/CheckBoxBaseAdapterTests.cs
Labels: waiting-review, area-test coverage

#13751 Add code coverage for CheckBoxFlatAdapter
  src/test/unit/System.Windows.Forms/System/Windows/Forms/CheckBoxFlatAdapterTests.cs
Labels: waiting-review, area-test coverage

#13745 Add code coverage for ButtonRenderer
  src/test/unit/System.Windows.Forms/System/Windows/Forms/ButtonRendererTests.cs
Labels: waiting-review, area-test coverage

#13726 Add code coverage for RadioButtonBaseAdapter
  src/test/unit/System.Windows.Forms/System/Windows/Forms/RadioButtonBaseAdapterTests.cs
Labels: waiting-review, area-test coverage

#13768 Skip unstable test ListView_Click_On_Second_Column_Does_Not_Alter_CheckBoxesAsync
  src/test/integration/UIIntegrationTests/ListViewTests.cs
Labels: area-Infrastructure

#13758 Add unit test for PropertyGrid.PropertyTabCollection file
  src/test/unit/System.Windows.Forms/System/Windows/Forms/PropertyGrid.PropertyTabCollectionTests.cs
Labels: area-test coverage

#13787 Fix title bar small icon scaling
  src/System.Windows.Forms/Resources/System/Windows/Forms/wfc.ico
  src/System.Windows.Forms/System/Windows/Forms/Form.cs
Labels: area-HDPI, needs-area-label

#13773 Add focused state for DropDownButton and reduces the icon width of the dropdown model button
  src/System.Windows.Forms/PublicAPI.Unshipped.txt
  src/System.Windows.Forms/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/DropDownButton.cs
  src/System.Windows.Forms/System/Windows/Forms/Rendering/ControlPaint.ModernControlButtonState.cs
  src/System.Windows.Forms/System/Windows/Forms/Rendering/ControlPaint_ModernControlButtonRenderer.cs
  src/System.Windows.Forms/System/Windows/Forms/VisualStyles/ComboBoxState.cs
Labels: area-DarkMode

#13795 fix #13777 : Dark Mode: Divider line between Up and Down buttons is not visible in DomainUpDown/NumericUpDown when mouse-over or click them
  src/System.Windows.Forms/System/Windows/Forms/Controls/UpDown/UpDownBase.UpDownButtons.cs
Labels: area-DarkMode

#13802 CommandParameter property: Provide designer support and control CodeDOM serialization
  src/System.Windows.Forms/System/Windows/Forms/Controls/Buttons/ButtonBase.cs
  src/System.Windows.Forms/System/Windows/Forms/Controls/ToolStrips/ToolStripItem.cs
  src/test/unit/System.Windows.Forms/System/Windows/Forms/BinaryFormat/WinFormsBinaryFormattedObjectTests.cs
Labels: area-Binding

#13808 Improve Form.ShowAsync and Form.ShowDialogAsync
  src/System.Windows.Forms/System/Windows/Forms/Form.cs
  src/test/unit/System.Windows.Forms/System/Windows/Forms/FormAsyncExtensions.cs
  src/test/unit/System.Windows.Forms/System/Windows/Forms/FormTests.cs
Labels: area-Infrastructure

#13771 Add check "IsDarkModeEnabled" for FocusForeColor of the CheckedListBox and PropertyGrid
  src/System.Windows.Forms/System/Windows/Forms/Controls/ListBoxes/CheckedListBox.cs
  src/System.Windows.Forms/System/Windows/Forms/Controls/PropertyGrid/PropertyGrid.cs
Labels: area-DarkMode
