Repository dotnet/winforms, pull requests merged in 2025-04, with the labels that each got.

#13220 checkout:self and clean are the default steps, we don't have to specify them in the script
  eng/pipelines/build-PR.yml
  eng/pipelines/build.yml
Labels: area-Infrastructure

#13181 Add code coverage for TabOrder
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/TabOrderTests.cs
Labels: waiting-review, area: test coverage

#13212 Add test for TableLayoutPanelCodeDomSerializer
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/TableLayoutPanelCodeDomSerializerTests.cs
Labels: area: test coverage

#13200 Adds some specific serialization test cases for the `ToolStripMenuItemCodeDomSerializer` class
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ToolStripMenuItemCodeDomSerializerTests.cs
Labels: area: test coverage

#13058 Enable nullability in ToolboxItemSnapLineBehavior
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/ToolboxItemSnapLineBehavior.cs
Labels: waiting-author-feedback, area: NRT

#13242 Enable nullability in MaskedTextBoxTextEditorDropDown
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/MaskedTextBoxTextEditorDropDown.cs
Labels: area-NRT, area: NRT

#13238 removed unreferenced config file
  eng/sdl-tsa-vars.config
Labels: area-Infrastructure

#13260 Suppress IDE0031
  src/System.Private.Windows.Core/src/System.Private.Windows.Core.csproj
  src/System.Windows.Forms/System.Windows.Forms.csproj
Labels: waiting-author-feedback, area-Infrastructure

#13215 Add code coverage for StandardCommandToolStripMenuItem
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/StandardCommandToolStripMenuItemTests.cs
Labels: waiting-review, area: test coverage

#13173 Add unit tests for ParentControlDesigner
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ParentControlDesignerTests.cs
Labels: area: test coverage

#13218 Add code coverage for ToolStripEditorManager
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ToolStripEditorManagerTests.cs
Labels: waiting-review, area: test coverage

#13265 Update System.Windows.Forms.Design.csproj
  src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
Labels: area-Infrastructure

#13255 Disable validation of InputLanguage.LayoutName in non-English modes in test InputLanguage_FromCulture_SupplementalInputLanguages_Expected
  src/test/unit/System.Windows.Forms/System/Windows/Forms/InputLanguageTests.cs
Labels: ready-to-merge

#13140 Removing assertion from constructor EditorServiceContext and update test "InvokeItemsDialog_ShouldThrowException"
  src/System.Windows.Forms.Design/src/Properties/AssemblyInfo.cs
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ListControlUnboundActionListTests.cs
  src/test/integration/UIIntegrationTests/ListControlUnboundActionListTests.cs
Labels: ready-to-merge

#13281 re-enable IDE0059 in the VMR build since it's on SDK p4 already
  src/System.Private.Windows.Core/src/System.Private.Windows.Core.csproj
Labels: area-Infrastructure

#13273 Add unit tests for EditorServiceContext
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/EditorServiceContextTests.cs
Labels: area: test coverage

#13282 Introduces a `DesignerOptionsBuilder` helper that explicitly sets `UseSmartTags = false`
  src/test/integration/DesignSurface/DesignSurfaceExt/DesignSurfaceExt.cs
  src/test/integration/DesignSurface/DesignSurfaceExt/DesignerOptionServiceExt.cs
Labels: area: test coverage

#13287 Avoid serialization with in-process Clipboard use
  src/System.Private.Windows.Core/src/System/Private/Windows/Ole/DataFormatNames.cs
  src/System.Private.Windows.Core/src/System/Private/Windows/Ole/DataStore.cs
  src/System.Private.Windows.Core/tests/System.Private.Windows.Core.Tests/System/Private/Windows/Ole/ClipboardCoreTests.cs
  src/System.Windows.Forms/PublicAPI.Unshipped.txt
  src/System.Windows.Forms/System/Windows/Forms/OLE/Clipboard.cs
  src/System.Windows.Forms/System/Windows/Forms/OLE/WrappingDataObject.cs
  src/test/unit/System.Windows.Forms/System/Windows/Forms/ClipboardTests.cs
Labels: :books: documentation, area-Clipboard, binaryformatter-migration

#13059 Enable nullability in WindowsFormsDesignerOptionService
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/WindowsFormsDesignerOptionService.cs
Labels: waiting-author-feedback, area: NRT

#13309 test code cleanup
  src/test/unit/System.Windows.Forms/ResourceStrings.cs
  src/test/unit/System.Windows.Forms/System/Windows/Forms/ClipboardTests.cs
  src/test/unit/System.Windows.Forms/System/Windows/Forms/NativeToWinFormsAdapterTests.cs
  src/test/util/System.Windows.Forms/Data/ManagedAndRuntimeDataObject.cs
  src/test/util/System.Windows.Forms/Data/TypedDataObject.cs
  src/test/util/System.Windows.Forms/Data/UntypedDataObject.cs
Labels: area-Infrastructure

#13275 Add code coverage for ListViewGroupCollectionEditor
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ListViewGroupCollectionEditorTests.cs
Labels: waiting-review, area: test coverage

#13257 Add code coverage for FlowLayoutPanelDesigner.cs file
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/FlowLayoutPanelDesignerTests.cs
Labels: area: test coverage

#13283 Ignore case for DESC and ASC in BindingSource.Sort
  src/System.Windows.Forms/System/Windows/Forms/DataBinding/BindingSource.cs
  src/test/unit/System.Windows.Forms/System/Windows/Forms/BindingSourceTests.cs
Labels: area-Binding, ready-to-merge

#13297 Issue 10773 add coverage for ToolStripInSituService
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ToolStripInSituServiceTests.cs
Labels: ready-to-merge, area: test coverage

#12959 Prevent Toolbar tooltips from appearing directly under cursor hotspot
  src/System.Windows.Forms/System/Windows/Forms/Controls/ToolStrips/ToolStrip.cs
Labels: ready-to-merge

#13256 Add code coverage for ToolStripContainerActionList
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ToolStripContainerActionListTests.cs
Labels: ready-to-merge, area: test coverage

#13301 Add code coverage for ListViewDesigner
  src/System.Windows.Forms.Design/tests/UnitTests/ListViewDesignerTests.cs
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ListViewDesignerTests.cs
Labels: waiting-review, area: test coverage

#13314 Update the min cmake version to enable native code compilation with cmake shipped in VS public preview .
  src/test/unit/interop/NativeTests/CMakeLists.txt
  src/test/unit/interop/System.Windows.Forms.Interop.Tests.csproj
Labels: area-Infrastructure

#13315 Add memory pressure management to AgileComPointer
  src/System.Private.Windows.Core/src/Windows/Win32/System/Com/AgileComPointer.cs
  src/System.Windows.Forms/System/Windows/Forms/Controls/WebBrowser/HtmlElement.cs
Labels: area-COM

#13320 Add _isReleasingDataSource to prevent unnecessary operations on CurrentCell when changing or releasing DataSource
  src/System.Windows.Forms/System/Windows/Forms/Controls/DataGridView/DataGridView.Methods.cs
  src/System.Windows.Forms/System/Windows/Forms/Controls/DataGridView/DataGridView.cs
Labels: waiting-author-feedback, area-controls-DataGridView

#13324 fix #13305 Baseline SnapLines do not appear in DesignSurface
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DragAssistanceManager.cs
Labels: waiting-author-feedback, area-DesignerSupport

#13294 Skip unstable ListView Tile tests and case ListView_Click_On_Second_Column_Does_Not_Alter_CheckBoxesAsync
  src/test/integration/UIIntegrationTests/ListViewTests.cs
Labels: waiting-author-feedback, area-Infrastructure

#13343 Add Unit Test For issue 13305
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/Behavior/SnapLineTests.cs
Labels: area-Infrastructure

#13345 publishing APIs that we ship in NET10 Preview4
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms/PublicAPI.Shipped.txt
  src/System.Windows.Forms/PublicAPI.Unshipped.txt
Labels: area-Infrastructure

#13347 Update Versions.props
  eng/Versions.props
Labels: area-Infrastructure

#13346 Update resourceManagement.yml
  .github/policies/resourceManagement.yml
Labels: area-Infrastructure

#13340 Update the run-on setting to ubuntu-22.04 in .github/workflows/backport.yml
  .github/workflows/backport.yml
Labels: area-Infrastructure

#13295 fix #13071 Changing properties with RefreshProperties.All does not requery the property list in the PropertyGrid in .net 9 (worked in .net 8)
  src/System.Windows.Forms/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/GridEntry.GridEntryAccessibleObject.cs
  src/System.Windows.Forms/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/PropertyGridView.Flags.cs
  src/System.Windows.Forms/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/PropertyGridView.cs
  src/test/unit/System.Windows.Forms/System/Windows/Forms/PropertyGridTests.cs
Labels: area-controls-PropertyGrid

#13329 Add RetryHelper to fix issue unstable test RoundTrip_DataObject_SupportsTypedInterface
  src/test/unit/System.Windows.Forms/System/Windows/Forms/ClipboardTests.cs
Labels: waiting-review, area-Infrastructure

#12996 Issue 12830 multi target demo console
  .gitignore
  Winforms.sln
  eng/Versions.props
  src/test/integration/DesignSurface/DemoConsole/DemoConsole.csproj
  src/test/integration/DesignSurface/DemoConsole/MainForm.Designer.cs
  src/test/integration/DesignSurface/DemoConsole/MainForm.MyUserControl.cs
  src/test/integration/DesignSurface/DemoConsole/MainForm.cs
  src/test/integration/DesignSurface/DemoConsole/Properties/launchSettings.json
  src/test/integration/DesignSurface/DesignSurfaceExt/DesignSurfaceExt.cs
  src/test/integration/DesignSurface/DesignSurfaceExt/DesignSurfaceExt.csproj
  src/test/integration/DesignSurface/DesignSurfaceExt/NameCreationServiceImp.cs
  src/test/integration/DesignSurface/Directory.Build.props
  src/test/integration/DesignSurface/README.md
Labels: waiting-review

#13341 Add code coverage for DesignerUtils
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/DesignerUtilsTests.cs
Labels: waiting-review, area: test coverage

#13362 Moving tag OperationInReleasingDataSource to function "OnDataSourceDisposed"
  src/System.Windows.Forms/System/Windows/Forms/Controls/DataGridView/DataGridView.Methods.cs
  src/System.Windows.Forms/System/Windows/Forms/Controls/DataGridView/DataGridView.cs
Labels: area-controls-DataGridView

#13354 fix #13344 Disabled ToolstripMenuItems are no longer highlighted
  src/System.Windows.Forms/System/Windows/Forms/Controls/ToolStrips/ToolStripItem.cs
  src/test/unit/System.Windows.Forms/System/Windows/Forms/ToolStripButtonTests.cs
Labels: area-controls-StripControls

#13383 Clean-up dependencies after first VMR sync
  eng/Version.Details.xml
  eng/Versions.props
Labels: area-Infrastructure

#13387 Update CustomButton.cs
  src/test/integration/DesignSurface/DemoConsole/CustomControls/CustomButton.cs
Labels: area-Infrastructure

#13385 Fix Color value in PageSettings
  src/System.Drawing.Common/src/System/Drawing/Printing/PageSettings.cs
  src/System.Drawing.Common/tests/Helpers.cs
  src/System.Drawing.Common/tests/System/Drawing/Printing/PageSettingsTests.cs
  src/System.Drawing.Common/tests/System/Drawing/Printing/PrintDocumentTests.cs
Labels: area-Infrastructure

#13381 Removing all skip tag and add ListViewUITests in a new collection and add retry mechanism
  src/test/integration/UIIntegrationTests/ListViewTests.cs
Labels: area-Infrastructure

#13373 Add Framework folder from multitarget repository to the new multi-target version of DemoConsole
  src/test/integration/DesignSurface/DesignSurfaceExt/Framework/Analyzer.cs
  src/test/integration/DesignSurface/DesignSurfaceExt/Framework/HashHelpers.cs
  src/test/integration/DesignSurface/DesignSurfaceExt/Framework/Index.cs
  src/test/integration/DesignSurface/DesignSurfaceExt/Framework/Range.cs
  src/test/integration/DesignSurface/DesignSurfaceExt/Framework/readme.txt
  src/test/integration/DesignSurface/DesignSurfaceExt/NameCreationServiceImp.cs
  src/test/integration/DesignSurface/DesignSurfaceExt/Properties/AssemblyInfo.cs
  src/test/integration/DesignSurface/Directory.Build.props
Labels: area-Infrastructure

#13384 Add code coverage for DesignerUtils
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/DesignerUtilsTests.cs
Labels: waiting-review, area: test coverage

#13393 Fix 13286: Add a null check before getting SelectionService and BehaviorService
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripTemplateNode.cs
Labels: area-NRT

#13397 Move `DataGridViewChooseDataSourceActionList` into a separate file
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewDesigner.DataGridViewChooseDataSourceActionList.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewDesigner.cs
Labels: waiting-review, area-NRT
