Repository dotnet/winforms, pull requests merged in 2025-01, with the labels that each got.

#12662 Write unit test for DataGridViewAddColumnDialog
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/DataGridViewAddColumnDialogTests.cs
Labels: waiting-review

#12646 Get rid of an unexpected white line above the status strip due to a changed
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/StatusStrip.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/StatusStripTests.cs
Labels: ready-to-merge

#12706 fix issue 12680 [HDPI]The dot line disappeared between checkbox and Expand/collapse in HDPI mode
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/TreeView/TreeView.cs
Labels: ready-to-merge

#12682 fix #12663 [Accessibility][High Contrast] ToolStrip grip icon colour contrast is less than 4.5:1 in Normal Mode and HC Desert mode
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripHighContrastRenderer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolstripProfessionalRenderer.cs
Labels: ready-to-merge

#12711 Add code coverage for ToolStripPanelControlCollection_XYComparer
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripPanel.ToolStripPanelControlCollection.XYComparerTests.cs
Labels: waiting-review

#12719 [release/9.0] Get rid of an unexpected white line above the status strip due to a changed renderer
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/StatusStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripHighContrastRenderer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripSystemRenderer.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolstripProfessionalRenderer.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/StatusStripTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripButtonTests.Rendering.cs
Labels: Servicing-approved

#12718 Add unit test for LinkAreaEditor
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/LinkAreaEditorTests.cs
Labels: waiting-review

#12730 PR Feedback Cleanup files in Separate PR
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/SingleInstanceHelpers.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/WindowsFormsApplicationBase.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Network.DownloadFile.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Network.UploadFile.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/NetworkUtilities.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Interaction.vb
  src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/MyServices/ClipboardProxy.vb
  src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/TestUtilitiesTests.vb
  src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/TestUtilities/TestData/PathSeparatorTestData.vb
  src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/TestUtilities/VbFileCleanupTestBase.vb
Labels: ready-to-merge

#12673 Add code coverage for DataGridViewRowHeightInfoPushedEventArgs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewRowHeightInfoPushedEventArgsTests.cs
Labels: ready-to-merge

#12658 [release/8.0] Fix WM_DESTROY message handling in ActiveX control
  src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
Labels: Servicing-approved

#12708 Fill missing information in resource files so they can be loaded correctly
  src/Microsoft.VisualBasic.Forms/src/Resources/Microsoft/VisualBasic/MyServices/Internal/ProgressDialog.resx
  src/System.Windows.Forms/tests/AccessibilityTests/Menu_Toolbars_controls.resx
Labels: ready-to-merge

#12731 [release/8.0] Fix #12661 Null Reference Exception: System.Windows.Forms.TabControl<WmSelChange>
  src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControlTests.cs
Labels: Servicing-approved

#12737 Revert changes in PR11529 and PR11761
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.FlatComboAdapter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripComboBox.ToolStripComboBoxControl.ToolStripComboBoxFlatComboAdapter.cs
Labels: :boom: regression-release

#12701 Add a null-check for "DataGridView" property before executing OnMouseUp in function OnMouseUpInternal
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewCell.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellTests.cs
Labels: :boom: regression-release

#12735 Fix code analysis issues
  src/System.Drawing.Common/src/System/Drawing/Printing/PrinterSettings.StringCollection.cs
  src/System.Private.Windows.Core/src/System/Collections/Generic/CollectionExtensions.cs
  src/System.Private.Windows.GdiPlus/System/Drawing/IIcon.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/CollectionEditor.CollectionEditorCollectionForm.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerHost.cs
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.CodeDomSerializationStore.ComponentListCodeDomSerializer.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/SelectionManager.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/TableLayoutPanelBehavior.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/ToolStripPanelSelectionBehavior.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/CommandSet.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FlowLayoutPanelDesigner .cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/OleDragDropHandler.cs
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TableLayoutPanelDesigner.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ActiveX/AxHost.AxPropertyDescriptor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
  src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/ICom2ExtendedBrowsingHandler.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStrip.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripDropDown.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Dialogs/TaskDialog/TaskDialogPage.cs
Labels: draft

#12745 [release/9.0] Only Unwrap If Given IDataObject
  src/System.Private.Windows.Core/src/Windows/Win32/System/Com/ComHelpers.cs
  src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
  src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
  src/System.Windows.Forms/tests/ComDisabledTests/ClipboardComTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ClipboardTests.cs
Labels: :no_entry_sign: * NO-MERGE *, Servicing-approved

#12760 Enable nullability in ComponentDocumentDesigner
  src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ComponentDocumentDesigner.cs
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ComponentDocumentDesignerTests.cs
Labels: waiting-review, area: NRT

#12638 Add switch "MoveTreeViewTextLocOnePixel" for update the drawing position of the Treeview control text
  src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/TreeView/TreeView.cs
Labels: :books: documentation, ready-to-merge

#12798 Revert "fix issue 12680 [HDPI]The dot line disappeared between checkb…
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/TreeView/TreeView.cs
Labels: ready-to-merge

#12806 Don't unwrap wrapped DataObject inner data store (#12800)
  src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ClipboardTests.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataObjectTests.cs
Labels: Servicing-approved

#12814 Add code coverage for DataGridViewButtonColumn
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewButtonColumnTests.cs
Labels: waiting-review

#12820 Added a condition to check if `_altCheckBox.Focused` before navigating to the next control. This ensures that the `Alt` checkbox is not skipped when using the right arrow key.
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ShortcutKeysEditor.ShortcutKeysUI.cs
Labels: ready-to-merge
