Repository dotnet/winforms, pull requests merged in 2025-02, with the labels that each got.

#12785 [release/9.0] WinForms ComboBox border and drop down button are not visible sometimes
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.FlatComboAdapter.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripComboBox.ToolStripComboBoxControl.ToolStripComboBoxFlatComboAdapter.cs
Labels: :no_entry_sign: * NO-MERGE *, servicing-approved

#12821 Fixes Exception being thrown when the space key is pressed on a CheckBoxCell
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewCheckBoxCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewRow.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewRowHeaderCell.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewTextBoxCell.cs
Labels: waiting-for-testing

#12953 Ensure `ComManagedStream` seekable wrapper stream has position of 0
  src/System.Private.Windows.Core/src/Windows/Win32/System/Com/ComManagedStream.cs
  src/System.Private.Windows.Core/tests/System.Private.Windows.Core.Tests/Windows/Win32/System/Com/ComManagedStreamTests.cs
Labels: servicing-consider

#12963 Add code coverage for ToolStripCustomTypeDescriptor
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ToolStripCustomTypeDescriptorTests.cs
Labels: waiting-review

#13023 Consistently throw data on null data
  src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
  src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ClipboardTests.cs
Labels: :book: documentation: breaking

#13008 Enable nullability in TableLayoutPanelResizeGlyph
  src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/TableLayoutPanelResizeGlyph.cs
Labels: area: NRT

#13011 Add code coverage for ControlCodeDomSerializer
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ControlCodeDomSerializerTests.cs
Labels: waiting-review

#13034 fix #12916 Cannot use down to expand ToolStripDropDownButton in toolStrip2 after using right/Left to collapse ToolStripDropDownButton in toolStrip1
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStrip.cs
Labels: waiting-for-testing
