Repository dotnet/winforms, pull requests merged in 2025-05, with the labels that each got.

#13395 Update resourceManagement.yml
  .github/policies/resourceManagement.yml
Labels: area-Infrastructure

#13390 Update developer-guide.md
  docs/developer-guide.md
Labels: area-Infrastructure, :mailbox_with_no_mail: waiting-author-feedback

#13403 Ensure that partial exclusions are shown in the solution explorer
  src/test/integration/DesignSurface/DesignSurfaceExt/DesignSurfaceExt.csproj
  src/test/integration/DesignSurface/DesignSurfaceExt/Framework/HashHelpers.cs
  src/test/integration/DesignSurface/DesignSurfaceExt/Framework/Index.cs
  src/test/integration/DesignSurface/DesignSurfaceExt/Framework/NotNullWhenAttribute.cs
  src/test/integration/DesignSurface/DesignSurfaceExt/Framework/Range.cs
  src/test/integration/DesignSurface/DesignSurfaceExt/PropertyGridExt.cs
  src/test/integration/DesignSurface/Directory.Build.props
Labels: area-Infrastructure

#13405 Upgrade Issue-Labeler to v2.0.0
  .github/workflows/labeler-build-predictor.yml
  .github/workflows/labeler-cache-retention.yml
  .github/workflows/labeler-predict-issues.yml
  .github/workflows/labeler-predict-pulls.yml
  .github/workflows/labeler-promote.yml
  .github/workflows/labeler-train.yml
  .github/workflows/labeler.md
Labels: area-Infrastructure

#13368 Moving some cases from ClipboardTests class to ClipboardCoreTests
  src/System.Private.Windows.Core/tests/System.Private.Windows.Core.Tests/System/Private/Windows/Ole/ClipboardCoreTests.cs
  src/test/unit/System.Windows.Forms/System/Windows/Forms/ClipboardTests.cs
Labels: area-test coverage

#13417 Update label "area:NRT" to "area-NRT"
  .github/policies/resourceManagement.yml
Labels: area-Infrastructure

#13411 [Release/9.0] Fix false-positive WinForms Analyzer diagnostics.
  src/System.Windows.Forms.Analyzers.CSharp/src/System/Windows/Forms/CSharp/Analyzers/MissingPropertySerializationConfiguration/MissingPropertySerializationConfigurationAnalyzer.cs
  src/System.Windows.Forms.Analyzers.VisualBasic/src/Analyzers/MissingPropertySerializationConfiguration/MissingPropertySerializationConfigurationDiagnosticAnalyzer.vb
Labels: :no_entry_sign: * NO-MERGE *, servicing-approved

#13356 [release/9.0] fix #13071 Changing properties with RefreshProperties.All does not requery the property list in the PropertyGrid in .net 9 (worked in .net 8)
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/GridEntry.GridEntryAccessibleObject.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/PropertyGridView.Flags.cs
  src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/PropertyGridView.cs
  src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridTests.cs
Labels: :no_entry_sign: * NO-MERGE *, servicing-approved

#13433 Unify namespaces and class names under DemoConsole
  src/test/integration/DesignSurface/DemoConsole/GlobalUsings.cs
  src/test/integration/DesignSurface/DemoConsole/MainForm.Designer.cs
  src/test/integration/DesignSurface/DemoConsole/MainForm.cs
  src/test/integration/DesignSurface/DesignSurfaceExt/DesignSurfaceExt.cs
  src/test/integration/DesignSurface/DesignSurfaceExt/DesignerOptionServiceExt.cs
  src/test/integration/DesignSurface/DesignSurfaceExt/DesignerSerializationServiceImpl.cs
  src/test/integration/DesignSurface/DesignSurfaceExt/IDesignSurfaceExt.cs
  src/test/integration/DesignSurface/DesignSurfaceExt/NameCreationServiceImp.cs
  src/test/integration/DesignSurface/DesignSurfaceExt/PropertyGridExt.cs
  src/test/integration/DesignSurface/DesignSurfaceExt/TabOrderHooker.cs
  src/test/integration/DesignSurface/DesignSurfaceExt/UndoEngineExt.cs
Labels: waiting-review, area-Infrastructure

#13444 Replace arch-specific package properties with arch neutral ones
  Directory.Build.targets
  eng/Version.Details.xml
  eng/Versions.props
  global.json
Labels: area-Infrastructure

#13431 Allow IDataObjectAsyncCapability
  docs/list-of-diagnostics.md
  src/Common/tests/TestUtilities/AppContextSwitchNames.cs
  src/System.Private.Windows.Core/src/NativeMethods.txt
  src/System.Private.Windows.Core/src/System/Private/Windows/CoreAppContextSwitches.cs
  src/System.Windows.Forms.Analyzers/src/System/Windows/Forms/Analyzers/Diagnostics/DiagnosticIDs.cs
  src/System.Windows.Forms/PublicAPI.Unshipped.txt
  src/System.Windows.Forms/System/Windows/Forms/OLE/DropTarget.cs
  src/System.Windows.Forms/System/Windows/Forms/OLE/IAsyncDropTarget.cs
Labels: :books: documentation, area-drag/drop

#13479 Publish unpublished APIs
  src/System.Windows.Forms/PublicAPI.Shipped.txt
  src/System.Windows.Forms/PublicAPI.Unshipped.txt
Labels: area-Infrastructure

#13483 Update resourceManagement.yml and Versions.props
  .github/policies/resourceManagement.yml
  eng/Versions.props
Labels: area-Infrastructure

#13526 fix #13508 Original text box is not empty after drag and drop the value to a new text box
  src/System.Windows.Forms/System/Windows/Forms/OLE/DropTarget.cs
Labels: area-controls-PropertyGrid

#13530 Handle ThreadContext cache more cleanly
  src/System.Windows.Forms/System/Windows/Forms/Application.ThreadContext.cs
Labels: needs-area-label
