Repository dotnet/winforms, pull requests merged in 2025-06, with the labels that each got.

#13542 Fix 13538: Update method Drop of DropTarget.cs
  src/System.Windows.Forms/System/Windows/Forms/OLE/DropTarget.cs
Labels: needs-area-label

#13561 Introduce FormScreenCaptureMode property on Form
  src/System.Windows.Forms.Primitives/src/NativeMethods.txt
  src/System.Windows.Forms/PublicAPI.Unshipped.txt
  src/System.Windows.Forms/Resources/SR.resx
  src/System.Windows.Forms/Resources/xlf/SR.cs.xlf
  src/System.Windows.Forms/Resources/xlf/SR.de.xlf
  src/System.Windows.Forms/Resources/xlf/SR.es.xlf
  src/System.Windows.Forms/Resources/xlf/SR.fr.xlf
  src/System.Windows.Forms/Resources/xlf/SR.it.xlf
  src/System.Windows.Forms/Resources/xlf/SR.ja.xlf
  src/System.Windows.Forms/Resources/xlf/SR.ko.xlf
  src/System.Windows.Forms/Resources/xlf/SR.pl.xlf
  src/System.Windows.Forms/Resources/xlf/SR.pt-BR.xlf
  src/System.Windows.Forms/Resources/xlf/SR.ru.xlf
  src/System.Windows.Forms/Resources/xlf/SR.tr.xlf
  src/System.Windows.Forms/Resources/xlf/SR.zh-Hans.xlf
  src/System.Windows.Forms/Resources/xlf/SR.zh-Hant.xlf
  src/System.Windows.Forms/System/Windows/Forms/Form.cs
  src/System.Windows.Forms/System/Windows/Forms/ScreenCaptureMode.cs
  src/test/unit/System.Windows.Forms/System/Windows/Forms/FormTests.cs
Labels: area-Infrastructure

#13513 related to issue 10466: add short cut ↑, ↓, ←, → to demo console
  src/test/integration/DesignSurface/DemoConsole/MainForm.cs
  src/test/integration/DesignSurface/DesignSurfaceExt/DesignSurfaceExt.cs
Labels: area-Infrastructure

#13546 fix #13539 Unable to select ToolStripMenuItem and TooStripTextBox of MenuStrip2 in DemoConsole application
  src/test/integration/DesignSurface/DemoConsole/MainForm.cs
Labels: area-Infrastructure

#13498 Add code coverage for UpDownBase.UpDownBaseAccessibleObject
  src/test/unit/System.Windows.Forms/System/Windows/Forms/AccessibleObjects/UpDownBase.UpDownBaseAccessibleObjectTests.cs
Labels: waiting-review, area-test coverage

#13497 Add unit test for GridEntryRecreateChildrenEventArgs.cs file
  src/test/unit/System.Windows.Forms/System/Windows/Forms/GridEntryRecreateChildrenEventArgsTests.cs
Labels: waiting-review, area-test coverage

#13586 Update copilot instructions
  .github/copilot-instructions.md
  .github/copilot/GDIPlus-copilot-instructions.md
  Winforms.sln
Labels: area-Infrastructure

#13512 Add unit test for HtmlElementErrorEventArgs.cs file
  src/test/unit/System.Windows.Forms/System/Windows/Forms/HtmlElementErrorEventArgsTests.cs
Labels: area-test coverage

#13514 Skip unstable ListView UI tests
  src/test/integration/UIIntegrationTests/ListViewTests.cs
Labels: area-Infrastructure

#13457 Add code coverage for ApplicableToButtonAttribute
  src/test/unit/System.Windows.Forms/System/Windows/Forms/ButtonTests.cs
Labels: waiting-review, area-test coverage

#13523 Add unit test for WebBrowserUriTypeConverter.cs file
  src/test/unit/System.Windows.Forms/System/Windows/Forms/WebBrowserUriTypeConverterTests.cs
Labels: waiting-review, area-test coverage

#13570 Related to #10466 Support Tab key in the demo console
  src/test/integration/DesignSurface/DemoConsole/MainForm.cs
  src/test/integration/DesignSurface/DesignSurfaceExt/DesignSurfaceExt.cs
Labels: area-Infrastructure

#13534 Fix 13288 by add Task.Delay for test ListView_Click_On_Second_Column_Does_Not_Alter_CheckBoxesAsync
  src/test/integration/UIIntegrationTests/ListViewTests.cs
Labels: area-Infrastructure

#13578 Add do...while loop in the SetValue method of SerializationResourceManager.cs until resourceName is unique
  src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ResourceCodeDomSerializer.SerializationResourceManager.cs
Labels: needs-area-label

#13588 Update TreeView's TvnEndLabelEdit method to set label to null when no text has changed
  src/System.Windows.Forms/System/Windows/Forms/Controls/TreeView/TreeView.cs
Labels: needs-area-label

#13601 Public Unshipped APIs
  src/System.Windows.Forms/PublicAPI.Shipped.txt
  src/System.Windows.Forms/PublicAPI.Unshipped.txt
Labels: area-Infrastructure

#13484 Add code coverage for DomainItemAccessibleObjectTests
  src/test/unit/System.Windows.Forms/System/Windows/Forms/DomainItemAccessibleObjectTests.cs
Labels: waiting-review, area-test coverage

#13464 Adding GetData test and SetAudio tests to ClipboardCoreTests
  src/System.Private.Windows.Core/tests/System.Private.Windows.Core.Tests/System/Private/Windows/Ole/ClipboardCoreTests.cs
Labels: waiting-review, needs-area-label

#13445 Issue 10773 Adds code coverage for public members of `ChangeToolStripParentVerb`.
  src/System.Windows.Forms.Design/tests/UnitTests/Mocks/MockSite.cs
  src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ChangeToolStripParentVerbTests.cs
Labels: waiting-review, area-test coverage

#13533 Add unit test for GridToolTip.cs file
  src/test/unit/System.Windows.Forms/System/Windows/Forms/PropertyGridInternal/GridToolTipTests.cs
Labels: waiting-author-feedback, area-test coverage

#13594 Add dotnet.config to opt-in MTP `dotnet test`
  dotnet.config
Labels: area-Infrastructure

#13620 Fix merge issue in ToolStripRenderer (Sizing Grip).
  src/System.Windows.Forms/System/Windows/Forms/Controls/ToolStrips/StatusStrip.cs
  src/System.Windows.Forms/System/Windows/Forms/Controls/ToolStrips/ToolStripRenderer.cs
Labels: area-DarkMode

#13342 Add test for PR 13320
  src/test/integration/UIIntegrationTests/DataGridViewTests.cs
Labels: waiting-review, area-Infrastructure

#13595 Cleanup for XUnitV3Version
  eng/Versions.props
Labels: area-Infrastructure

#13626 Update ListView_Click_On_Second_Column_Does_Not_Alter_CheckBoxesAsync to add judgment and InvokeAsync
  src/test/integration/UIIntegrationTests/ListViewTests.cs
Labels: area-Infrastructure

#13632 Update xunit.v3 and xunit.stafact
  eng/Versions.props
Labels: area-Infrastructure

#13547 Add code coverage for DataGridViewImageColumn
  src/test/unit/System.Windows.Forms/System/Windows/Forms/DataGridViewImageColumnTests.cs
Labels: area-test coverage

#13524 Add code coverage for DataGridVieLinkCell
  src/test/unit/System.Windows.Forms/System/Windows/Forms/DataGridViewLinkCellTests.cs
Labels: waiting-review, area-test coverage
